### ISSUE TITLE
Reports of strange eta distributions for e-gamma and jets

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#106]
Simone Genai writes:

```
In particular, running on CMSSW_7_6_0 +    
  git cms-merge-topic cms-l1t-offline:l1t-dev-recipe-CMSSW_7_6_0
and then 
   cmsRun L1Trigger/L1TCommon/test/runL1TReEmulateFromRAW.py
In the meantime I have tried modifying the configuration of the L1UpgradeTreeProducer
filling in the simCaloStage1FinalDigis (at the moment I am not really interested
 in muons so far). The problem is that when I run with this modification the ntuple is filled 
but the eta distrbution of few objects (egamma and jets) has some weird asymmetry that 
looks like what Mario got in the past.  Is there a known fix for it?
```

**Comment by mulhearn** [comment]
Would be helpful to know which samples you ran over.  I'll try to reproduce the problem and hand it off to the Stage-1 calo experts.

**Comment by gennai** [comment]
I have just run the script L1TCommon/test/runL1TReEmulateFromRAW.py
with the inputFile as it is in git: 
fileNames = cms.untracked.vstring('/store/data/Run2015B/DoubleMuon/RAW/v1/000/251/251/00000/9C66B64C-CA25-E511-818A-02163E0140E1.root', 
        '/store/data/Run2015B/DoubleMuon/RAW/v1/000/251/251/00000/DA60E454-CA25-E511-BFF0-02163E01207C.root'),
    lumisToProcess = cms.untracked.VLuminosityBlockRange("251251:1-251251:31", "251251:33-251251:97", "251251:99-251251:167"),

Please note that I had to change the GT as it was set to MC even if the default input file is data.

**Comment by mulhearn** [comment]
@gennai:  That might be the problem.  The Calo config comes from the GT, so perhaps you are getting the wrong payload for the re-emulation.  I guess when re-emulating we should override these specific payloads appropriately, and use the data tag, but for a quick test maybe just try running with the MC GT and ignoring the errors from the TP generation?

**Comment by gennai** [comment]
It is a bit counterintuitive to me, but I can surely believe you (and going to check it now :-)

Could you please send the list of needed tags fom the MC GT (we may think of adding them by hand on top of the Data GT).

Best,
S.

**Comment by mulhearn** [comment]
Yeah, will do, this requires a bit of thought...

**Comment by gennai** [comment]
So I have re-run again both Stage-1 and Stage-2 emulators, on the same data file and with both options data and MC GlobalTag.
Stage-2 distributions look reasonable for either MC or Data GT (no big differences by eyes can be seen, more details will need further coding on my side)
_Stage-1_ distributions look weird with asymmetries in Eta and Phi with both MC and Data GT.
This is the configuration I used for the Stage-1 case (just only the ntuple maker part):
process.l1UpgradeTree = cms.EDAnalyzer(
    "L1UpgradeTreeProducer",
    egToken = cms.untracked.InputTag("simCaloStage1FinalDigis"),
    tauToken = cms.untracked.InputTag("simCaloStage1FinalDigis:rlxTaus"),
    jetToken = cms.untracked.InputTag("simCaloStage1FinalDigis"),
    muonToken = cms.untracked.InputTag("none"),
    sumToken = cms.untracked.InputTag("simCaloStage1FinalDigis",""),
    maxL1Upgrade = cms.uint32(60)
)

Can you tell if you see something clearly wrong on it?

Best,
S.

**Comment by mulhearn** [comment]
That configuration looks correct to me.  I'll have to look closer...

**Comment by mulhearn** [comment]
Seems most like that something isn't right about the conditions.  Let me play around a bit.

**Comment by mulhearn** [comment]
Conditions look OK...  Now thinking this is a problem with our ntupler when using the Stage-1 calo inputs... looking.

**Comment by mulhearn** [comment]
These look fine to me as long as I require Et>0 for the objects.  Do you apply such a cut?

(Maybe we should do this in ntuple to avoid future confusion.)

**Comment by mulhearn** [comment]
There might still be some tau's missing from the Stage-1 ntuple.

**Comment by gennai** [comment]
I did NOT, in the past only ?Jet/Tau objects above 10 GeV were saved (if I am not wrong).

Could you add a minimal cut at the ntuple level?
BTW, is this feature also present in stage-2 ntuple (no low pT cut applied?)

Best,
S
Il giorno 17 dic 2015, alle ore 13:21, mulhearn <notifications@github.com<mailto:notifications@github.com>> ha scritto:

These look fine to me as long as I require Et>0 for the objects. Do you apply such a cut?

(Maybe we should do this in ntuple to avoid future confusion.)

**Comment by mulhearn** [comment]
Thanks for the testing cycles.  I'm about to push a new version with cut on pt>0 and warning about the GT in the config file.

**Comment by mulhearn** [comment]
(Also handles stage1 ntuple automatically when you change era)

**Comment by mulhearn** [comment]
This one is closed now, but I'll follow up on the remaining issues uncovered on this thread:

   https://github.com/cms-l1t-offline/cmssw/issues/101
