### ISSUE TITLE
Missing changes after rebase of Correlator code

### ISSUE THREAD

**Issue by EmyrClement** [cms-l1t-offline/cmssw#1081]
#1063 is a rebase of #1060 from 123X to 125X.  However it looks like some changes got lost in the rebase.

Some missing changes were noticed in the [PR to CMSSW master](https://github.com/cms-sw/cmssw/pull/40670), as they prevented the L1 sequence from running.  These were fixed in #1067, which is also ported to the PR to master.

Since then, I've now noticed other changes are missing, where the seeded cone jets produced from the extended puppi candidates are not in the event content (comparing [123X](https://github.com/cms-l1t-offline/cmssw/pull/1060/files#diff-9ee5d95b80750ddfe3e1fb7513dbd7cf445e6c1b52239b3275dc652d385ea4f0) and [125X](https://github.com/cms-l1t-offline/cmssw/pull/1063/files#diff-9ee5d95b80750ddfe3e1fb7513dbd7cf445e6c1b52239b3275dc652d385ea4f0).  This means the objects the b jet NN `edm::ValueMap`  reference to don't exist in the output root file.

I can fix this instance - @cecilecaillol @aloeliger should I add this to the existing PR to master, or make an independent PR?

@gpetruc can you check that there aren't any other cases like this that were missing after the rebase?  Or could you point out which commit/constituent PRs of #1060 may not be caught by any CI?

@mcepeda @thesps

**Comment by aloeliger** [comment]
@cecilecaillol this one is sort of up to you. I would lean towards making an independent PR to not upset the [ongoing review](https://github.com/cms-sw/cmssw/pull/40670), but you're closer to this one than I am. Sorry to keep bugging you about this one, but hopefully it can be one of your last software convener acts.

**Comment by aloeliger** [comment]
@EmyrClement I believe after discussion with @cecilecaillol yesterday the preference is that you open your own PR to central CMSSW with these changes. We can take a look at it there.
