### ISSUE TITLE
Many Puppi candidates with phi=0

### ISSUE THREAD

**Issue by EmyrClement** [cms-l1t-offline/cmssw#1113]
#1063 introduced a feature leading to an excess of seeded cone/histo jets with phi=0.  Following this upstream, I can see there are many barrel Puppi candidates with phi = 0:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4438699/234986603-0db69f13-e031-4671-b9f7-d0dfb7fcb688.png">

And the earliest I can see this is in the calo clusters:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4438699/234986894-c969c21b-060c-4f60-9bfc-35ad5edf6b12.png">

It seems the underlying PR that introduced this was [#98 to p2l1pfp](https://github.com/p2l1pfp/cmssw/pull/98) 

Something in the ECAL-HCAL linking appears to cause this, and these are the [relevant lines](https://github.com/cms-l1t-offline/cmssw/blob/l1t-phase2-v58/L1Trigger/Phase2L1ParticleFlow/src/CaloClusterer.cc#L519-L520), in `l1tpf_calo::SimpleCaloLinkerBase::fetch` :

```
      ret->emplace_back(cluster.et,
                        photon ? cluster.ecal_eta : cluster.eta,
                        photon ? cluster.ecal_phi : cluster.phi,
                        cluster.ecal_et > 0 ? std::max(cluster.et - cluster.ecal_et, 0.f) / cluster.ecal_et : -1,
                        photon);
```

It seems `cluster.ecal_eta` and `cluster.ecal_phi` are always zero, so whenever `photon` is true, the cluster eta/phi is set to zero.  Removing the conditional and using 'cluster.phi' for all clusters solves the problem (with a hack).  So it's likely that the calculation of `cluster.ecal_phi` is the problem, and there's probably a similar problem with eta as well, though I didn't see an obvious change in the jet eta distribution.

I think this is as far as I can get right now with debugging this issue, without some help from people who are more familiar with the code.  Now that Dylan has left, who is best positioned to help debug this further? 

@gpetruc @violatingcp

**Comment by EmyrClement** [comment]
Looking a bit closer, I see that `cluster.ecal_eta/phi` is only set when using the `CombinedCaloLinker` (added by this PR), whereas `FlatCaloLinker` is used by default.

I think the fix could then be trivial - we could set `cluster.ecal_eta/phi` to `cluster.eta/phi` when running either `FlatCaloLinker` or `SimpleCaloLinker`?

**Comment by gpetruc** [comment]
Hi Emyr,
Yes, the proposed fix of using the cluster eta & phi for the other linkers looks right to me.
