### ISSUE TITLE
Fix crashes when reEmulating over MC since latest updates.

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#116]
Thomas writes:

```
Apparently, with this input file [1] the muonCSCDigis object that is the
input to the simCscTriggerPrimitiveDigis, which is itself the input to
simEmtfDigis, is empty for some reason.
The result is that I have no EMTF muons as input for the uGMT.
This might also affect the OMTF muons.

If I change the input to the simCscTriggerPrimitiveDigis module to
simMuonCSCDigis (which is already in the MC file) by adding the two
lines [2] to my config file, I get EMTF muons.
```

Very good, but then still need to track down this:

```
one thing to add since I realized that I did not have the latest commits
from the dev-recipes branch.
Pulling those I now get a segfault that seems to be coming from
process.simGtStage2Digis (At least it does not occur if I take out that
module). The relevant parts of the stack are here [3].
Looks like there is a problem handling the incoming muon (that can have
non-zero BX after the merge).
```

**Comment by thomreis** [comment]
The input file where I noticed it is:
root://xrootd.unl.edu//store/mc/Fall13dr/Neutrino_Pt-2to20_gun/GEN-SIM-RAW/tsg_PU20bx25_POSTLS162_V2-v1/00000/00276D94-AA88-E311-9C90-0025905A6060.root

The segfault occured somewhere between event 350 and 400 if I remember correctly.

**Comment by thomreis** [comment]
I have been looking at this a bit more and it seems that the uGT emulator cannot handle muons in BX < -2 or BX > +2.

In order to reproduce this check out this branch https://github.com/thomreis/cmssw/tree/l1t-muon-pass2-CMSSW_8_0_0_pre5_uGT-segfault and run https://github.com/thomreis/cmssw/blob/l1t-muon-pass2-CMSSW_8_0_0_pre5_uGT-segfault/L1Trigger/L1TCommon/test/runL1TReEmulateFromRAW.py
The MC sample file is remote so a voms-prox-init --voms cms is necessary.
The segfault happens in event 196 which has one muon in BX=-3.

@blwiner or @puigh can you have a look please?

**Comment by puigh** [comment]
We were working under the assumption that the uGT would be working only in
a range of 5 bx (-2 to 2), but we will confirm with Takashi that it is 5
and not 7 bx. We should follow what the hardware is doing. This is
configurable, and it would be an easy change if we decided to update. That
being said, it is a bug that it produces a segfault, and we will put in
protection to keep this from happening.

Once we find the specification and put in the fix, where should we push
these changes? There seem to be quite a few places these days.

**Comment by thomreis** [comment]
From the hardware we are also sending from -2 to +2 only. Except last December when we had special readout menus.
Definitely good to add some protection though.

I am not sure in which branch this should go. l1t-muon-pass2-CMSSW_8_0_0_pre5 perhaps and maybe also l1t-dev-recipe-CMSSW_7_6_0. Perhaps @mulhearn can help.

**Comment by puigh** [comment]
While we wait for a response from Mike, if you just want to test the full
chain, you can always set this to bx 7 from the configuration:
https://github.com/thomreis/cmssw/blob/l1t-muon-pass2-CMSSW_8_0_0_pre5_uGT-segfault/L1Trigger/L1TGlobal/python/simGtStage2Digis_cfi.py#L10

On Wed, Jan 27, 2016 at 12:29 PM, Darren Puigh <darren.michael.puigh@cern.ch

**Comment by thomreis** [comment]
OK thanks.

**Comment by mulhearn** [comment]
Just push it to whatever branch you are working in, alert me when ready,
and I'll put it where needed...

**Comment by puigh** [comment]
OK, here is the commit on our development branch. It's just a few lines of
code for extra protection with all the changes in one file:
https://github.com/cms-l1t-offline/cmssw/commit/ae56e296a76792c0b69f5cab5c41b4bd49d35716

Let me know if that doesn't work and/or if something else is needed.

**Comment by mulhearn** [comment]
I've put a stripped down version of Darren's fix into both the muon dev branch and the recipe branch.  @thomreis can you try cherry-picking this guy 272f34e0de64eb067d6d29c140f3d30f748f479e and confirm that it fixes your problem?

**Comment by mulhearn** [comment]
The tea worked:

```
Begin processing the 196th record. Run 1, Event 1014275, LumiSection 10188 at 27-Jan-2016 23:55:59.420 CET
Put uGMT output muon in bx -3
Begin processing the 197th record. Run 1, Event 1014276, LumiSection 10188 at 27-Jan-2016 23:55:59.717 CET
...
Begin processing the 500th record. Run 1, Event 1014579, LumiSection 10191 at 27-Jan-2016 23:57:40.758 CET
27-Jan-2016 23:57:41 CET  Closed file root://xrootd.unl.edu//store/mc/Fall13dr/Neutrino_Pt-2to20_gun/GEN-SIM-RAW/tsg_PU20bx25_POSTLS162_V2-v1/00000/00276D94-AA88-E311-9C90-0025905A6060.root
```

**Comment by mulhearn** [comment]
I think we can close this one.
