### ISSUE TITLE
Remove the use of deprecated std::iterator

### ISSUE THREAD

**Issue by aloeliger** [cms-l1t-offline/cmssw#1164]
### What
Taken from https://github.com/cms-sw/cmssw/issues/43009

> The std::iterator was deprecated in C++17. A quick git grep shows it is being used in
> 
>  CondCore/CondDB/interface/GTProxy.h
>  CondCore/CondDB/interface/IOVProxy.h
>  CondCore/CondDB/interface/RunInfoProxy.h
>  CondCore/CondDB/src/DbCore.h
>  Geometry/TrackerGeometryBuilder/test/GeoHierarchyTest.cc
>  Geometry/TrackerNumberingBuilder/interface/trackerStablePhiSort.h
>  L1Trigger/L1TMuonEndCap/src/helper.h
>  MagneticField/Interpolation/src/bstream_iterator.h
>  RecoBTau/JetTagComputer/interface/GenericMVAComputer.h
>  Utilities/General/interface/precomputed_value_sort.h
> (plus in 4 headers in DataFormats/Common, but those are effectively tracked in https://github.com/cms-sw/cmssw/issues/43002)
> 
> For example here https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/ is some description of the deprecation itself, and instructions what to do instead of using std::iterator.

### Recipe to Recreate
N/A

**Comment by aloeliger** [comment]
I'm not sure this is truly an issue in our code: https://github.com/cms-sw/cmssw/issues/43009#issuecomment-1761165146

**Comment by eyigitba** [comment]
Hi @aloeliger , I'm not even sure if this is used in EMTF. We can try commenting out this code and run a test.

**Comment by aloeliger** [comment]
This is not an issue at L1, our usage is undeprecated: https://github.com/cms-sw/cmssw/issues/43009#issuecomment-1761497720
