### ISSUE TITLE
Add MC information to L1TNtuple

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#118]
A reminder from Pierluigi that it would be useful to add some MC info to standard support for L1TNtuple.

**Comment by jimbrooke** [comment]
What MC info is required?  There is already code for generator particles and MC vertices
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_7_6_0/L1Trigger/L1TNtuples/src/L1AnalysisGenerator.cc
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_7_6_0/L1Trigger/L1TNtuples/src/L1AnalysisSimulation.cc

If needed urgently, they are filled now by L1NtupleProducer.  But they should be moved into a single producer (along with additional variables proposed by @thomreis) so L1NtupleProducer can be removed.

**Comment by mulhearn** [comment]
This issue is unused.  Closing.
