### ISSUE TITLE
L1EventTreeProducer

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#119]
@mulhearn I see this module is used in reEmul.py.  The C++ appears to be in L1Trigger/L1TNtuples, but there is no _cfi.py and it's not integrated in the ntuple sequences (eg. L1NtupleRAW_cff.py).  It is redundant with part of L1Trigger/L1TNtuples/python/l1Tree_cfi.py.  What is the plan?

**Comment by jimbrooke** [comment]
Incidentally, this appears to be useful - I just don't know why it is not finished.

**Comment by jimbrooke** [comment]
Also, if many people are developing this package we need a plan.  Uncoordinated changes in ~2011 made this package completely unusable.  Now I've gone to some length to clean it up, and I've been committing changes at will because it seemed like no-one else was working on it.  If other people are now actively developing I need to know who, so I can discuss the (many) changes I have planned.

**Comment by mulhearn** [comment]
It seems this was added by Len at the request of consumers of reEmul.py and the worked stopped there.

I think the main consumers are currently L1 DPG plus Simone.

**Comment by jimbrooke** [comment]
@mulhearn OK.  Well I can fix up the missing config snippets for this producer.  But I don’t know how we prevent divergence in future...

**Comment by mulhearn** [comment]
Well, some pain is unavoidable, but if I change e.g. reEmul.py to call the ntuple cfi directly it might minimize it.

**Comment by mulhearn** [comment]
We are handling this one in the CMS driver sequences.   This one is closed.
