### ISSUE TITLE
L1TCalorimeter does not compile with debug messages enabled

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#120]
@mulhearn Compiling with debug message enabled 
scram b -j8 USER_CXXFLAGS="-DEDM_ML_DEBUG"

Results in multiple errors related to CaloParamsHelper, first one below.  I am working around by temporarily changing some LogDebug messages to std::cout

In file included from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/ErrorObj.h:147:0,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/MessageSender.h:6,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/MessageLogger.h:133,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/Framework/src/Worker.h:31,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/Framework/src/Factory.h:5,
                 from /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/Framework/interface/MakerMacros.h:4,
                 from /afs/cern.ch/work/j/jbrooke/stage2/CMSSW_8_0_X_2016-01-20-2300/src/L1Trigger/L1TCalorimeter/plugins/L1TStage2Layer2Producer.cc:30:
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/ErrorObj.icc: In instantiation of 'edm::ErrorObj& edm::ErrorObj::opltlt(const T&) [with T = l1t::CaloParamsHelper]':
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/ErrorObj.icc:44:20:   required from 'edm::ErrorObj& edm::operator<<(edm::ErrorObj&, const T&) [with T = l1t::CaloParamsHelper]'
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/MessageSender.h:47:32:   required from 'edm::MessageSender& edm::MessageSender::operator<<(const T&) [with T = l1t::CaloParamsHelper]'
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/MessageLogger.h:389:26:   required from 'edm::LogDebug_& edm::LogDebug_::operator<<(const T&) [with T = l1t::CaloParamsHelper]'
/afs/cern.ch/work/j/jbrooke/stage2/CMSSW_8_0_X_2016-01-20-2300/src/L1Trigger/L1TCalorimeter/plugins/L1TStage2Layer2Producer.cc:263:30:   required from here
/afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_0_X_2016-01-20-2300/src/FWCore/MessageLogger/interface/ErrorObj.icc:28:8: error: no match for 'operator<<' (operand types are 'std::ostringstream {aka std::basic_ostringstream<char>}' and 'const l1t::CaloParamsHelper')
   myOs << t;
        ^

**Comment by mulhearn** [comment]
Sorry about this.  Will clearly require a proper fix.  For urgent fix we can just comment out the problematic lines.

**Comment by mulhearn** [comment]
Fixed by this commit:  4a886ad3bbd1d1820e85f1c3c281c9ed1744441a
