### ISSUE TITLE
Tracking of PRs into CMSSW 80X 

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#128]
This topic will track PRs into CMSSW made from our 80x integration branch:

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-integration-pass6-80x

The integration branch is up to date with the dev-recipes branch
   https://github.com/cms-l1t-offline/cmssw/commits/l1t-dev-recipe-CMSSW_8_0_0_pre5
at (currently latest) commit ecbb92bed14dbfa4ddc9609c76c8d1170cbe643b.

This PR to muon data will bring L1TMuon/data fully up to date with dev-recipe branch:

   https://github.com/cms-data/L1Trigger-L1TMuon/pull/2 (merged)
   https://github.com/cms-sw/cmsdist/pull/2091 (merged)

This PR to muon data will bring L1TCalibration/data fully up to date with dev-recipe branch:

  https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/7 (merged)
  https://github.com/cms-sw/cmsdist/pull/2124 (merged)

The merged PRs already in CMSSW are:
   cms-sw#13064 condformats for muon (merged)
   cms-sw#13066 global emulation (merged)
   cms-sw#13162 ntuples (merged)
   cms-sw#13065 muon emulation (merged)
   cms-sw#13067 calo stage2 emulation (merged)
   cms-sw#13202 cond formats for L1TGlobal UTM library (merged)
   cms-sw#13068 framework unpackers (merged)
   cms-sw#13160 update calo+muon to dev-recipe algorithm (merged)
   cms-sw#13163 L1TGlobal for UTM library (merged)
   cms-sw#13165 unpackers for twin mux and calo layer 1 (merged)

Not yet merged:
   cms-sw#13166 HLT seeds filter (v2.0) (passes tests, fully signed)

Still in works:
- requested updates to HLT interface:  the subset needed for pre6 are done.  Fixing L1T/HLT for 2016 run will be the focus of next week.
- standard sequences:  the 2015 relVals were left intact for pre6.   Fixing L1T/HLT and other downstream code needed for 2016 relVals will be the focus of next week.
- stage-2 layer-1 calo bitwise emulator (missed pre6)
- serialization checks for L1TUtm objects:  Done, included in PR.

**Comment by mulhearn** [comment]
Just checked the data branches again wrt dev-recipes, and update needed for Calo for these files:

```
#   Flat_Tau_iso_LUT_eff70.txt
#   Flat_Tau_iso_LUT_eff80.txt
#   Flat_Tau_iso_LUT_eff90.txt
#   IsoIdentification_0.5_adapt_v16.01.28.txt
#   egCompressLUT_v3.txt
#   egTrimmingLUT_10_v16.01.19.txt
```

**Comment by mulhearn** [comment]
Comparing current dev-recipes branch to integration branch:

```
mulhearn@lxplus0026>git diff --name-only cf3e45f41c25f7c4c3ff28f94789a0601f47f4db..ecbb92bed14dbfa4ddc9609c76c8d1170cbe643b | grep -v data
CondFormats/L1TObjects/interface/CaloParams.h
Configuration/StandardSequences/python/DigiToRaw_cff.py
Configuration/StandardSequences/python/RawToDigi_cff.py
DataFormats/FEDRawData/test/DumpFEDRawDataProduct.cc
EventFilter/RawDataCollector/python/rawDataCollectorByLabel_cfi.py
EventFilter/RawDataCollector/python/rawDataCollector_cfi.py
L1Trigger/Configuration/python/SimL1Emulator_cff.py
L1Trigger/L1TCalorimeter/plugins/L1TStage2Layer2Producer.cc
L1Trigger/L1TCalorimeter/python/L1TCaloStage1_HIFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/L1TCaloStage1_PPFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/L1TCaloStage1_cff.py
L1Trigger/L1TCalorimeter/python/L1TCaloStage1_customForHLT.py
L1Trigger/L1TCalorimeter/python/L1TCaloStage2_PPFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/L1TCaloStage2_cff.py
L1Trigger/L1TCalorimeter/python/L1TRerunHCALTP_FromRaw_cff.py
L1Trigger/L1TCalorimeter/python/L1TRerunHCALTP_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage1_HIFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage1_PPFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage1_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage1_customForHLT.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage2_PPFromRaw_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TCaloStage2_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TRerunHCALTP_FromRaw_cff.py
L1Trigger/L1TCalorimeter/python/deprecate/L1TRerunHCALTP_cff.py
L1Trigger/L1TGlobal/src/L1TGlobalUtil.cc
L1Trigger/L1TMuonBarrel/src/L1MuBMTFConfig.cc
L1Trigger/L1TMuonEndCap/interface/PatternRecognition.h
L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapTrackProducer.cc
L1Trigger/L1TMuonEndCap/src/PatternRecognition.cc
L1Trigger/L1TMuonEndCap/src/core_gen_summer_2013/vppc_sim_lib.cpp
```

The data files are missing on purpose, as they don't go into a separate repo for data.  The remaining changes were all modifications to the original PRs including: reverting back legacy standard sequences (for now), fix to CaloParams explained below, unneeded changes to raw data collector, compilation fixes found during addons.

**Comment by mulhearn** [comment]
Noting that someone did a bad thing in CaloParams:

```
mulhearn@lxplus0026>git diff cf3e45f41c25f7c4c3ff28f94789a0601f47f4db..ecbb92bed14dbfa4ddc9609c76c8d1170cbe643b -- CondFormats/L1TObjects/interface/CaloParams.h
diff --git a/CondFormats/L1TObjects/interface/CaloParams.h b/CondFormats/L1TObjects/interface/CaloParams.h
index 53c5ce0..66eb064 100644
--- a/CondFormats/L1TObjects/interface/CaloParams.h
+++ b/CondFormats/L1TObjects/interface/CaloParams.h
@@ -200,14 +200,12 @@ namespace l1t {


     // DO NOT ADD ENTRIES ANYWHERE BUT DIRECTLY BEFORE "NUM_CALOPARAMNODES"
-    // DO NOT CHANGE NUMERICAL VALUES OF ANY ALREADY EXISTING FIELDS, YOU CAN ONLY EXTEND, AT THE END.
     enum { regionPUS=0,
           egTrimming=1, egMaxHOverE=2, egCompressShapes=3, egShapeId=4, egCalibration=5, egPUS=6, egIsolation=7,
-          tauCalibration=8, tauPUS=9, tauIsolation=10,
-          jetPUS=11, jetCalibration=12,
-          hiCentrality=13, hiQ2=14,
-          tauEtToHFRingEt=15,
-           tauCompress=16,
+          tauCalibration=8, tauPUS=9, tauIsolation=10, tauCompress=11,
+          jetPUS=12, jetCalibration=13,
+          hiCentrality=14, hiQ2=15, 
+          tauEtToHFRingEt=16,
           NUM_CALOPARAMNODES=17
     };
```

See what happened there?  Someone wanted the tau stuff all together nicely in the enum, so they changed the enum ordering.  You can't do this!   Things have already been written to the database with the old enum ordering...  we can only _extend_ these enums, without changing the preceding entries.  This has been fixed in the version sent to CMSSW PRs (the - version is used).

**Comment by rekovic** [comment]
Some comments of Martin at https://github.com/cms-sw/cmssw/pull/13154#issuecomment-178108613
should probably be addressed.

**Comment by mulhearn** [comment]
@gflouris can you merge in the changes in cms-sw#13064 into your own working copy of development area and make sure it works as a drop in replacement?

**Comment by mulhearn** [comment]
To merge this is, go here:
https://github.com/cms-sw/cmssw/pull/13064/commits
to see that you need:

```
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cherry-pick 54411b2376ca47e64d52799b9d622c0ed7aa3650
...
git cherry-pick 6d68c4312180b9b49ad446a9735522f93477ffa4
```

**Comment by mulhearn** [comment]
@thomreis I'll try to get your latest commits in.  Probably possible.

**Comment by mulhearn** [comment]
Need to update HLT branch with three latest commits of Vladimir, addressing HLT group concerns, in
   https://github.com/cms-sw/cmssw/pull/13154#issuecomment-178108613 (DONE)

**Comment by gflouris** [comment]
@mulhearn I tested the bmtf emulation with the changes in cms-sw#13064. The changes work perfectly fine for me.

**Comment by mulhearn** [comment]
@thomreis your last two commits are now in #13065  (please confirm thats what you requested)

**Comment by thomreis** [comment]
@mulhearn this looks good to me. Thanks.

**Comment by mulhearn** [comment]
Human XML parser error?  TriggerObjectCollection checksum did not change.  Posting the diff here before I blow it away with my update to the branch:
```
    <class name="trigger::TriggerObjectCollection"/>
 -  <class name="trigger::TriggerRefsCollections" ClassVersion="13">
 +  <class name="trigger::TriggerRefsCollections" ClassVersion="20">
```
I will confirm after tests are running that the check sum changes all have a dependence on the intended change ...

**Comment by mulhearn** [comment]
The few remaining items in this one are tracked elsewhere.  This one is closed!
