### ISSUE TITLE
Problem running reEmul.py with latest muon updates

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#130]
I noticed that I cannot run "reEmul.py" with the latest muon updates included.  I get errors like this:

```
%MSG-w Input Mismatch:  L1TMuonProducer:simGmtStage2Digis  26-Jan-2016 07:46:58 CET Run: 256843 Event: 469404342
 too many inputs per processor for emtf+ / omtf+. Wedge 5: Size 6
```

@thomreis can you please investigate?

Its on the latest muon dev branch (which merges w/ dev-recipes for convenience):

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-CMSSW_8_0_0_pre5

**Comment by thomreis** [comment]
I saw the same warning yesterday evening on the muon branch. Looks like we get to many muons per BX from either EMTF or OMTF. We expect max 3 and we get 6.

**Comment by thomreis** [comment]
Further investigation shows that there are too many muons from the OMTF.
In every BX=0 it sends 36 muons (6 per sector instead of 3). 

They have all the following properties:
input: bx 0, hwPt: 1, hwPhi: 525, hwEta: 999

These seem to be default fake muons. @akalinow could you please check what the OMTF emulator is producing?

**Comment by akalinow** [comment]
Found a bug: after adapting the ptCode scale to correct convention, dummy candidates had ptCode=1,
instead of 0. I will push the update in a moment (have to setup the new l1t-muon-CMSSW_8_0_0_pre5 area).

**Comment by thomreis** [comment]
I checked this with the old muon branch but no I realize that I cannot run reEmul.py on the new branch at all.
@mulhearn how did you run it? There seem to be two configurations for L1TMuonGlobalParamsESProducer in https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-CMSSW_8_0_0_pre5/L1Trigger/L1TMuon/python 
One is called fakeGmtParams and the other fakeMuonGlobalParams. From looking at them I think that fakeMuonGlobalParams is the more up to date one.

**Comment by mulhearn** [comment]
Indeed, it looks like things got out of sync between dev-recipe and the muon dev branch.  I think I just need to globally make sure the configs (with new names as in dev-recipes) are your latest and greatest.   Let me try... my fixes might break your expert code, but we can fix that next.

**Comment by akalinow** [comment]
The bugfix on OMTF (too many candidates) pushed to both pre1 and pre5 branches.

**Comment by mulhearn** [comment]
Excellent, thanks.

**Comment by mulhearn** [comment]
OK, I've restored all of the unit tests (L1TMuon/L1TMuonXXX/test/runXXX.py) and the reEmul.py now works as well.

I want to clean up the commit history, and I don't want to "change history", so I'll make a new dev branch (pass2) shortly...

**Comment by mulhearn** [comment]
OK, new, fully functional Muon dev branch is here, with all tests I know of working:

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-pass2-CMSSW_8_0_0_pre5

please make sure you expert code works in this version and update as needed.  Thanks for the help debugging!

**Comment by mulhearn** [comment]
This one is closed!

**Comment by thomreis** [comment]
L1Trigger/L1Tmuon/test/runMuon.py still does not work. Need to either run the simMuonQualityAdjusterDigis module or change the inputs for simGmtStage2Digis

**Comment by thomreis** [comment]
Changed input for simGmtStage2Digis in runMuon.py and now it works.
Commit: https://github.com/cms-l1t-offline/cmssw/commit/7812d2caacf5037ff68d10be010ca0fe92bed8ac

Closing this again.

**Comment by mulhearn** [comment]
Weird... I sweat I tested all of them!  Thanks!
