### ISSUE TITLE
Out of date offline JEC in L1Ntuples in l1t-calostage2-CMSSW_7_6_0

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#134]
Offline JEC are out of date in l1t-calostage2-CMSSW_7_6_0.  We were accessing them from an external file in previous versions, but this is broken due to issue described below.
https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2196.html

The fix is either to wait for new JEC In global tag, or to update the branch to newer CMSSW (764?)

**Comment by mulhearn** [comment]
I think we should just move the dev-recipe branch to 764.  But first I want to finish getting the cmsDriver workflows working.

**Comment by mulhearn** [comment]
Follow this up in #135.
