### ISSUE TITLE
L1Calo cmsDriver jobs

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#135]
Here are some jobs that we are using for tests/development/analysis of L1Calo

1) unpack S2Calo and create ntuples
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAW --conditions=auto:run2_data -n 10 --data --filein=/store/data/Run2015D/ZeroBias/RAW/v1/000/260/627/00000/00A76FFA-0C82-E511-B441-02163E01450F.root`

2) as 1) but include re-emulation
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --conditions=auto:run2_data -n 10 --data --filein=/store/data/Run2015D/ZeroBias/RAW/v1/000/260/627/00000/00A76FFA-0C82-E511-B441-02163E01450F.root`

3) as 2) but add AOD info to the ntuple
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --conditions=auto:run2_data -n 10 --data --filein=/store/data/Run2015D/SingleMuon/RAW-RECO/MuTau-PromptReco-v4/000/260/627/00000/00C3E929-6D84-E511-AFDF-02163E0146A5.root`

**Comment by mulhearn** [comment]
Thanks, will try as soon as finished compiling...

**Comment by mulhearn** [comment]
OK, so your workflow clashed rather maximally with my cleanup of the standard sequences.  For now I have restored L1Extra and Stage-1 unpacking to standard sequences even during Stage-2 era.  But it won't be for long!  I'll provide customizations to replace this before I pull them out again.

**Comment by mulhearn** [comment]
They all run now:
(1) produces L1Extra output, as expected.
(2) complains about no HCAL/ECAL TPs, no re-emulated stage-2 outputs.
(3) crashes looking for "sqlite:Summer15_25nsV6_DATA.db"

**Comment by mulhearn** [comment]
and why are you using l1extra for stage-1 calo anyway?!  Don't you have the upgrade objects available?  I thought we agreed to deprecate it!

**Comment by jimbrooke** [comment]
Which release/branch are you using ?  
1) should produce an l1UpgradeTree  as well as l1Extra !
2) I have run in 760 dev branch looked at stage 2 objects, so I think those complaints can be ignored - will check.
3) I will commit the missing file to /data, but I am pretty sure that job will fail further on in all releases/branches other than 760pre7.

Re: L1Extra - I just took what already existed for stage 1, happy to switch to upgrade formats now this is possible (ie. changes to l1 upgrade tree to read iso tau).  However, I am now well behind on all other fronts, so I won't get to this any time soon.

**Comment by jimbrooke** [comment]
Re: L1Extra - I took what existed in October '15 (!) when I wrote these sequences
https://github.com/cms-l1t-offline/cmssw/blob/e31b9b985ea9b7eee885d02a6431e3e113fea0b0/L1Trigger/L1TNtuples/python/L1NtupleRAW_cff.py

**Comment by mulhearn** [comment]
So far I am just updating the dev-recipe branch.

About workflow (1), isn't that a stage-1 RAW file in the example, so, absent re-emulation, won't the L1Upgrade tree be empty?  

(2) clearly needs additional debugging.

So (3) I should wait until I move this to 764 before looking into it?

**Comment by jimbrooke** [comment]
I have updated the file in 1) and 2) to one from run 260627, which includes stage 2 calo
/store/data/Run2015D/ZeroBias/RAW/v1/000/260/627/00000/00A76FFA-0C82-E511-B441-02163E01450F.root

**Comment by mulhearn** [comment]
@jimbrooke:  status report on this one is:
1) Works, but there seems to be a problem with the unpacking of Stage-1 Calo.
2) Works (with same problem as 1) and the re-emulation works (except that muon is not included yet)
3) Works (if I copy the sqlite file locally) and I see I see reco quantities in ntuple

So the only major problem seems to be the unpacker for Stage 1.  I see the same problem when I run on your 7_6_0_pre7 branch.  So I guess this one isn't limited to "dev-recipes"...

**Comment by mulhearn** [comment]
@jimbrooke:  the error message from the stage-1 unpacker that I get is:

```
Cannot find an unpacker for
    block: ID 0, size 6
    AMC: # 4, board ID 0x2300
    FED ID 1352, and FW ID 16843264
Cannot find an unpacker for
    block: ID 2, size 6
    AMC: # 4, board ID 0x2300
    FED ID 1352, and FW ID 16843264
Cannot find an unpacker for
    block: ID 4, size 6
    AMC: # 4, board ID 0x2300
    FED ID 1352, and FW ID 16843264
Cannot find an unpacker for
    block: ID 6, size 6
    AMC: # 4, board ID 0x2300
    FED ID 1352, and FW ID 16843264
Cannot find an unpacker for
    block: ID 8, size 6
    AMC: # 4, board ID 0x2300
    FED ID 1352, and FW ID 16843264
...
```

That was as far as I was able to track this so far.

**Comment by mulhearn** [comment]
Finally got the message logger working and I see however:

```
%MSG-d L1T:  L1TRawToDigi:caloStage2Digis 01-Feb-2016 18:01:26 CET  Run: 260627 Event: 396678164 JetUnpacker.cc:72
Jet: eta 58 phi 60 pT 23 qual 0 bx 2
```

So maybe downstream of unpacker after all...

**Comment by mulhearn** [comment]
Ugggh, says it right there... thats the caloStage2Digis having success.  (With proper Error logger output) its clear problem is with stage 1 unpacker:

```
%MSG-d L1T:  L1TRawToDigi:caloStage1Digis 01-Feb-2016 18:22:00 CET  Run: 260627 Event: 396678165 L1TRawToDigi.cc:233
Cannot find an unpacker for
        block: ID 2, size 6
        AMC: # 4, board ID 0x2300
        FED ID 1352, and FW ID 16843264
```

**Comment by mulhearn** [comment]
@bortigno example cmsDriver recipe #3 should get you started.  Only stage-1 unpacking appears to be be broken.

**Comment by mulhearn** [comment]
@bortigno you'll still need an update with me to add re-emulation of muons to this example before muons will work... but you can get started.

**Comment by bortigno** [comment]
ok thank you. i will try to run on some data tonight.

**Comment by bortigno** [comment]
@mulhearn @jimbrooke which release and which branch am I supposed to use to run this recipe? I tried 800_pre5 release and l1t-dev-recipe-CMSSW_8_0_0_pre5 branch giving me this error: Connection on "sqlite:Summer15_25nsV6_DATA.db" cannot be established.

**Comment by jimbrooke** [comment]
We really need to find a solution for this!  It is just the latest offline JEC.  For now, you can copy the file from my public area
cp ~jbrooke/public/Summer15_25nsV6_DATA.db .

**Comment by jimbrooke** [comment]
@mulhearn @matz-e I guess this is of interest.

I reproduced the stage 1 unpacker problem.  

As shown in the error message, the FW ID in this data is 0x1010200, which I confirmed by inspecting the raw data.  But 0x1010200 & 0xff000000 = 0x1000000 so the unpacker sets itself up using the fake MC setup
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre5/EventFilter/L1TRawToDigi/src/implementations_stage1/CaloSetup.cc#L77

Which means it expects board ID 0x200D.  But this is data, where the board ID is 0x2300.  Hence nothing can be unpacked.

Looking in 74X/76X (in which unpacking appears to work) the equivalent line is 
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/EventFilter/L1TRawToDigi/src/implementations_stage1/CaloSetup.cc

Here, (0x1010200 >> 24) = 0x1 so the condition fails and the unpacker is properly setup.

I guess the problem starts with this commit
https://github.com/cms-l1t-offline/cmssw/commit/299072a7940492e9613ef1915ce9a7bef60ff480

**Comment by jimbrooke** [comment]
Looking a bit closer I guess what is missing is a line in
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre5/EventFilter/L1TRawToDigi/python/caloStage1Digis_cfi.py

that will set this to false by default (assuming that is the desired behaviour, I think it is)
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre5/EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc#L89

Although I don't understand why the framework did not complain about a missing tracked parameter...???

**Comment by mulhearn** [comment]
In the release:
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/EventFilter/L1TRawToDigi/plugins/L1TRawToDigi.cc#L258
there is an explicit FWoverride parameter that was supposed to fix all this....  I guess this got mangled in our dev release.

**Comment by mulhearn** [comment]
re: sqlite file For lack of a better place, I can just put in the L1TCalorimeter data area when I get a chance....

**Comment by matz-e** [comment]
Trying to unsort this in my head… there's a bit too much branch- and merge-juggling going on IMHO. @jimbrooke I think there's a commit that reverted part of this one:

https://github.com/cms-sw/cmssw/commit/299072a7940492e9613ef1915ce9a7bef60ff480

Where both the plugin and the config should do the same w.r.t. the firmware version. Compare:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre5/EventFilter/L1TRawToDigi/src/implementations_stage1/CaloSetup.cc#L72
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/EventFilter/L1TRawToDigi/src/implementations_stage1/CaloSetup.cc#L72

**Comment by mulhearn** [comment]
@matz-e:  anyway, right, I think that is the only error... the convention is that mc has all upper 8 bits set to one, correct?

As to the branches, with this fix, dev-recipe branch will be fully functional for everyone, and the latest 11 PRs into CMSSW will bring 80X_pre6 in sync with dev-recipe.  So things should get cleaner soon.

**Comment by mulhearn** [comment]
I brought back the 7_4_16 version of unpacker and indeed Stage-1 works.  Now I'll roll back the changes since and see where we broke it.

**Comment by mulhearn** [comment]
This is working except for unpacking, which I'll follow up elsewhere.
