### ISSUE TITLE
L1T Calo Stage 2 Development Branch

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#140]
Mulhearn has produced a rebased version of the calo development branch against the dev-recipe branch at tag l1t-tsg-v1:

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-CMSSW_8_0_0_pre6

To build this follow the same instructions as here #147, but substitute  `l1t-calostage2-CMSSW_8_0_0_pre6` at the cms-merge-topic step.

The previous calo team dev branch (which will likely still be in use until the above is checked carefully) is:

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-CMSSW_8_0_0_pre5

**Comment by mulhearn** [comment]
@jimbrooke: here you go.  Please let me know when I may delete the (is it 15?) failed calo dev branches.

**Comment by mulhearn** [comment]
Consolidating issues, Jim wrote elsewhere the three cms-driver work flows:

1) unpack S2Calo and create ntuples 
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAW --conditions=auto:run2_data -n 10 --data --filein=/store/data/Run2015D/ZeroBias/RAW/v1/000/260/627/00000/00A76FFA-0C82-E511-B441-02163E01450F.root`

2) as 1) but include re-emulation
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --conditions=auto:run2_data --geometry=Extended2016,Extended2016Reco -n 10 --data --filein=/store/data/Run2015D/ZeroBias/RAW/v1/000/260/627/00000/00A76FFA-0C82-E511-B441-02163E01450F.root`

3) as 2) but add AOD info to the ntuple
`cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --conditions=auto:run2_data --geometry=Extended2016,Extended2016Reco -n 10 --data --filein=/store/data/Run2015D/SingleMuon/RAW-RECO/MuTau-PromptReco-v4/000/260/627/00000/00C3E929-6D84-E511-AFDF-02163E0146A5.root`

**Comment by jimbrooke** [comment]
I'm currently getting this from 3) on std lxplus node.  I'll try another one...

Begin processing the 2nd record. Run 260627, Event 1317516448, LumiSection 720 at 03-Feb-2016 17:01:00.664 CET

std::bad_alloc exception
----- Begin Fatal Exception 03-Feb-2016 17:01:00 CET-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing run: 260627 lumi: 720 event: 1317516448
   [1] Running path 'raw2digi_step'
   [2] Calling event method for module DTTFFEDReader/'dttfDigis'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------

**Comment by apana** [comment]
Hi Jim,

I also got this message when I tried running the
l1t-dev-recipe-CMSSW_8_0_0_pre5 recipe last night. The recipe worked
the night before, so the bug was probably introduced sometime
yesterday.  Mike asked that for now I try:  (RECIPE DELETED)

and that fixed the problem.

-Len

**Comment by mulhearn** [comment]
I should have warned you not to share that magic recipe... that definitely won't work Jim's case, since it will blow away everything up until that particular commit, including stuff he needs....

**Comment by mulhearn** [comment]
Does not crash for me... its before 10 events?

**Comment by apana** [comment]
Hi Mike,

Yes, it was ~10 events.

**Comment by mulhearn** [comment]
Jim currently checking if it is the "--unsafe" option in cms-merge-topic causing the problem.  We had some data format changes.

**Comment by jimbrooke** [comment]
OK, adding the dependent packages did indeed fix the problem.  Thanks Mike!

**Comment by jimbrooke** [comment]
Just a note - HF 1x1 TPs are not produced by default in these jobs, and we seem to be missing some HCAL voodoo.  We have voodoo that previously worked (in 80X IBs) but it is broken in this release (or possibly in these cmsDriver jobs).

**Comment by mulhearn** [comment]
@jimbrooke, please cherry-pick these recent additions to dev-recipes:

65af6edacce1b2d7e25418b19b34d7738c6366ec   (bug fix stage-1 unpacking)
b0e832fc43ccaf56758a3de6138f5e7fc09df086  (utility customs)

**Comment by jimbrooke** [comment]
I added those commits as requested

**Comment by jimbrooke** [comment]
I merged a missing commit
https://github.com/cms-l1t-offline/cmssw/commit/6a67e92f83783dd5734224acf9ffc6c74d180217

This enables the HF 1x1 TPs to be read by the calo emulator and produce forward jets.  However, in order to make this work I had to produce cmsRun configs with cmsDriver as above and then load
Configuration.Geometry.GeometryExtended2016Reco_cff

instead of
Configuration.StandardSequences.GeometryDB_cff

**Comment by jimbrooke** [comment]
Now understand how to enable the 1x1 geometry from the command line.  Add
 --geometry=Extended2016,Extended2016Reco

**Comment by bundocka** [comment]
Running this job:

cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --conditions=auto:run2_data -n 20 --data --filein=/store/data/Run2015D/SingleMuon/AOD/16Dec2015-v1/10000/00A3E567-75A8-E511-AD0D-0CC47A4D769E.root --secondfilein=/store/data/Run2015D/SingleMuon/RAW/v1/000/260/627/00000/62834F8D-4C82-E511-8E4C-02163E013555.root --python_file=ntuple_maker_SMReco.py

in release *\* l1t-calostage2-CMSSW_8_0_0_pre5*\* I get  the following error (that I did not get before in l1t-stage2calo-CMSSW_7_6_0_pre_7):

Begin processing the 1st record. Run 260627, Event 2566871750, LumiSection 1398 at 08-Feb-2016 13:01:11.532 CET

std::bad_alloc exception
----- Begin Fatal Exception 08-Feb-2016 13:01:12 CET-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing run: 260627 lumi: 1398 event: 2566871750
   [1] Running path 'raw2digi_step'
   [2] Calling event method for module DTTFFEDReader/'dttfDigis'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------

**Comment by jimbrooke** [comment]
For the record, this error is fixed by running
git cms-checkdeps -a
to check out the dependent packages, and recompile.

Alternatively, don't use the --unsafe option with git cms-merge-topic.

**Comment by davignon** [comment]
@jimbrooke When running cmsDriver.py in emulation mode, I see the tauIso flag is always set to 0 (not expected for the WP under consideration). After a few quick checks, the problem is somewhere between L1TStage2Layer2Producer (where the iso is filled properly) and L1UpgradeTreeProducer (where the iso is always 0).
Jim and I are investigating the problem. We suspect it's related to the fact that taus can have several input tags.

**Comment by jimbrooke** [comment]
@davignon   I have pushed a fix.

@mulhearn this results from the change of tau InputTag to VInputTag 
https://github.com/cms-l1t-offline/cmssw/blob/l1t-calostage2-CMSSW_8_0_0_pre5/L1Trigger/L1TNtuples/python/l1UpgradeTree_cfi.py#L6

This wasn't propagated here
https://github.com/cms-l1t-offline/cmssw/blob/l1t-calostage2-CMSSW_8_0_0_pre5/L1Trigger/L1TNtuples/python/L1NtupleEMU_cff.py#L14

Because the parameter changed from tauToken to tauTokens, the module will read tau objects from the unpacker output, not the emulator.

**Comment by mulhearn** [comment]
Uggh, I am sorry I missed that addition config.  It seems we to include an EMU ntuple example in our list of standard checks to make.

**Comment by davignon** [comment]
@mulhearn @jimbrooke 
Just committed the new tau isolation LUTs to calostage2-CMSSW_8_0_0_pre5. I'm not sure of the procedure, but can we make this available in the dev-recipe branch so that the TSG can review?
Thanks.

**Comment by mulhearn** [comment]
Putting it in now...

**Comment by mulhearn** [comment]
@davignon @jimbrooke data files cannot go into CMSSW, they go in separate repo.  Its fine for us to put data files directly in our dev branches, but having different versions of the same named data file is I think a nightmare bound to happen...  I noticed these files have different versions:

```
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff70.txt
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff80.txt
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff90.txt
```

From what I put in the data-repo.  I'm leaving as is for now, but can you rename these _v2 or something and update your configs accordingly?

**Comment by mulhearn** [comment]
From your changes Feb 5 and onward, I've only included:
e496e25
d3af1d3
04dc8a1
in the dev recipes branch.  Should anything else be cherry-picked yet?

**Comment by davignon** [comment]
@mulhearn 
I agree with your concerns.

These files:
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff70.txt
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff80.txt
   L1Trigger/L1TCalorimeter/data/Flat_Tau_iso_LUT_eff90.txt
have been updated correctly inside the l1t-dev-recipe-CMSSW_8_0_0_pre6 branch (and the caloStage2 8_0_0_pre5 branch). I see the correct versions in both places. Next time around, when I update such files, I will create a versioning as you suggested.
These files do not appear by default in the config file.

What do you mean by data-repo? Can you please point me to it so that I check everything is OK?

**Comment by davignon** [comment]
Thanks for that.
On the tau side, this looks OK.

**Comment by mulhearn** [comment]
Our own fork of data repository for L1Trigger/L1TCalorimeter/data is here:
   https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter 
It won't yet contain any updates from our dev branches (under L1Trigger/L1TCalorimeter/data) since I only update the data repo in advance of making PRs into official CMSSW.  The framework seems to sensibly put anything locally at L1Trigger/L1TCalorimeter/data on top of what is already in the data repo...  But I don't know a nice way to navigate any of this.

**Comment by mulhearn** [comment]
@jimbrooke:  currently testing a rebased version of calostage2 dev branch onto latest version of dev recipe.  So far so good, but I want to run all the tests before handing it off.  Should be soon.

**Comment by mulhearn** [comment]
@jimbrooke:  the rebased version of calostage2 dev branch is here:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-CMSSW_8_0_0_pre6

I checked all your calo-stage-2 cms driver based workflows and they all ran... I explicitly checked the ntuple output of:

```
cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --conditions=auto:run2_data -n 200 --data --filein=/store/data/Run2015D/SingleMuon/RAW-RECO/MuTau-PromptReco-v4/000/260/627/00000/00C3E929-6D84-E511-AFDF-02163E0146A5.root
```

and it looked reasonable at the level of Et distributions for all unpacked / reco / re-Emulated objects.

Len's CMS driver based command also ran, as well as the old style flat python tests (but see note below).

This includes the bitwise calo layer1 emulation, but it is off by default.  You can turn it on in L1Trigger/L1TCalorimeter/python/simDigis_cff.py by changing these lines:

```
    # select one of the following two options:
    # - layer1 from L1Trigger/L1TCalorimeter package
    from L1Trigger.L1TCalorimeter.simCaloStage2Layer1Digis_cfi import simCaloStage2Layer1Digis
    # - layer1 from L1Trigger/L1TCaloLayer1 package
    #from L1Trigger.L1TCaloLayer1.simCaloStage2Layer1Digis_cfi import simCaloStage2Layer1Digis
```

I have only tested that this works for me in dev-recipe for one simulation and one re-emulation workflow, and not at all in your new dev-branch.

**Comment by mulhearn** [comment]
Requests:
- To reduce versioning, please consider retiring `customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw`
  for the full L1T re-Emulation in:
  `--customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW`
  if the latter is not found to be deficient for you.
- I found one regression in test:
  `cmsRun L1Trigger/L1TCommon/test/runL1T.py`
  which fails with

```
----- Begin Fatal Exception 12-Feb-2016 11:47:07 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'L1TPath'
   [2] Calling event method for module L1TStage2Layer1Producer/'simCaloStage2Layer1Digis'
Exception Message:
No "CaloTPGRecord" record found in the EventSetup for synchronization value
Run: 1 LuminosityBlock: 1 Event: 0 Time: 1
 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

probably this is missing something from your other workflows which I can find, but if you know the answer outright, please let me know to save me some time.  Obviously I'm not delaying handing this branch to you over this regression because I doubt you use this workflow...  I think will be worthwhile to have very limited number of tests that aren't cmsDriver based, even though it will mean some duplication, but just so we can decouple ourselves from cmsDriver in case of problems.

**Comment by mulhearn** [comment]
One important note:  you need to follow the recipe for dev-recipe #147 in building this branch, namely I am worried about `git cms-addpkg L1Trigger/L1TGlobal` until we fix the problem.  I could trivially fix this by adding a commit there, but that would complicate testing the actual fix (of lib dependencies) which hasn't happened yet....

**Comment by mulhearn** [comment]
(Updated first comment summary to better describe current state.)

**Comment by mulhearn** [comment]
One last question:  can I delete yet all other calostage2 stage2calo topic branches not mentioned in summary above?  Any other branch you want me to keep around longer for backup?

**Comment by jimbrooke** [comment]
The CaloTpgRecord is an HCAL ES object that the Layer 1 module requests to interpret the HCAL TP data.  Previously, the module was using an RCT ES object to do the same thing.  So L1Trigger/L1TCommon/test/runL1T.py is missing some ES setup that is standard in the cmsDriver jobs.

**Comment by jimbrooke** [comment]
Regarding the other questions, I'll alert the developers.  I cannot think of any branches we need to keep, but I'll ask the others.

**Comment by jimbrooke** [comment]
@apana asked about bugfixes for HT/MHT.  These are listed below.  They could be merged into the TSG branch, but we cannot guarantee yet that the HT/MHT is fully understood.

6495cf8be9bfec7452575aad63b8982ae4aea4e4
f8b5cd4bd9458c19eccd90868ef92653e46063d5
3e850dc647527f37c8d3e248d7a767efe069eebb
8ad47956fd3a2184377159cd5993bf287918b2ca
b6ee4cf67db3307f92ab2e512e0b65642623e02c

**Comment by jimbrooke** [comment]
@mulhearn I tried using customiseReEmul.L1TReEmulFromRAW in place of customise_Stage2Calo.Stage2CaloFromRaw but there are no forward jets.

The difference is due to lines 20-34 of customise_Stage2Calo.py
https://github.com/cms-l1t-offline/cmssw/blob/l1t-calostage2-CMSSW_8_0_0_pre6/L1Trigger/Configuration/python/customise_Stage2Calo.py#L20

Not sure if you want to add them to customiseReEmul or find another workaround.

**Comment by mulhearn** [comment]
Got it.  Just use your version for now and I'll push an update when I can...

-Mike

**Comment by jimbrooke** [comment]
@apana @mulhearn the fixes listed above for HT/MHT should be merged with the TSG branch.  We have checked the turn-ons and they look good.  I expect comparable performance to stage 1, although the scale may be a bit different.

**Comment by mulhearn** [comment]
Doing this now: we had an emergency situation with L1T/HLT interface that has just been resolved...

**Comment by jimbrooke** [comment]
@mulhearn here is the list of commits to enable HF 1x1 TPs.  Since this is a long list I am testing this set on top of l1t-dev-recipe-CMSSW_8_0_0_pre6, and will post here if successful....
92d5635bf9dec4a21b805400e6470e5c9c19f559
c673d9860634f84c7e4e6c0a48fa6171e07589fc
c673d9860634f84c7e4e6c0a48fa6171e07589fc
c673d9860634f84c7e4e6c0a48fa6171e07589fc
c4512d4e0d174d012cc321c4ba3e80aa676074f2
1994746683698e47bf415658294bdd7b1e1bb0cd
19cd81fa92b4f6cfbe45d404896fad967b125fa5
269d353b0d10f506cf6b696f254e7ed333dbbacc
d3449caa464124d4eaf8db000672d7a86f6d4be6
d2df29f20061e44a283abf3b8498d05171560c48
45527c8ad59b2249f34ab4044217599ed46e3d50
b430df3160ae37c021281659a30380984a649d4a

This one needs to be added to both dev recipe and l1t-calostage2-800p6 branches.
1d1fc404f5f3080214ce41568415b8fadbdf1138

**Comment by mulhearn** [comment]
Excellent.

**Comment by jimbrooke** [comment]
Actually, if there is a clever git way to merge _everything_ in the calo dev branch onto the dev recipe branch, this would achieve what we want for forward jets...

**Comment by jimbrooke** [comment]
Update the cmsDriver commands above to include HF 1x1 TPs
https://github.com/cms-l1t-offline/cmssw/issues/140#issuecomment-179258458

**Comment by mulhearn** [comment]
The only pending issue from this topic is merging in the HF 1x1s.  Thats covered now here:  #161.
Closing.
