### ISSUE TITLE
Debugging Cycle For 80x

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#145]
Here we will keep track of the debugging issues that emerge since our massive import of code into 80x.

The HLT/L1T interface development is a separate issue.

So far we have:
  1) warnings from L1TGlobal new enum's:
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc493/CMSSW_8_0_X_2016-02-06-2300/L1Trigger/L1TGlobal
  2) problems reported with relval 250407.0 due to config files for legacy technical triggers
  3) problems with many RCT warnings reported in relval:

```
%MSG-e L1T:  RctRawToDigi:rctDigis 15-Feb-2016 11:44:43 CET Run: 1 Event: 1012
Cannot unpack: empty/invalid L1T raw data (size = 0) for ID 1350. Returning empty collections!
%MSG
```

From step 3 in:

```
runTheMatrix.py -l 1306 -i all
```

Fixes are:
1) PR cms-sw#13296, but follow-up, outside of 80x, still needed to address what appears to be a logic problem. (Merged)
2) PR cms-sw#13297, but it seems SimL1EmulatorDM_cff.py will need a small update before any new Stage-2 workflows with data mixer will work. (Merged) 
3) PR cms-sw#13298 (Merged)

Additional bug fixes are:
4) PR cms-sw#13299 to fix crashes of OMTF at run transitions. (Merged)
5) cms-sw#13310 fixes offline DQM crashes reported by Martin. (Merged)
6) cms-sw#13311  actually does quiet (3) (Merged)

And a snuck in additional feature at:
7) cms-sw#13319 (Merged)

Remaining show-stoppers for 800:
8) An update for Layer-2 unpacker for change in FED is here:  cms-sw#13330 (Merged)
9) At David's request, Takashi is updating UTM library to include xsd directory in the external instead of the release (this is preferred over the env variable solution)
10) prescale config bug fix:  cms-sw#13329 (Merged)

These did not make 800 but will go into a patch release in time for MWGR:
11) cms-sw#13339 (Merged) - Mike's fix making calo packing of eta consistent with firmware/unpacking.
12) cms-sw#13340 (Passes Test, Fully Signed) - Vladimir's update to HLT seeds applying prescales and masks correctly.

Likewise for the remaining complaint from HLT:
- need to check on physical phi value in sums, and muon charge.

**Comment by mulhearn** [comment]
All problems reported so far from David are now addressed.

**Comment by mulhearn** [comment]
Actually I didn't check yet that (3) actually succeeds at quieting the warnings, only that it passes relvals, which it did before... need to check this.

**Comment by mulhearn** [comment]
Martin has found another problem with latest IB at which he commented on at cms-sw#13271, but not clear yet which work flow failed.

**Comment by mulhearn** [comment]
Fixes for Martin are here:  cms-sw#13310

**Comment by mulhearn** [comment]
So I misfired on the RCT errors... that payload is not emulated in MC (there isn't an RCT packer...) so its totally expected that it will be missing when trying to unpack RCT from MC.  I simply removed the warning when that FED isn't present in Raw data.  This is Stage-1, not worthwhile to do anything fancier, and this payload isn't used except for DQM.  This is in PR cms-sw#13311.

**Comment by mulhearn** [comment]
That clears (again) the reported bug list for 80x....  let's see what else trickles in.

**Comment by mulhearn** [comment]
I think the L1TGlobal package issue is only current show-stopper for 800.  Easy to tweak this problem in latest IB:

```
git cms-init
git cms-addpkg L1Trigger/L1TCommon
scram b -j 8
cmsRun L1Trigger/L1TCommon/test/runL1T.py
```

but miraculously fixed by:

```
git cms-addpkg L1Trigger/L1TGlobal
scram b -j 8
cmsRun L1Trigger/L1TCommon/test/runL1T.py
```

**Comment by mulhearn** [comment]
And David figures it out,,.  I was looking for weird library problems, but the recompile isn't even needed.   So it must just be an illegally opened file that assumes it is in the local path.

**Comment by mulhearn** [comment]
Oh crap... what if it is in utm library??!!

**Comment by blwiner** [comment]
Mike,

   Do you have a little more detail on this?  What file?

-Brian

On Wed, Feb 17, 2016 at 7:39 AM, mulhearn notifications@github.com wrote:

> And David figures it out,,. I was looking for weird library problems, but
> the recompile isn't even needed. So it must just be an illegally opened
> file that assumes it is in the local path.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/145#issuecomment-185181615
> .

## 

# 

| Prof. Brian L. Winer |
| --- |

```
              Department of Physics
           The Ohio State University
             191 W. Woodruff Ave
              Columbus, OH 43210

               (614) 292-8996 (Office)
               (614) 292-7370 (Lab)
```

#

**Comment by tmatsush** [comment]
Just had a chat with Mike.
The problem could be solved by setting UTM_XSD_DIR environment variable to .../xsd-type

**Comment by mulhearn** [comment]
Discussed schedule with David...

Next IB will be built at 10:00 pm, by then:
- New UTM library should be included, I should test following Takashi instructions.
- PR from Jim is promised to address unpacker FED change
- PR from me is promised to address physical values in Muon/EtSum classes
- I should provide list of unit tests to David for testing (e.g. runL1T, runHLT, ...)

In morning we will see if tonights IB will become 800.

**Comment by mulhearn** [comment]
An interesting evening sorting the problems when configuring L1TGlobal from the release...  It was a dreaded AND of two problems, emerging only when all our code was in release and we stopped having L1TGlobal compiled locally.

Takashi has sorted out the UTM library with a second update, and I meanwhile worked out this one letter bug fix:  https://github.com/cms-sw/cmssw/pull/13329

**Comment by mulhearn** [comment]
Last minute FED change from Jim has PR now too.  That is it for the show-stoppers.

**Comment by mulhearn** [comment]
All of our PRs are merged.
