### ISSUE TITLE
L1T TSG integration branch for CMSSW_8_0_0_pre6

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#147]
This issue tracks the TSG integration branch ("dev-recipe") based on CMSSW_8_0_0_pre6:
  https://github.com/cms-l1t-offline/cmssw/tree/l1t-dev-recipe-CMSSW_8_0_0_pre6
For stability, the TSG integration branch lags the L1T integration branch, which is tracked here:
  https://github.com/cms-l1t-offline/cmssw/issues/164
Only code in this TSG branch, with a l1t-tsg-X tag, is intended for widespread consumption.

For various work-flows related using the latest TSG tag, see the Twiki here:
  https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions

WARNING: the following is currently untested due to problems with cmsrel command on lxplus... it will be tested as soon as cmsrel becomes available!

The recipe for the latest stable tag is:

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic cms-l1t-offline:l1t-tsg-v3
git cms-addpkg L1Trigger/L1TCommon
scram b -j 8
```

To instead take our latest and greatest:

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-merge-topic cms-l1t-offline:l1t-dev-recipe-CMSSW_8_0_0_pre6
git cms-addpkg L1Trigger/L1TCommon
scram b -j 8
cmsRun L1Trigger/L1TCommon/test/reEmul.py
```

The latest control plots from a short run over 10k zero-bias events are here:
http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v7.0/

The list of recent tags, along with the hash of most recent commit from relevant dev branches is:
- l1t-tsg-v3 this syncs with l1t-integration-v7.0 which includes:
  - updates the Stage-2 calo emulator to use 1x1 HF TPs.
  - calo parameter improvements for HT sum
  - muon improvements for GMT cancel-out based on quality.
  - muon bugfix for Eta and FW version 2 which improves rate in BMTF.
  - does not include recent EMTF quality updates, so these still corrected by MuonQualityAdjuster
  - deprecation of non cmsDriver and duplicate re-Emulation workflows.
- l1t-tsg-v2-patch1 technical bug fixes for OMTF at run boundaries, and to include L1TGlobal package as work-around
- l1t-tsg-v2  calo: partial commits up to b6ee4cf   (fixes for HT and MHT, but needs validation. No 1x1 HF TPs yet)
- l1t-tsg-v1 muon: 8d55eab (entire) calo: 9789e7c ntuple: 96e7b99 (entire)
- l1t-tsg-v0  = calo: 04dc8a1b muon: 3d4ac92

**Comment by mulhearn** [comment]
Not sure why the 

```
git cms-addpkg L1Trigger/L1TGlobal
```

is needed.  I checked out the package to investigate a crash in L1TGlobal, and the crash went away.  It is reproducible.

**Comment by mulhearn** [comment]
Now working on bringing this fully up-to date with previous dev-recipes branch...  (DONE)

**Comment by mulhearn** [comment]
Now fully update to date with previous dev-recipes branch, at commit d4b256ea8bca8c6295e43541c8f79434ab0e6a61.  Previous dev-recipes branch will now be retired.

**Comment by mulhearn** [comment]
Now cherry-picking from development branches the following:
  e496e25 (Was actually already in...sorry...done)
  1fc3e0e (done)

**Comment by mulhearn** [comment]
Now merging in Layer-1... (DONE)

**Comment by mulhearn** [comment]
Developers, if you are wondering where your data files went, check e.g.:
   $CMSSW_DATA_PATH/data-L1Trigger-L1TCalorimeter/
I'll ask if there is an easier way to access this... but note that you continue to reference these as if still in the release at e.g. L1Trigger/L1TCalorimeter/data

**Comment by fwyzard** [comment]
@mulhearn , I'm trying to understand what is available in 800pre6, what is available here, what is available from the developers but not yet integrated here, and what else we can expect Soon™.

From the TSG point of view, I think that on the short term the highest priority items are
- [x] update the "dev" recipe based on CMSSW_8_0_0_pre6
- [x] integrate the L1 uGT seed module for HLT (https://github.com/cms-sw/cmssw/pull/13166 - merged)
- [x] integrate the EG and Tau LUTs corresponding to the plots presented today
- [x] integrate the fix for HTT to use calibrated jets (expected by the end of the week)
- [ ] integrate the new jet calibrations including HF (expected by the end of the week)

**Comment by mulhearn** [comment]
The bitwise emulation of CaloLayer1 is now included, but off by default:

```
# select one of the following two options:
# - layer1 from L1Trigger/L1TCalorimeter package
from L1Trigger.L1TCalorimeter.simCaloStage2Layer1Digis_cfi import simCaloStage2Layer1Digis
# - layer1 from L1Trigger/L1TCaloLayer1 package
#from L1Trigger.L1TCaloLayer1.simCaloStage2Layer1Digis_cfi import simCaloStage2Layer1Digis
```

it seems to be working for MC but not for re-Emulation from RAW.  Will follow up with Layer-1 experts.

**Comment by mulhearn** [comment]
@jimbrooke can you confirm for me and @fwyzard that my recent inclusion of:
e496e25
d3af1d37
04dc8a1b
brings us up to date with the plots shown today?

**Comment by fwyzard** [comment]
@mulhearn , according to what @davignon and @tstreble told Simone via email, I think you are up to date.
- this is in e496e2587608a07dc757786cf80f98646913bfc3:
  On 9 February 2016 at 13:41, thomas strebler thomas.strebler@llr.in2p3.fr wrote:
  
  > `caloStage2Params.egIsoLUTFile               = cms.FileInPath("L1Trigger/L1TCalorimeter/data/IsoIdentification_0.5_adapt_v16.02.01.txt")`
  > 
  > This corresponds indeed to the best EG configuration available.
- this should be in 04dc8a1b0c54a5cbde1063d75a06158d0febc979:

**Comment by mulhearn** [comment]
This is posted above in summary, but repeating here for questions:

I am proposing the following scheme for tags:
- I periodically tag the dev recipe branch, e.g. "l1t-tsg-v0".
- for each tag, I record the hash of the most recent commit included in dev-recipes from the calo and muon development branches, and anything else appropriate. As in example above.
- when speakers present talks, they should always note the hash of the most recent relevant commit in their own development branch at the time the plots were made. (Note: they do not need to wait for a tag!)
- In this way, its not too difficult to discern which tag is needed to be up to date with a particular presented plot.

**Comment by mulhearn** [comment]
@fwyzard I guess I was planning to keep the HLT integration somewhat orthogonal to this.  I don't believe we need our latest and greatest emulators for that work, or do I misunderstand something?  The problem is HLT reco brings in a bunch of dependent packages... and also we'll be updating things here that I don't want to put in release immediately.  OK from you end if these are separate?

**Comment by jimbrooke** [comment]
"@jimbrooke can you confirm"  - sorry, but I have no more information than anyone else about this.

**Comment by fwyzard** [comment]
@mulhearn - sure, we do not need the HLT integration here.
I listed because it is among the important topics, it's fine to have it in its own branch.

**Comment by mulhearn** [comment]
The latest update, which is tagged l1t-tsg-v1, merges completely (and so retires) the muon dev branch and Len's ntuple dev branch.  It also includes the bitwise emulation of Stage-2 Layer-1 emulation (but it is not on by default yet).  It also includes Len and Jim's latest set of updates for the cmsDriver based ntuple production.

**Comment by apana** [comment]
Hi Mike,

I tried setting up a new project area using the new l1t-tsg-v1 tag, but failed in the initial 
git cms-merge-topic cms-l1t-offline:l1t-tsg-v1  step. 
It crashed with message:
error: no such remote ref 26009a63cb61fa292f650cb4763ccd7d5e94aadc

**Comment by mulhearn** [comment]
Hmmmmm.  I'll investigate.  For now just use recipe for latest and greatest...

**Comment by mulhearn** [comment]
This is probably useless info at this point, so recording here and deleting from the summary above:

The retired muon development branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-pass2-CMSSW_8_0_0_pre5
is entirely synced (dddb4a765d45328fb3ae99f94a7f215db09b8283) No more commits should be made to this branch.

The retired calo stage-2 development branch is now in 80x to make use of 1x1 TPs currently in 80x only. Therefore, only a subset of commits in this (obsolete) branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-pass2-CMSSW_8_0_0_pre4
are actually be included in the recipe, and they are listed here:
everything up until 6d65a08 plus
a6d96ce, 4c60b2c, d043d2a, b2e40ce, a629dda,

Work continued  on the retired Calo Stage 2 development branch
https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-CMSSW_8_0_0_pre5
from which we've taken:
e496e25, d3af1d37, 04dc8a1b, 8b948b9, ab1a7f7, 7164084, 2dd1043, 6cd6362, 9789e7c

**Comment by fwyzard** [comment]
> I tried setting up a new project area using the new l1t-tsg-v1 tag, but failed in the initial
> `git cms-merge-topic cms-l1t-offline:l1t-tsg-v1` step.
> It crashed with message:
> error: no such remote ref 26009a6

I think that is a limitation of `git cms-merge-topic` , I'll see if I can fix it.

**Comment by apana** [comment]
Hi Andrea,

Can you try git fetch cms-l1t-offline  and see if that fixed the problem?

-Len

**Comment by mulhearn** [comment]
(I guess he's looking for a better fix than having to fetch the entire repo locally...)

**Comment by apana** [comment]
BTW, I think this branch is already obsolete.  Namely it's missing the
mHT/HT fix that's just been put in the dev-recipe branch. Maybe you want to
try running with that?

-Len

**Comment by fwyzard** [comment]
Actually I'd rather see the HTT/MHT updates propagated here, since this is the "official" recipe.

**Comment by apana** [comment]
Right.  There will be another tag that would then become the "new" official
recipe. I just wanted to let you know there were some updates since the tag
was released and if you wanted to try it.

-Len

**Comment by mulhearn** [comment]
Sorry, indeed, only updated in summary.  v2 is out which includes the mHT/HT fix.

**Comment by fwyzard** [comment]
Sigh, I have to give up on `git cms-merge-topic` for the moment. I know where the problem is, and it should be able to support tags as well as branches, but git is not helping :-(

I confirm that doing

```
git add remote cms-l1t-offline https://github.com/cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
```

is a valid workaround.

**Comment by thomreis** [comment]
If I use the workaround for the tag like below I get an error saying that the newly checked out release is not a git repository.

Recipe:

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
```

Leads to:

```
fatal: Not a git repository (or any parent up to mount point /afs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I did the 
`git cms-addpkg L1Trigger/L1TCommon`
before
`git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git`
to work around this.

**Comment by fwyzard** [comment]
Hi Thomas,
you can do

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
...
```

.A

**Comment by gennai** [comment]
Hi,
Could you specify which fix it is? The one concerning the use of corrected jets for the htt?

Best,
S.

**Comment by fwyzard** [comment]
@thomreis , you can do

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic cms-l1t-offline:l1t-tsg-v1
```

**Comment by mulhearn** [comment]
(Updated prescription for specific tag.)

**Comment by mulhearn** [comment]
Discussed schedule with David...

Next IB will be built at 10:00 pm, by then:
 - New UTM library should be included, I should test following Takashi instructions.
 - PR from Jim is promised to address unpacker FED change
 - PR from me is promised to address physical values in Muon/EtSum classes
 - I should provide list of unit tests to David for testing (e.g. runL1T, runHLT, ...)
In morning we will see if tonights IB will become 800.

**Comment by mulhearn** [comment]
(Message to wrong thread deleted)

**Comment by mulhearn** [comment]
Updated recipe to set env variable instead of adding L1TGlobal package.  This will go away entirely once 800 is out.  But it occurs to me maybe people prefer to just checkout the package instead of remembering the env variable, so putting both in recipe...

**Comment by mulhearn** [comment]
The latest stable tag is now l1t-tsg-v2-patch1 which is simply v2 plus technical bug fixes (for crash avoidance).

**Comment by mulhearn** [comment]
This is dated information in the summary, recording here before deleting:
The muon development branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-CMSSW_8_0_0_pre6
is synced up to 26009a63cb61fa292f650cb4763ccd7d5e94aadc.

The calo stage-2 development branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-calostage2-CMSSW_8_0_0_pre6
is synced up to 26009a63cb61fa292f650cb4763ccd7d5e94aadc plus 
6495cf8, f8b5cd4, 3e850dc647527f37c8d3e248d7a767efe069eebb,
8ad4795, b6ee4cf,

The global dev branch:
   https://github.com/cms-l1t-offline/cmssw/commits/l1t-global-CMSSW_8_0_0_pre5
is synced up db8953de8f599c7031b0ac6856ed843b4c079699

**Comment by mulhearn** [comment]
This branch is now deprecated.  The L1T TSG branch has moved to CMSSW 8_0_2 as documented at new issue #191.
