### ISSUE TITLE
Re-emulation for Stage 2

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#150]
@apana @mulhearn 
I think the customisation for re-emulation of stage 2 is missing HCAL TPs.  Right ?  We need to include this for consistency with results presented so far, and certainly when we include HF 1x1 TPs.
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre6/L1Trigger/Configuration/python/customiseReEmul.py

**Comment by mulhearn** [comment]
OK, will update.  I actually reverted this to better coincide with the Stage-2 calo customization...  anyway, both modes were to be supported but easiest is to make re-emulating the default for now.

**Comment by jimbrooke** [comment]
Stage 2 calo customisation does include HCAL TPs
https://github.com/cms-l1t-offline/cmssw/blob/l1t-calostage2-CMSSW_8_0_0_pre5/L1Trigger/Configuration/python/customise_Stage2Calo.py

**Comment by mulhearn** [comment]
Sorry... misremembered.  It was the TSG work flows I was emulating.  Anyway, I will update.

**Comment by mulhearn** [comment]
Its fixed:  https://github.com/cms-l1t-offline/cmssw/commit/e95c1ebe596224134ca2b2615b43e37aed3ca768

**Comment by mulhearn** [comment]
This one is closed.

**Comment by apana** [comment]
Hi Mike,

Not quite.  I think in Configuration/python/customiseReEmul.py you need to
comment out the line

process.simCaloStage2Layer1Digis.hcalToken = cms.InputTag("hcalDigis")

I also see the problem in Configuration/python/customise_Stage2Calo.py, but
I'm not sure if this customisation file is used by anyone anymore.

-Len

**Comment by mulhearn** [comment]
Ah, right.  I see now why the confusion.  In Jim's dev branch (which includes stuff for 1x1 HF TPs he hasn't released to dev-recipe yet) he re-Emulates HCAL TPs.  But in the dev-recipes branch there's no TP re-Emulation because these updates haven't been merged yet.

**Comment by mulhearn** [comment]
I've made the fix but lxplus seems to be down now so I can't test and push yet..

**Comment by mulhearn** [comment]
OK, now should be fixed.  Ignoring "Configuration/python/customise_Stage2Calo.py" since that will just add conflict when the calo dev branch is merged back in.
