### ISSUE TITLE
Problem with packing Regional Muon Candidates in since pre6

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#151]
Since pre6, maybe longer, there is a problem with packing the Regional Muon Candidates during the DigiToRaw step.  To get standard sequences working for now, I've disabled this part of the packer in commit df5994975faefd697694d61b59eb6781cc041063.  To reproduce the problem, follow the standard recipe for dev recipes at issue #147, revert that changes from that commit, and run the test program:

```
cmsRun L1Trigger/L1TCommon/test/runStandardSequences.py
```

Please push to your own branch and notify me when fixed.

**Comment by mulhearn** [comment]
@thomreis @jlingema can you have a look at this one?

**Comment by thomreis** [comment]
There are in fact two bugs. One of them leading to the exception.
It seems that the track address map for the EMTF muons is not filled correctly.

**Comment by thomreis** [comment]
@mulhearn should the uGMT packer not use the collections that were produced by the uGMT emulator as inputs? Also for the TF muons it packs? In the configuration of the module [1] the output muons of the TF are used as input for the packer. I believe the input should always be simGmtStage2Digis.
The reason for the exception is most likely that the EMTF emulator has not yet implemented the new EMTF track address scheme. For sure it is not in this version of CMSSW since I made the PR for the data format just before midnight on the last open day. @mrcarver could confirm this.

I can put a protection with an error message telling to check the data format in the code.

[1]
process.gmtStage2Raw = cms.EDProducer("L1TDigiToRaw",
    BMTFInputLabel = cms.InputTag("simBmtfDigis","BMTF"),
    EMTFInputLabel = cms.InputTag("simEmtfDigis","EMTF"),
    FWId = cms.uint32(1),
    FedId = cms.int32(1402),
    InputLabel = cms.InputTag("simGmtStage2Digis"),
    OMTFInputLabel = cms.InputTag("simOmtfDigis","OMTF"),
    Setup = cms.string('stage2::GMTSetup'),
    lenSlinkHeader = cms.untracked.int32(8),
    lenSlinkTrailer = cms.untracked.int32(8)
)

**Comment by thomreis** [comment]
Ah no that was wrong. The uGMT does not produce these collections. Only the uGMT unpacker produces them.

**Comment by thomreis** [comment]
So the only thing to do then is to include a dummy track address until the EMTF emulator has implemented the new scheme.

**Comment by thomreis** [comment]
d208c83409af227e856421455774e757bb0c6532 contains a protection against the exception that was observed. There is a change to the RegionalMuonCand data format header but it affects only the enums in there and not what is written in an edm file. So I guess that change is fine.

b3d3a628e3284bb84b0b4cbb428c5606e3523783 fixes a problem that empty muons were only filled in the first BX if no muon was found in the present BX.

@mulhearn you can go ahead and pick these two.

**Comment by mulhearn** [comment]
@thomreis, Excellent, Thanks for the quick fix, will pick these today...

**Comment by mulhearn** [comment]
@abrinke1 @bmichlin it seems like maybe the series of commits you have after 3d4ac926e29decc79a223903bf546742dad0b61e in https://github.com/cms-l1t-offline/cmssw/commits/l1t-muon-pass2-CMSSW_8_0_0_pre5 should fix the problem as well?  Are these ready to go into dev-recipe  branch?

**Comment by abrinke1** [comment]
@mulhearn https://github.com/mulhearn With the commits I made, the EMTF
unpacker now outputs a RegionalMuonCandBxCollection (with the BX
artificially set to 0 for now.)  However, we do not yet have any packing,
so if that's the problem, my latest commits won't fix it.

As regards the dev-recipe, I would be happy for my commits to go in there -
it would be a great help for MWGR 2.  I pulled the latest
l1t-muon-pass2-CMSSW_8_0_0_pre5 version and clean-compiled before
committing, so it should all work.

Cheers,
Andrew

**Comment by mulhearn** [comment]
Note that dev-recipe is our development branch on top of what is already in CMSSW.  So being in dev-recipe does not automatically imply it will make it for MWGR.  However, I will try to sync things one last time before Monday...

**Comment by mulhearn** [comment]
@abrinke1 can you move your update of "hwToLogicLayer.xml" into "hwToLogicLayer_v2.xml" and update your code to use _v2 of xml instead?  This is explained in just posted hypernews thread here:

   https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerSW/578.html

**Comment by akalinow** [comment]
@mulhearn which changes to hwToLogicLayer.xml you mean? This file is a config file for OMTF, not EMTF.

**Comment by abrinke1** [comment]
@mulhearn I don't think I changed that file.  The history indicates the
only changes were by @akalinow 10 days ago:
https://github.com/cms-l1t-offline/cmssw/commits/l1t-muon-pass2-CMSSW_8_0_0_pre5/L1Trigger/L1TMuon/data/omtf_config

On Thu, Feb 11, 2016 at 10:43 AM, Artur Kalinowski <notifications@github.com

**Comment by mulhearn** [comment]
Sorry, yes, my bad... its this commit 694c341271ed335c41c5d6b113901b6c338844ed.  @akalinow can you change this file to _v2.xml and update your configs to use _v2.xml?

@mulhearn: I have made an update with commit 8d55eabaf1e4448b964f4a0353d345352b0f5063

**Comment by mulhearn** [comment]
@abrinke1 @bmichlin @thomreis it seems when I rebase the muon dev branch onto the dev-recipe branch, the Gt unpacker crashes...   Can you checkout this branch:
   https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-CMSSW_8_0_0_pre6
and debug the errors when running:

```
cmsRun L1Trigger/L1TCommon/test/runStandardSequences.py 
cmsRun L1Trigger/L1TCommon/test/reEmul.py
```

I'm adding @blwiner and @puigh since this is their unpacker, but there code runs as is in dev-recipe (I'll confirm this) so it must be something muon folks introduced.  This branch (when working) should become the new muon development branch, and these tests should always be run before pushing any updates.

**Comment by mulhearn** [comment]
(Note for motivation that the EMTF updates wanted for MWGR won't be able to go in until this is fixed!)

**Comment by mulhearn** [comment]
Misfire!  This is crashing in dev-recipes too...  please hold for now.

**Comment by akalinow** [comment]
I have renamed the new XML OMTF config files with commit 8d55eabaf1e4448b964f4a0353d345352b0f5063

**Comment by mulhearn** [comment]
Exactly.  Thanks!

**Comment by mulhearn** [comment]
This is so weird... I always check the main programs before committing anything to dev-recipe branch, which is why I confidently blamed you folks, but now I am getting these crashes even I revert back to an earlier tag.  Something very weird is happening.

**Comment by thomreis** [comment]
We saw crashes of the uGT when the uGMT was sending muons in BX outside of -2 to +2. This was fixed however in the uGT and also the uGMT has now a window of 5 BX configured from the ES.

**Comment by mulhearn** [comment]
So weird... now getting this crash on code that is many days old running straight out of box.

**Comment by mulhearn** [comment]
Uggghhh.  I think I forgot to follow my own $%^&ing recipe.  Need to manual checkout L1TGlobal for some weird reason.

**Comment by mulhearn** [comment]
Yeah, that was it.  Your code is fine.  Thanks all, this one is closed.
