### ISSUE TITLE
Change to ntuples in calo dev branch

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#155]
@apana @mulhearn I generated some ntuples for jet studies in the 800pre6 calo dev branch and I noticed that the config has been changed since last time I ran jobs
https://github.com/cms-l1t-offline/cmssw/commits/l1t-calostage2-CMSSW_8_0_0_pre6/L1Trigger/L1TNtuples/python

I know Len was planning some changes for the TSG branch, but I thought these changes might be discussed in advance.  (Y'know, because we are already users of this code ?)  Or at least we would get to discuss them at some point, before branches are merged and they're imposed upon us.  Now I am left staring at some plots in the middle of the night, with absolutely no idea whether they are comparable or not...

Can you help me out by telling me what version of offline JEC is now applied in our jobs?

**Comment by jimbrooke** [comment]
And then tell me whether any of the other commits have any impact on our analysis.

**Comment by jimbrooke** [comment]
OK, I _think_ run2_data auto GT in 800p6 gives us offline JEC V6, same as the file...  But I am not sure.

Len, please can you confirm ?

**Comment by apana** [comment]
Hi Jim,

Yes, I can confirm this gives the same corrections. In pre6, auto:run2_data
points to 80X_dataRun2_v4 which points to the same JEC payloads
as Summer15_25nsV6_DATA.db.  I also ran with both and got the same results.

-Len

**Comment by jimbrooke** [comment]
Thanks Len.  @raggleton and I both repeated that test, because we didn't know what was going on...
