### ISSUE TITLE
L1T Private Integration Branch and PR-based Development Work Flow.

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#164]
**NOTE:  This branch, based on CMSSW_8_0_0_pre6 is now obsolete... integration will continue under 8_0_2 at issue #189**

Integration of continuing L1T developments will be made on our private L1T integration branch at:

https://github.com/cms-l1t-offline/cmssw/tree/l1t-integration-CMSSW_8_0_0_pre6

Only mulhearn should merge or push to this branch, however, developers are encouraged to make PRs to this branch when their effort has matured.

The TSG integration branch is simply a lagging version of this branch.  Only changes first integrated, and tested here, will be merged onto dev recipes and given a "l1t-tsg-vX" type tag.

To check out a defined working tag:

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic cms-l1t-offline:l1t-integration-v7.0
git cms-addpkg L1Trigger/L1TCommon
scram b -j 8
```

to run the officially supported cmsDriver-based version of L1T Re-Emulation:
`cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 200 --data --no_exec --no_output --filein=/store/data/Run2015D/DoubleEG/RAW-RECO/ZElectron-PromptReco-v4/000/260/627/00000/12455212-1E85-E511-8913-02163E014472.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`
and then:

```
cmsRun l1NtupleRECO_RAW2DIGI.py
root -x L1Trigger/L1TCommon/macros/rates.C
root -x L1Trigger/L1TCommon/macros/kin.C
```

Note to former users of `reEmul.py`:  that example config file has been deprecated in favor of the far more versatile cmsDriver sequence above.  Note that the location of the re-emulated tree has changed, see rate.C and kin.C macros for example of how to access the data in `L1Ntuple.root`.

Also note that to run over RAW only, droping reco, one simply omits AOD from the ntuple customization file name:
`--customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODEMU`
is replaced by:
`--customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU`

Most recent integrations tags are:
- l1t-integration-v10: bitwise layer-1 off by default 
-  l1t-integration-v10-layer1:  layer-1 bug fix for asymmetry, bitwise layer-1 on by default
-  l1t-integration-v9.5 EMTF bx fixes
  - l1t-integration-v9.1 minor update to muon ntuple code
  - l1t-integration-v9.0 revert to stand-in layer1 to preserve consistency of current calibrations
  - l1t-integration-v9.0-layer1  extend calo data formats, speedup layer-1,improve integrations test,bugfix GT unpacker crashes
  - l1t-integration-v8.0 bugfix for layer1-calo, l1t integration tests, include legacy tech triggers to prevent some CMSSW standard sequence crashes
  - l1t-integration-v7.0 BMTF eta fix, plus switch to BMTF FW version 2.
  - l1t-integration-v6.1 layer1 bugfix for HF 1x1 TPs, no effect since this module is off by default.
  - l1t-integration-v6.0 add calo parameter updates for improved HT sum performance
  - l1t-integration-v5.0: muon dev branch up to 79e370fd5faa04b542f5b44f2674df2ef000ca8b plus cherry-pick d066c7bc54d6f9f57294ec5ae42adcb7ffa8677a these updates from thomreis improve muon quality and cancel-out treatment
  - l1t-integration-v4.1: deprecate customise_Stage2Calo.py
  - l1t-integration-v4.0: layer1 dev branch up to d84459e69fe955fea755c2b39ada03ecb843d4ef, which adds non-unity HF LUTS for Layer1, but no effect to standard sequence since stand-in Layer-1 emulator is still default.
  - l1t-integration-v3.1: cleanup/unify the various re-emulation customizations, and deprecate reEmul.py
  - l1t-integration-v2:  merge muon dev branch at 737703aaec5170445092f4a0b7402cd72a952165
  - l1t-integration-v1:  merge calo dev branch at 3bf1b931b88a9c8ad8417e9a8546e8e676880cb7 which includes HF 1x1 TP re-emulation capability.

The control plots from a short 10k run of l1t-integration-v9.2 are here:
http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v9.2/

THE REMAINING STEPS ARE UNDER DEVELOPMENT.... COMMANDS NOT YET TESTED:

Now that most development branches have been integrated, the recommended workflows for continuing L1T development is moving to a model based on making PRs to this integration branch.  

The process includes:
- compiling the most recent integration tag, as above, or simply the latest and greatest from this branch: 

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git cms-merge-topic cms-l1t-offline:l1t-integration-CMSSW_8_0_0_pre6
scram b -j 8
```
- pick a local branch name for your to work.  This doesn't really matter, no one but you will ever see this local branch name.  In the examples below we assume you've done:

```
git checkout -b mydevel
```
- work, commit, work, commit, as usual

```
# work work work
git add <files>
git commit -m "work work work"
# repeating as needed...
```
- and push to either (1) your own private branch:

```
git push my-cmssw mydevel:my-private-work-work-work-branch-$CMSSW_VERISON  
```
- or (2) a collaborative branch on cms-l1t-offline, in case several people are going to work on the same issue:

```
git push cms-l1t-offline mydevel:our-shared-work-work-work-branch-$CMSSW_VERISON  
```
- I recommend we keep the explicit CMSSW version in branch names, especially when several people are involved, to avoid the most common pitfalls of CMSSW+git.
- If you ever need to re-start your work in a fresh area or bring in a new team member, they simply follow the recipe above but use your common development branch at cms-merge-topic stage:

```
 git cms-merge-topic cms-l1t-offline:our-shared-work-work-work-branch-$CMSSW_VERISON
```
- If you simply need to merge in updates from other collaborators you would do:

```
git pull cms-l1t-offline our-shared-work-work-work-branch-$CMSSW_VERISON
```
- When your fix or new feature is ready, find your branch on github, ... TO BE CONTINUED...

**Comment by mulhearn** [comment]
Matt Carver alerts me to:
- https://github.com/cms-l1t-offline/cmssw/pull/159

**Comment by mulhearn** [comment]
And Giannis:
  https://github.com/gflouris/cmssw/commit/357c9a09a18104e1cf1f46e21491efcd424f2a9c

**Comment by gflouris** [comment]
@mulhearn Pull request #158 includes this commit https://github.com/gflouris/cmssw/commit/357c9a09a18104e1cf1f46e21491efcd424f2a9c

**Comment by mulhearn** [comment]
Thanks!

**Comment by mulhearn** [comment]
@apana tag l1t-integration-v1 merges latest version of calo dev branch, which includes HF 1x1 TPs.  All my test pass so far.  Please check yourself that you see results consistent with calo dev branch.  (There's only very minor differences after merge so no problem expected)

**Comment by mulhearn** [comment]
Now working on tag l1t-integration-v2 which will include latest and greatest from muons...

**Comment by mulhearn** [comment]
Tag l1t-integration-v2 is ready.

**Comment by mulhearn** [comment]
Now working on collapsing the various versions of L1T re-Emulation.

**Comment by mulhearn** [comment]
Tag l1t-integration-v3.0 is ready for initial testing by @apana and @jimbrooke.  

Len, you can turn on off the HF 1x1 TPs by including (or not) in your cmsDriver.py command the arguments:
`--geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`

Jim, can you please test that the arguments:
`--customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`
are a drop-in, fully functional replacement for your (to be deprecated) customization:
`--customise=L1Trigger/Configuration/customise_Stage2Calo.Stage2CaloFromRaw --geometry=Extended2016,Extended2016Reco`
I've checked myself that I get the same jet eta output but I'd appreciate your check.

**Comment by mulhearn** [comment]
I believe we are ready to retire "reEmul.py" and "L1Trigger/Configuration/python/L1TReEmulateFromRAW_cff.py", I have perfect bitwise agreement when I compare output of new sequence (also being tested by Len) above to "reEmul.py": 

```
SUCCESS:  bitwise equality for variable jetEt
SUCCESS:  bitwise equality for variable jetEta
SUCCESS:  bitwise equality for variable jetPhi
SUCCESS:  bitwise equality for variable tauEt
SUCCESS:  bitwise equality for variable tauEta
SUCCESS:  bitwise equality for variable tauPhi
SUCCESS:  bitwise equality for variable egEt
SUCCESS:  bitwise equality for variable egEta
SUCCESS:  bitwise equality for variable egPhi
SUCCESS:  bitwise equality for variable muonEt
SUCCESS:  bitwise equality for variable muonEta
SUCCESS:  bitwise equality for variable muonPhi
SUCCESS:  bitwise equality for variable sumEt[0]
SUCCESS:  bitwise equality for variable sumEt[1]
SUCCESS:  bitwise equality for variable sumEt[2]
SUCCESS:  bitwise equality for variable sumEt[3]
```

When I use different number of input events for one sample, all comparisons fail, as sanity check.

**Comment by mulhearn** [comment]
Ah, very nice, we can deprecate "def Stage2CaloFromRaw" as well:

```
SUCCESS:  bitwise equality for variable jetEt
SUCCESS:  bitwise equality for variable jetEta
SUCCESS:  bitwise equality for variable jetPhi
SUCCESS:  bitwise equality for variable tauEt
SUCCESS:  bitwise equality for variable tauEta
SUCCESS:  bitwise equality for variable tauPhi
SUCCESS:  bitwise equality for variable egEt
SUCCESS:  bitwise equality for variable egEta
SUCCESS:  bitwise equality for variable egPhi
FAILURE:  variable muonEt shows a disagreement
FAILURE:  variable muonEta shows a disagreement
FAILURE:  variable muonPhi shows a disagreement
SUCCESS:  bitwise equality for variable sumEt[0]
SUCCESS:  bitwise equality for variable sumEt[1]
SUCCESS:  bitwise equality for variable sumEt[2]
SUCCESS:  bitwise equality for variable sumEt[3]
```

I notice there is also "Stage2CaloFromRaw_HWConfig(process):" which we'll need to support, but I think this should be a small perturbation of the main customization (instead of a full copy).

**Comment by mulhearn** [comment]
Note that the muon disagreements are to be expected, since the Stage-2 calo re-Emulate work flow doesn't include GMT and GT.  @jimbrooke:  I can add a utility customization to drop GMT and GT emulation from the sequence if you like (I didn't notice a speed difference, but might be noticed for larger jobs...)

**Comment by mulhearn** [comment]
I've added two more customizations to fully reproduce functionality in CaloStage2 workflows using the new sequences:
`--customise=L1Trigger/Configuration/customiseReEmul.L1TCaloStage2ParamsForHW` 
`--customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffGtAndGmtEmulation`
The first overrides the CaloParams to use the "HW" settings.  The second turns off Gt and GMT re-Emulation, so CaloStage2 emulation can fun at full speed.

**Comment by mulhearn** [comment]
The will be available in tag 3.1, after some more cleanup.

**Comment by mulhearn** [comment]
At tag l1t-integration-v3.1, reEmul.py has been removed, with related configs, in favor of the cmsDriver based configuration:

`cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 200 --data --no_exec --no_output --filein=/store/data/Run2015D/DoubleEG/RAW-RECO/ZElectron-PromptReco-v4/000/260/627/00000/12455212-1E85-E511-8913-02163E014472.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`
then:

```
cmsRun l1NtupleRECO_RAW2DIGI.py
root -x L1Trigger/L1TCommon/macros/rates.C
root -x L1Trigger/L1TCommon/macros/kin.C
```

All the functionality of `L1Trigger/Configuration/python/customise_Stage2Calo.py` has also been moved to the above config plus small additional customs described above.  But waiting on green light from @jimbrooke before deleting this.

**Comment by jimbrooke** [comment]
I am getting this error (from command below).  Any ideas?

```
customising the process with L1TEventSetupForHF1x1TPs from L1Trigger/Configuration/customiseReEmul
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_0_pre6/bin/slc6_amd64_gcc493/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_0_pre6/bin/slc6_amd64_gcc493/cmsDriver.py", line 27, in run
    configBuilder.prepare()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_0_pre6/python/Configuration/Applications/ConfigBuilder.py", line 2197, in prepare
    self.pythonCfgCode += self.addCustomise()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc493/cms/cmssw/CMSSW_8_0_0_pre6/python/Configuration/Applications/ConfigBuilder.py", line 869, in addCustomise
    raise Exception("config "+f+" has no function "+fcn)
Exception: config L1Trigger/Configuration/customiseReEmul has no function L1TEventSetupForHF1x1TPs

```

cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW  --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --geometry=Extended2016,Extended2016Reco --conditions=auto:run2_data --no_output -n 1000 --data --filein=/store/data/Run2015D/SingleMuon/RAW/v1/000/260/627/00000/62834F8D-4C82-E511-8E4C-02163E013555.root

**Comment by jimbrooke** [comment]
Ah, I was using the l1t-integration-v2 tag at the top of the thread....  Now trying with v3.1

**Comment by apana** [comment]
Hi Jim, Mike

It looks like the cmsDriver command work for me in v3.1. Running cmsRun
now...

-Len

**Comment by jimbrooke** [comment]
What is the status of Layer 1 integration in this branch?  Are Bhawna's latest commits for HF tower calibration in here?

**Comment by mulhearn** [comment]
Not yet... do you need this urgently?  Was going to be next after some testing...

**Comment by jimbrooke** [comment]
We need it for our next set of tests, which I would really like to base on this branch/tag if possible, to reduce entropy.  But I can just ask Bhawna for the relevant commits and cherry pick them.  (Or a PR, which is how I guess this would work in future - check out an integration tag, add a PR, run tests...?)

**Comment by mulhearn** [comment]
No!!!  I'll add ASAP!

**Comment by mulhearn** [comment]
Yes about workflow.

**Comment by apana** [comment]
Hi Mike,

v3.1 gives me identical results with the l1t-calostage2 branch for all calo
objects. I see a slight difference for muons, but I don't think muons are
expected to be identical.

-Len

**Comment by SridharaDasu** [comment]
Dear Jim,

Our HF changes are committed to Layer1 development branch:

l1t-layer1-CMSSW_8_0_0_pre6

The changes probably need to be cherry-picked.  I believe the latest commit is:

https://github.com/cms-l1t-offline/cmssw/commit/d84459e69fe955fea755c2b39ada03ecb843d4ef

Regards,
Sridhara

**Comment by mulhearn** [comment]
I'm about to release v4.0 which includes these.

**Comment by mulhearn** [comment]
...but it failed some tests.  I'll post steps to reproduce problem shortly too.

**Comment by jimbrooke** [comment]
Other than this issue, everything looks good to me

**Comment by mulhearn** [comment]
Excellent, so I can go ahead and delete `L1Trigger/Configuration/python/customise_Stage2Calo.py`?

**Comment by jimbrooke** [comment]
Yes, please do!

**Comment by mulhearn** [comment]
Done.  Now working on v5.0 which will include Thomas fix for muon quality and cancel out.

**Comment by mulhearn** [comment]
@thomreis can you have a look at tag l1t-integration-v5.0 and make sure it behaves as you expect.

**Comment by jimbrooke** [comment]
I would like to include this before circulating this recipe widely
https://github.com/jimbrooke/cmssw/commit/05f3b81112407686d421f025782ece675f8f5454
Should I make a PR to this branch?

**Comment by jimbrooke** [comment]
Also this change to default jet threshold for HT/MHT sums
https://github.com/jimbrooke/cmssw/commit/facb85979456ab53bc0e39fa29087c18eed61e78

**Comment by mulhearn** [comment]
Sorry, off duty this morning!  I don't mind cherry-picking these...

**Comment by bortigno** [comment]
Before closing the TSG-tag can we check that the eta-assignment bug fix from BMTF in is @190d76fd108d1c84ae8b6787b33dfc64cec6907b ?

**Comment by mulhearn** [comment]
@jimbrooke the fix for layer-1 from @gomber @SridharaDasu is in l1t-integration-v6.1, and all my tests pass now when using bitwise Layer-1 emulator.  So this is ready for use!

@bortigno now working on v7.0, which will have any last minute updates for muons, and will check with Giannis what config changes are needed to turn on the new algorithm...

**Comment by gflouris** [comment]
@mulhearn Set fwVersion to 2 in fakeBmtfParams_cff.py for the new algo.

**Comment by mulhearn** [comment]
@gflouris @thomreis at tag l1t-integration-v7.0 this branch now includes latest BMTF eta fix, and switches the firmware version to 
`fwVersion = cms.uint32(2),`
for BMTF.  My tests so far are insensitive to the change, so I could use confirmation that this has the expected improvements properly turned on...  can you guys have a look?

**Comment by gflouris** [comment]
@mulhearn I have just re-emulated 1000 events using runMuonBarrel.py with fwVersion 1 and 2. The bmtf pt spectrum differs between the two versions.

**Comment by mulhearn** [comment]
l1t-integration-v7.0 has been tested thoroughly and is ready to become l1t-tsg-v3

**Comment by mulhearn** [comment]
Unfortunately, "cmsrel" does not presently work on lxplus, so I am unable to actually make the tag...

**Comment by mulhearn** [comment]
@thomreis requests inclusion of PR #168.

**Comment by mulhearn** [comment]
special tag l1t-integration-v9.0-layer1 is available now for anyone that wants the bitwise layer-1 emulator used by default.  There will be a slight over-calibration in this tag.  I'll also have  l1t-integration-v9.0 with same stand-in layer-1 we have been using in past, so that present calibrations remain consistent.

**Comment by mulhearn** [comment]
@thomreis, your muon ntuple updates are in v9.1

**Comment by rekovic** [comment]
Now working on merging Andrew's fixes for BX assignments in EMTF

**Comment by thomreis** [comment]
@mulhearn please take not of this PR: https://github.com/cms-l1t-offline/cmssw/pull/185

**Comment by mulhearn** [comment]
@jimbrooke the fixes from @gomber and @SridharaDasu are in l1t-integration-v10-layer1, with bitwise layer-1 emulation turned on by default.

**Comment by rekovic** [comment]
@mrcarver @thomreis Muon fixes (BX and quality) are in l1t-integration-v11.0

The effect on Muon rates (drop about 50%)  can be seen here 
/afs/cern.ch/user/r/rekovic/public/forL1TStage2/l1t-integration/rateComparison_l1t_integraion_v11.0_vs_9.4.log

**Comment by rekovic** [comment]
@davignon Tau fixes (compression, LUTs, emulator) are in l1t-integration-v12.0

The effect on the Tau rates (increase about 15%) can be seen here
/afs/cern.ch/user/r/rekovic/public/forL1TStage2/l1t-integration/rateComparison_l1t_integraion_v12.0_vs_11.0.log

**Comment by rekovic** [comment]
Updated previous 2 comments with comparison log files showing effect on relevant L1T rates.

**Comment by mulhearn** [comment]
The branch, based on CMSSW_8_0_0_pre6 is now obsolete... integration will continue under 8_0_2 at issue #189
