### ISSUE TITLE
Problem with Calo Layer1 Emulator and HF 1x1 re-Emulation

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#169]
To reproduce the problem, simply follow the main recipe at #164 for tag l1t-integration-v4.0
If you run the re-Emulation example out of the box you'll see it runs fine using stand-in Layer1 emulator.

If you then repeat the test after selecting real/bitwise Layer1emulator, by editing `L1Trigger/L1TCalorimeter/python/simDigis_cff.py` then you should see an error like:

```
UCTLayer1::setHCALData - Crate number is wrong - deadbeef (eta,phi)=(31,57)
```

This seems to be related to the updates to use the HF 1x1 TPs, because if I leave out the customizations `--geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs` it runs just fine.

**Comment by mulhearn** [comment]
@SridharaDasu @gomber please take a look and fix if possible.  I'll post some instructions for how to submit the bugfix for easy inclusion in our integration branch.

**Comment by mulhearn** [comment]
Your git workflow should look like this (after following above steps):

```
git checkout -b mydevel
# work
git add <files>
git commit -m "bug fix for blah blah"
git push cms-l1t-offline mydevel:l1t-bugfix-layer1-hf1x1-$CMSSW_VERSION
```

At this point, you can either just alert me that its ready to merge in, or if you want to be fancy, make a PR directly into our integration branch by:
 1) Finding your branch l1t-bugfix-... on github website.
 2) Push the "New Pull Request" Button
 3) Navigate the annoying pull down menus to set basefork to "cms-l1t-offline" and base to "l1t-integration-CMSSW_8_0_0_pre6".
4) Have a look at the preview and make sure it makes sense, then submit.

**Comment by gomber** [comment]
Looking now, will get back asap!

**Comment by mulhearn** [comment]
Thanks @gomber.

**Comment by SridharaDasu** [comment]
Dear Jim and Mike,

In the HF region, i.e., eta=30-41 there should only be 36 or 18 phi 
divisions.  The numbering scheme I thought was agreed upon is:

ieta=1-28   iphi=1-72
ieta=31-39  iphi=1-36 (towers are duplicated in Layer-1 firmware, each carrying ET/2)
ieta=40-41  iphi=1-18 (towers are quadrupled in Layer-1 firmware, each carrying ET/4)

Therefore, per our code iPhi=57 shouldn't have happened at all.
However, it appears uHTR unpacker always uses 1-72 and pick every 
other or every fourth number to indicate phi.

Therefore, we need to change our geometry description a bit.

We made a quick test, with a kludge, and it seems to work.  However, 
the kludge will not work with our unpacker.  We will make a proper
fix in the next few hours and commit both unpacker and emulator.

Thanks,
Sridhara

**Comment by SridharaDasu** [comment]
Dear Mike,

This is done:

-bash-4.1$ git push cms-l1t-offline mydevel:l1t-bugfix-layer1-hf1x1-$CMSSW_VERSION
Enter passphrase for key '/afs/cern.ch/user/d/dasu/.ssh/id_rsa': 
Counting objects: 49, done.
Delta compression using up to 36 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (22/22), 2.59 KiB | 0 bytes/s, done.
Total 22 (delta 18), reused 0 (delta 0)
To git@github.com:cms-l1t-offline/cmssw.git
- [new branch]      mydevel -> l1t-bugfix-layer1-hf1x1-CMSSW_8_0_0_pre6
  -bash-4.1$ 

I tried to go fancy as you recommend, but without reading all four 
of your steps.

I made a pull request accidentally to the main CMSSW area :(
I assume managers there including you can kill that request.
I did not bother making correct pull request fearing another screwup.
I leave it to you to integrate this then.

Thanks,
Sridhara

**Comment by nsmith-** [comment]
Lending a helping hand : >

**Comment by mulhearn** [comment]
Thanks @nsmith-

**Comment by mulhearn** [comment]
Merged.
