### ISSUE TITLE
Problems with GT packing/unpacking of Inputs

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#172]
There were crashes in MWGR#2 due to GT unpacking failing.  The crashes were during unpacking of the GT inputs, which I have turned off in cms-sw#13514 as a fast mitigation.  The GT output will still be available as will the inputs (via GMT and Calo).

While investigating, I noticed that the packer had these inputs disabled.  I suspect this is how we missed the problem with the unpacker.

Anyway, in this thread, we should track a proper fix, that includes packing and unpacking all the GT inputs.  A good way to start would be to see if just turning on the packing and unpacking leads to crashes when testing DIGI2RAW+RAW2DIGI.  If not, the online crash is reproduced in 800_patch2 by this config file:
https://mulhearn.web.cern.ch/mulhearn/public/L1TEST_RAW2DIGI.py

**Comment by mulhearn** [comment]
@blwiner @puigh lets track the complete fix here.

**Comment by mulhearn** [comment]
Well, I understand why the packing of GT inputs do not work at all... this was clearly commented out by me pending a fix but was then forgotten...  The problem is here:
https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre6/EventFilter/L1TRawToDigi/src/implementations_stage2/JetPacker.cc#L26
that can't possibly work.  The cast to CaloTokens won't work if what it was actually passed was e.g. a GTTokens.  This is a misunderstanding about how static_cast works.  static_cast can't turn an orange into a tangerine.

**Comment by mulhearn** [comment]
Maybe dynamic_cast plus an inheritance like:

```
class GTTokens : public GMTTokens, public CaloTokens { ... }
```

would work.  Have to test this with a toy.

**Comment by mulhearn** [comment]
But safer might be just be to define GTTokens and have GMT/Calo use GTTokens (ignoring the parts they don't need).

**Comment by mulhearn** [comment]
Playing with the toy it is clear the fancy / scary multiple inheritance won't work...

**Comment by mulhearn** [comment]
I think the safest way out is like this toy:

```
#include <iostream>
using namespace std;

class base {};

class common : public base{
public:
  virtual int f1() { return 0; }
  virtual int f2() { return 0; }
};

class d1 : public common {
public:
  d1(int i) : i(i) {}
  virtual int f1() { return i; }
private:
  int i;
};

class d2 : public common {
public:
  d2(int i) : i(i) {}
  virtual int f2() { return i; }
private:
  int i;
};

class d3 : public common {
public:
  d3(int i, int j) : i(i), j(j) {}
  virtual int f1() { return i; }
  virtual int f2() { return j; }
private:
  int i,j;
};



int main(){
  cout << "Hello World\n";

  base * pb = new d3(1,2);
  cout << (static_cast<common *>(pb))->f1() << "\n";
  cout << (static_cast<common *>(pb))->f2() << "\n";

  pb = new d1(1);
  cout << (static_cast<common *>(pb))->f1() << "\n";
  cout << (static_cast<common *>(pb))->f2() << "\n";

  pb = new d2(2);
  cout << (static_cast<common *>(pb))->f1() << "\n";
  cout << (static_cast<common *>(pb))->f2() << "\n";


  return 0;
}

```

which outputs, as you'd expect:

```
Hello World
1
2
1
0
0
2
```

**Comment by mulhearn** [comment]
This is what I have in mind, but not working yet:
https://github.com/cms-l1t-offline/cmssw/commit/b60d7c6cbb8a458c538715149278ae93f76efdf5

**Comment by blwiner** [comment]
@Mulhearn  I have a couple of comments and questions.

  1) Do you think the crash was caused because the GT input was not
packed?  I'm a bit confused why this would have caused a crash.

  2) There is another problem with the GT input packing that I had pointed
out quite some time ago.  The GT packing/unpacking  uses the same code as
the Calo system. On the packing side there are lines of code like the
following:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre6/EventFilter/L1TRawToDigi/src/implementations_stage2/JetPacker.cc#L58

https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre6/EventFilter/L1TRawToDigi/src/implementations_stage2/EGammaPacker.cc#L52

https://github.com/cms-l1t-offline/cmssw/blob/l1t-dev-recipe-CMSSW_8_0_0_pre6/EventFilter/L1TRawToDigi/src/implementations_stage2/TauPacker.cc#L52

If you look at this code, the block numbers are hardcoded. I believe this
means there is an assumption regarding which links these data are on.   The
link (fiber) mapping is not the same for the uGT as for the DeMux.    Maybe
I am not interpreting this correctly, but I think there is a problem here.

 -Brian

On Sat, Feb 27, 2016 at 11:45 PM, mulhearn notifications@github.com wrote:

> This is what I have in mind, but not working yet:
> b60d7c6
> https://github.com/cms-l1t-offline/cmssw/commit/b60d7c6cbb8a458c538715149278ae93f76efdf5
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-189783448
> .

## 

---

B. Winer

**Comment by mulhearn** [comment]
@blwiner 
1) Only indirectly...  since we had the packing turned off, we weren't exercising the unpackers, though they were turned on, and so didn't catch the problem ahead of time.  Essentially, we had unused code that we used for the first time during the MWGR... not a recipe for a success!

2)  Indeed, that does look like a problem too.

IWe'll just have to leave GT unpacking of inputs off until we sort this all out.

**Comment by jimbrooke** [comment]
@blwiner Am I right in thinking the issue with hard-coded Block numbers only affects the Packer?  I think for the unpacker, the Block <-> code assignment is done separately in CaloSetup and GTSetup so there should be no problem there.  

The long term solution for the packer is to create an object(s) which stores the mapping information, make it available via EventSetup, and then have the L1TRawToDigi framework make this available to packer/unpacker code.

**Comment by mulhearn** [comment]
@jimbrooke, I don't thing the EventSetup is enough.  Still the packer will need to know which case it is being used for (Packing for GT or packing for GMT/Calo).

**Comment by tmatsush** [comment]
There was one (unintended) change between script based operation (uGT parallel running) and swatch based operation (stage-2 trigger). The input link 11, which carries no valid data,  was included in the uGT parallel running but not in stage-2 trigger. Does this cause the problem in unpacker ?

**Comment by tmatsush** [comment]
the current uGT input data format;
https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerUpgradeInputSpec

**Comment by mulhearn** [comment]
@tmatsush:  no that didn't cause the problem, as I can reproduce the crash using data from MWGR#1.  For which I sincerely apologize, as it means we could have in principle detected this before MWGR#2 if we had our complete set of integration tests together in time...

**Comment by jimbrooke** [comment]
@mulhearn i had assumed it would get that from the FED ID, but I see this is not actually passed to the pack() method.  I think that's how I would solve it.

**Comment by tmatsush** [comment]
uGT readout (just the tx part) overview:
https://twiki.cern.ch/twiki/bin/view/CMS/GlobalTriggerUpgrade-ReadoutSpec

**Comment by mulhearn** [comment]
@jimbrooke I had similar thoughts, as that could be used to retrieve the correct config in the EventSetup as well...

**Comment by jimbrooke** [comment]
@mulhearn am I right in thinking this is like a not

**Comment by blwiner** [comment]
@jimbrooke  you are correct that I never saw any problem with this on the
unpacking side.

On Mon, Feb 29, 2016 at 6:24 AM, Jim B notifications@github.com wrote:

> @blwiner https://github.com/blwiner Am I right in thinking the issue
> with hard-coded Block numbers only affects the Packer? I think for the
> unpacker, the Block <-> code assignment is done separately in CaloSetup and
> GTSetup so there should be no problem there.
> 
> The long term solution for the packer is to create an object(s) which
> stores the mapping information, make it available via EventSetup, and then
> have the L1TRawToDigi framework make this available to packer/unpacker code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190163364
> .

## 

---

B. Winer

**Comment by blwiner** [comment]
@mulhearn @jimbrooke:

  Possible problem with muon unpacking:

https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_patchX/EventFilter/L1TRawToDigi/src/implementations_stage2/MuonUnpacker.cc#L36

compared with:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-global-jan-dev-CMSSW_8_0_0_pre1/EventFilter/L1TRawToDigi/src/implementations_stage2/MuonUnpacker.cc#L39

  The muon unpacker does not have the generic collection
(L1ObjectCollection) that it needs in order for the GT unpacker to use the
same code.

  I am working on trying to see if this fixes the problem

 -Brian

On Mon, Feb 29, 2016 at 9:36 AM, Brian Winer brianwiner@gmail.com wrote:

> @jimbrooke  you are correct that I never saw any problem with this on the
> unpacking side.
> 
> On Mon, Feb 29, 2016 at 6:24 AM, Jim B notifications@github.com wrote:
> 
> > @blwiner https://github.com/blwiner Am I right in thinking the issue
> > with hard-coded Block numbers only affects the Packer? I think for the
> > unpacker, the Block <-> code assignment is done separately in CaloSetup and
> > GTSetup so there should be no problem there.
> > 
> > The long term solution for the packer is to create an object(s) which
> > stores the mapping information, make it available via EventSetup, and then
> > have the L1TRawToDigi framework make this available to packer/unpacker code.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190163364
> > .
> 
> ## 
> 
> ---
> 
> B. Winer

## 

---

B. Winer

**Comment by blwiner** [comment]
@mulhearn   OK.  First I tried turning off only the muon unpacking and
leaving the other unpackers in place.  The crash goes away.  The muon code
was definitely not updated to be used with the GT.

 -Brian

On Tue, Mar 1, 2016 at 9:00 AM, Brian Winer brianwiner@gmail.com wrote:

> @mulhearn @jimbrooke:
> 
>   Possible problem with muon unpacking:
> 
> https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_0_patchX/EventFilter/L1TRawToDigi/src/implementations_stage2/MuonUnpacker.cc#L36
> 
> compared with:
> 
> https://github.com/cms-l1t-offline/cmssw/blob/l1t-global-jan-dev-CMSSW_8_0_0_pre1/EventFilter/L1TRawToDigi/src/implementations_stage2/MuonUnpacker.cc#L39
> 
>   The muon unpacker does not have the generic collection
> (L1ObjectCollection) that it needs in order for the GT unpacker to use the
> same code.
> 
>   I am working on trying to see if this fixes the problem
> 
>  -Brian
> 
> On Mon, Feb 29, 2016 at 9:36 AM, Brian Winer brianwiner@gmail.com wrote:
> 
> > @jimbrooke  you are correct that I never saw any problem with this on the
> > unpacking side.
> > 
> > On Mon, Feb 29, 2016 at 6:24 AM, Jim B notifications@github.com wrote:
> > 
> > > @blwiner https://github.com/blwiner Am I right in thinking the issue
> > > with hard-coded Block numbers only affects the Packer? I think for the
> > > unpacker, the Block <-> code assignment is done separately in CaloSetup and
> > > GTSetup so there should be no problem there.
> > > 
> > > The long term solution for the packer is to create an object(s) which
> > > stores the mapping information, make it available via EventSetup, and then
> > > have the L1TRawToDigi framework make this available to packer/unpacker code.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190163364
> > > .
> > 
> > ## 
> > 
> > ---
> > 
> > B. Winer
> 
> ## 
> 
> ---
> 
> B. Winer

## 

---

B. Winer

**Comment by mulhearn** [comment]
@blwiner, indeed that looks suspicious...  this up-casting is a perilous business.   Note that if you simply change this to work with GT, it will likely crash unless corresponding changes are made on Muon side:
i.e. this crash is probably L1TObjectCollection being incorrectly static_cast as L1TGMTCollection, but it will likely equally crash if L1TGMTCollection is  incorrectly static_cast as L1TObjectCollection.

**Comment by blwiner** [comment]
@mulhearn  I have made a couple of changes to the muon code and the crash
goes away.  This probably needs to be tested with muon repacking/unpacking
to verify nothing is broken.  Do you want me to put these changes someplace?

 Brian

On Tue, Mar 1, 2016 at 10:03 AM, mulhearn notifications@github.com wrote:

> @blwiner https://github.com/blwiner, indeed that looks suspicious...
> this up-casting is a perilous business. Note that if you simply change this
> to work with GT, it will likely crash unless corresponding changes are made
> on Muon side:
> i.e. this crash is probably L1TObjectCollection being incorrectly
> static_cast as L1TGMTCollection, but it will likely equally crash if
> L1TGMTCollection is incorrectly static_cast as L1TObjectCollection.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190758007
> .

## 

---

B. Winer

**Comment by mulhearn** [comment]
Yes, can you do:
`git push cms-l1t-offline <current branch>:l1t-bugfix-gt-unpacker`
Its a near certainly this will now crash muon unpacker if there code isn't changed to send L1TObjectCollection (instead of L1TGMTCollection) to the unpacker...

**Comment by mulhearn** [comment]
@thomreis:  once blwiners code is in place, can you make the corresponding changes to the muon code that use the L1TObjectCollection instead of L1TGMTCollection?  I think we had a situation where both sides kept flipping this back and forth!  The fix is for _everyone_ to use L1TObjectCollection _everywhere_ and delete L1TGMTCollection.  If I understand correctly...

**Comment by blwiner** [comment]
@mulhearn @thomreis  is pushed the changes to  l1t-bugfix-gt-unpacker .

@mulhearn  Does your L1Test_RAW2DIGI.py  exercise the muon side?  Because
with these changes that config runs fine. But we should test in more detail
regardless.

 -Brian

On Tue, Mar 1, 2016 at 10:33 AM, mulhearn notifications@github.com wrote:

> @thomreis https://github.com/thomreis: once blwiners code is in place,
> can you make the corresponding changes to the muon code that use the
> L1TObjectCollection instead of L1TGMTCollection? I think we had a situation
> where both sides kept flipping this back and forth! The fix is for
> _everyone_ to use L1TObjectCollection _everywhere_ and delete
> L1TGMTCollection. If I understand correctly...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190772504
> .

## 

---

B. Winer

**Comment by thomreis** [comment]
@blwiner Sorry this has passed under my radar. Are the changes that you did for the muon unpacker everything that is needed. Is the RegionalMuonGMTUnpacker affected by this?

**Comment by blwiner** [comment]
@thomreis  I think the RegionalMuonGMTUnpacker should be looked at.  What
I know is that the changes I put in get rid of the uGT crash that Mike was
able to reproduce with his config script.   I'm not sure if that test
script exercised the region muon unpacking, that's why I asked Mike that
question.  Hopefully he can comment more.  Do you have a test for all the
muon packing and unpacking that you could try this code?

 -Brian

On Tue, Mar 1, 2016 at 12:17 PM, Thomas Reis notifications@github.com
wrote:

> @blwiner https://github.com/blwiner Sorry this has passed under my
> radar. Are the changes that you did for the muon unpacker everything that
> is needed. Is the RegionalMuonGMTUnpacker affected by this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-190820203
> .

## 

---

B. Winer

**Comment by jimbrooke** [comment]
I imagine a cmsDriver -s RAW2DIGI command using a file from a run from last week with calo, uGMT, uGT FEDs included would be a pretty good test of all unpackers simultaneously.  I'll see if I can find a file.

**Comment by tmatsush** [comment]
@jimbrooke 
not from MWGR2 but 264573 in MWGR1 includes uGMT, uGT, layer-2 FEDs

**Comment by thomreis** [comment]
I have applied the changes of d6f0cb4808e18d9a2e4ab5597818a63e405469d9 and ran on run 265648 data. The unpacked data for uGMT inputs and outputs look fine.

**Comment by mulhearn** [comment]
Ah, beautiful, I see Brian already made:

```
 -      class GMTCollections : public UnpackerCollections {
 +      class GMTCollections : public L1TObjectCollections {
```

which I believe is all that was needed to make this work for Muons too.  No more apples static cast as oranges!

**Comment by tmatsush** [comment]
The followings are runs with uGT read-out record included (parallel running):

MWGR2
265637: uGMT + uGT (FEDs 1402, 1404)

MWGR1
264573: layer2 + uGMT + uGT (FEDs 1360, 1366, 1402, 1404)
264586: layer2 + uGT (FEDs 1360, 1366, 1404)

And the parallel run without uGT but with layer2 + uGMT
264593: layer2 + uGMT  (FEDs 1360, 1366, 1402)

**Comment by mulhearn** [comment]
The fix for unpacker is in l1t-integration-v9.0 of integration branch.  My new integration tests caught the crash before hand, but it passes with this fix included...   but we still need a packer to thoroughly test this!

**Comment by mulhearn** [comment]
OK, so I have at last made some progress on this one again, I think its time to hand this back to @blwiner and @puigh.  There's a new topic branch at

https://github.com/cms-l1t-offline/cmssw/tree/l1t-debug-gt-unpacker-CMSSW_8_0_2

Just cms-merge this branch in the usual way using CMSSW_8_0_2

This includes the updated to the packer to use a  CommonToken base class for overlap of GT/Calo/Muon (which are the GT inputs).

It works for Calo and Muon, but I find that the GT inputs are still empty after packing / unpacking.  I can't spot the problem after some time looking and hoping Darren/Brian will be able to catch it since they wrote the first version of the packer/unpacker.

To see the problem, run the debugging test I added in this branch:

```
cmsRun EventFilter/L1TRawToDigi/test/debug_gt_unpacker.py
```

You can see in the output that the unpacked inputs of GT are empty:

```
eg:    0
tau:   0
jet:   0
sum:   0
muon:  0
```

despite the packer finding non-zero input collections:

```
DEBUG:  MUONS:  0 size:  2
DEBUG:  MUONS:  0 size:  2
```

(two instances of packer use the Muon packing, GT and GMT)

```
DEBUG GTCollections:  Muon Size at BX=00
```

(BX=0 size is 0 at unpacker)

**Comment by mulhearn** [comment]
Cleaned up up some packer<-->unpacker typos in original comment... (follow view it on github to see corrected version of previous comment.)

**Comment by mulhearn** [comment]
@rekovic please just cherry-pick 5ca556710eb26addeb21f75432d6a88bbac2f85c for your work.

**Comment by blwiner** [comment]
@mulhearn  I don't understand how this code fixes our problem.  If I look
at the EGammaPacker.cc, the return statement looks like

 return {Block(9, load1), Block(11, load2)};

So the block IDs are still hard coded.  This doesn't work because the EG
output on the DeMux board are on different blocks than the input for the
uGT board.  So this cannot possibly pack the uGT input into the correct
blocks.

 -Brian

On Wed, Apr 13, 2016 at 7:44 AM, mulhearn notifications@github.com wrote:

> OK, so I have at last made some progress on this one again, I think its
> time to hand this back to @blwiner https://github.com/blwiner and @puigh
> https://github.com/puigh. There's a new topic branch at
> 
> https://github.com/cms-l1t-offline/cmssw/tree/l1t-debug-gt-unpacker-CMSSW_8_0_2
> 
> Just cms-merge this branch in the usual way using CMSSW_8_0_2
> 
> This includes the updated to the packer to use a CommonToken base class
> for overlap of GT/Calo/Muon (which are the GT inputs).
> 
> It works for Calo and Muon, but I find that the GT inputs are still empty
> after packing / unpacking. I can't spot the problem after some time looking
> and hoping Darren/Brian will be able to catch it since they wrote the first
> version of the packer/unpacker.
> 
> To see the problem, run the debugging test I added in this branch:
> 
> cmsRun EventFilter/L1TRawToDigi/test/debug_gt_unpacker.py
> 
> You can see in the output that the unpacked inputs of GT are empty:
> 
> eg:    0
> tau:   0
> jet:   0
> sum:   0
> muon:  0
> 
> despite the unpacker finding non-zero input collections:
> 
> DEBUG:  MUONS:  0 size:  2
> DEBUG:  MUONS:  0 size:  2
> 
> (two instances of packer use the Muon packing, GT and GMT)
> 
> DEBUG GTCollections:  Muon Size at BX=00
> 
> (BX=0 size is 0 at packer)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/172#issuecomment-209385948

## 

---

B. Winer

**Comment by mulhearn** [comment]
My fix was only for the input Tokens....  it seems that this mapping needs to be added as a configuration as well.  Let me look...

**Comment by mulhearn** [comment]
Thanks @blwiner for finding the problem.  Thanks @matz-e for suggesting the solution.  All I had to do was code it up, and we now have GT packing and unpacking of inputs!

```
INFO: count of non-zero candidates for each type follows:
eg:    16
tau:   37
jet:   21
sum:   20
muon:  6
```

**Comment by mulhearn** [comment]
Here's a test bitwise comparing the unpacked (GT) payload with simulated payload:

```
INFO: count of successful comparison for each type follows:
eg:    16
tau:   37
jet:   21
sum:   20
muon:  6
INFO: count of failed comparison for each type follows:
eg:    0
tau:   0
jet:   0
sum:   0
muon:  0
```

**Comment by mulhearn** [comment]
Here's the PR:  #248

This one is closed at last!
