### ISSUE TITLE
Speeding up L1 calo emulation

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#173]
@SridharaDasu @gomber I have a small request to change how the Layer 1 emulator outputs the tower collection.  i think the Layer 1 module currently uses BXVector::push_back(bx, tower).  However, we have a function that will calculate a vector index from tower ieta, iphi.  If you then call BXVector::set(bx, index, tower) a given tower is always at the same position in the vector.  This facilitates faster access in the Layer 2 emulator.  The index method is 
https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_0_pre6/L1Trigger/L1TCalorimeter/interface/CaloTools.h#L58

**Comment by gomber** [comment]
We will include this change and get back.

**Comment by mulhearn** [comment]
This is v9.0
