### ISSUE TITLE
Critical Issues for MWGR#3 and HLT/L1T interface

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#175]
Tracking issues needed for MWGR#3 and the HLT/L1T interface.

Twiki for the Joint Ops meeting is here:
https://twiki.cern.ch/twiki/bin/view/CMS/OfflineOperationsMeeting03032016

Needed for both:
- quick fix for GT unpacker problems:  PR cms-sw#13538 (Merged)
  - need PR to patchX as well:  cms-sw#13576 (Merged)

Needed for HLT/L1T:
- Set muon quality for passing muons to 12, for use in GT emulation:  cms-sw#13548 (Merged)
- L1TGlobalSummary and L1TGlobalUtils:  PR cms-sw#13542 (Merged)
- For L1Candidate products, use instance label to enable use of edm::View:  cms-sw#13547 (Merged)

Needed for MWGR#3:
- PR for new L1TGlobal XML Menu file:  https://github.com/cms-data/L1Trigger-L1TGlobal/pull/1
- Confirm that all XML needed by HLT is in the release (looks good to me, asked HLT+Takashi to confirm)

Not critical, but wanted for 801:
- I noticed that latest EMTF unpacker updates are not in 800 yet.  These are not included in Standard Sequences yet, but should add for DQM use.
- requested unpacker updates for BMTF as well.
- Jim has some extensions to calo DataFormats that he'd like to add and not use yet:  cms-sw#13584

Tests should be run before MWGR#3, with time to adapt if needed:
- Tests of Vladimir using ".raw" in HLT sequence.  
- Integration tests with MWGR#2 data.

**Comment by mulhearn** [comment]
@fwyzard @Martin-Grunewald @tmatsush can you please have a look here:  https://github.com/cms-l1t-offline/L1Trigger-L1TGlobal/tree/master/Luminosity/startup
and confirm that all the XML files you would potentially like to use for "MW"GR3 are present?

**Comment by tmatsush** [comment]
I confirm the menu used in MWGR2, L1Menu_Collisions2015_25nsStage1_v7_uGT_v3.xml,
and the menu for "MW"GR3, L1Menu_Collisions2015_25nsStage1_v7_uGT_v4.xml, are included in the directory.

According to the comment from Martin [https://github.com/cms-l1t-offline/cmssw/issues/103#issuecomment-190308570] these xml files should be "external" (which I am not familiar with)

**Comment by mulhearn** [comment]
Yes, that just means they aren't in cms-sw/cmssw repo, but rather cms-data/L1Trigger-L1TGlobal repo, then findable in release under $CMSSW_DATA_PATH.  But you still access in same way, as long as you properly use edm::FileInPath(..)

**Comment by Martin-Grunewald** [comment]
So what will the next MWGR be based on? 800p2 still had the files inside CMSSW,
while the IBs moved to have the externals. If MWGR3 uses 800p3 based on 800p2, 
we need the menu both in that release, but for IBs also in the external.

**Comment by mulhearn** [comment]
@Martin-Grunewald MWGR3 will use 801, which will have these as externals.

**Comment by mulhearn** [comment]
So plan is, Friday tests will be based on L1Menu_Collisions2015_25nsStage1_v7_uGT_v3.xml using 800_patch3.  When 801 is out (promised in time for GR#3) it will have the new external data, that includes L1Menu_Collisions2015_25nsStage1_v7_uGT_v4.xml
