### ISSUE TITLE
Request of new method in UTM for O2O

### ISSUE THREAD

**Issue by tmatsush** [cms-l1t-offline/cmssw#176]
@kkotov @mulhearn 

Let's keep track this issue here;

2016/03/02 22:46、Takashi MATSUSHITA takashi.matsushita@cern.ch :

Hi Khristian

I think I can prepare the interface like;

const esTriggerMenu\* getTriggerMenu(std::istringstream);

Is this what you want ?
Are you going to use UTM comes with CMSSW ?

Cheers,
Takashi

2016/03/02 20:50、Khristian Kotov khristian.kotov@cern.ch :

Hi Takashi,

I see your ESProducer uses UTM library to convert an XML file in the L1 Menu CondFormats
object. Would it be also possible to provide function that creates the object from an XML that
is represented by an std::string? Otherwise, our L1T O2O job would have to write a file once
the menu is fetched from the DB.

Thanks,
 Khristian.

**Comment by tmatsush** [comment]
@kkotov 

I will add the method in UTM so that you can test it.
Once the method become available, you can follow the instruction at the following link to test the private version of UTM;
https://gitlab.cern.ch/cms-l1t-utm/utm
When the method is tested ok, let's ask update of UTM library in CMSSW release.

2016/03/03 8:17、Khristian Kotov khristian.kotov@cern.ch：

Hi Takashi,

Yes, the function that you proposed is exactly what I'd like to use in the L1T O2O.

Although, I'd like to use what comes with the CMSSW, I may have to go ahead and
link my stuff against a local customized version of this external library rather than
wait when the new release comes out and propagates to p5. I didn't yet check how
to link a CMSSW job with an external library, but I hope I'll be able to figure it out.
Otherwise, if you have a working example, I'd take advantage and have a look at it.

Thanks,
 Khristian.

**Comment by tmatsush** [comment]
@kkotov 
can you try the instruction at;
  https://gitlab.cern.ch/cms-l1t-utm/utm/blob/master/README.md
You can change the following line in Demo/tmEventSetup/test/test.cc
  `const esTriggerMenu* menu = tmeventsetup::getTriggerMenu(file);`
with something like;
  `std::ifstream ifs(file);`
  `std::string buf( (std::istreambuf_iterator<char>(ifs) ),
                   (std::istreambuf_iterator<char>()    ) );`
  `std::istringstream iss;`
  `iss.str(buf);`
  `const esTriggerMenu* menu = tmeventsetup::getTriggerMenu(iss);`

Please let me know if it works.

**Comment by kkotov** [comment]
@tmatsush 
I only had to define UTM_XSD_DIR environment variable that points to a random (existing) directory and everything else worked just fine. Thanks for the fix.

**Comment by tmatsush** [comment]
@kkotov 
Thanks for your check.
By the way, UTM_XSD_DIR is properly set in CMSSW environment. So you do not need to set it.
Outside of CMSSW environment, UTM_XSD_DIR should point to .../utm/tmXsd directory.

**Comment by kkotov** [comment]
We are almost done with integrating the L1T O2O PR to the release. The only remaining issue is updating the UTM library for the release: https://github.com/cms-sw/cmssw/pull/13810 . What is the new tag that Shahzad requests?

**Comment by tmatsush** [comment]
The new tag of utm library to use for L1T O2O of uGT menu is r43857-xsd310-patch

**Comment by kkotov** [comment]
@tmatsush
Thanks!
