### ISSUE TITLE
Muon quality integration

### ISSUE THREAD

**Issue by thomreis** [cms-l1t-offline/cmssw#179]
@mrcarver @gflouris @akalinow I have made a new development branch based on l1t-tsg-v3 to put the muon quality adjustments. https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-quality-CMSSW_8_0_0_pre6

You can get it with the following recipe:

```
cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git cms-merge-topic cms-l1t-offline:l1t-muon-quality-CMSSW_8_0_0_pre6
scram b -j 8
```

Please push your muon quality work there and notify me once done so that we can start making new rate and efficiency plots.

**Comment by gflouris** [comment]
@thomreis Done. New quality and masking are in.

**Comment by mrcarver** [comment]
@thomreis Also finished for EMTF.

**Comment by thomreis** [comment]
@mrcarver I do not see any EMTF muons produced. Could you check please?
There is a config file (https://github.com/cms-l1t-offline/cmssw/blob/l1t-muon-quality-CMSSW_8_0_0_pre6/l1NtupleRECO_RAW2DIGI.py) that I will use for ntuple generation. Using this I don't see any EMTF muons, but I expect around 20.

**Comment by mrcarver** [comment]
@thomreis Sorry for that. I used the wrong function to add the EMTF cands.
I just pushed again to the l1t-muon-quality-CMSSW_8_0_0_pre6 branch with
the proper implementation that I tested and can see output EMTF muons.
Please try again and let confirm you also see the same thing.

Best,
Matt
