### ISSUE TITLE
Packer/Unpacker Inconsistencies for Calo

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#182]
I see discrepancies when comparing emulated Calo output objects to packed+unpacked objects.

It looks like maybe a  straight-forward bit-shift error to me.
For EG objects, it looks like Iso is eating a Qual bit or vice versa:

COMPARISON FAILURE:  
hwQual = 7 hwIso = 0
hwQual = 3 hwIso = 2
COMPARISON FAILURE:  
hwQual = 7 hwIso = 1
hwQual = 3 hwIso = 3
COMPARISON FAILURE:  
hwQual = 7 hwIso = 1
hwQual = 3 hwIso = 3

For Sums it looks like maybe there is a problem with either the hwPhi and/or the Sum type:

COMPARISON FAILURE:  
hwPt = 73 hwEta = 0 hwPhi = 64
hwPt = 73 hwEta = 0 hwPhi = 0

L1T COMPARISON FAILURE:  EtSum type:2 vs 1
L1T COMPARISON FAILURE:  EtSum type:1 vs 2

**Comment by mulhearn** [comment]
Once I update integration branch with new testing code, the recipe to reproduce will be:
`cmsDriver.py L1TEST --conditions auto:run2_mc -s DIGI,L1,DIGI2RAW,RAW2DIGI --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --filein=/store/relval/CMSSW_7_6_0_pre7/RelValTTbar_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/0A812333-427C-E511-A80A-0025905964A2.root --python_filename=hack.py --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU
`

**Comment by mulhearn** [comment]
The new testing code used above is now available in  tag l1t-integration-v9.3

**Comment by tstreble** [comment]
The issue has been found and fixed for EG (it was indeed a bit-shift error).

INFO:  L1T Summary for Stage 2 Unpacked Digis
INFO: count of successful comparison for each type follows:
eg:    16
tau:   37
jet:   38
sum:   15
muon:  7
INFO: count of failed comparison for each type follows:
eg:    0
tau:   0
jet:   0
sum:   5
muon:  0

The fix is included in the PR
https://github.com/cms-l1t-offline/cmssw/pull/183

**Comment by mulhearn** [comment]
@jimbrooke @tstreble I have a fix for the EtSums now too.  Main fix is just to fill the sums during packing in the same order that is expected by the unpacker.  Second, for neatness, I changed the emulator to output in the same order as the unpacked sums.  Only thing left is to check that no one downstream is assuming a particular order...  I'll post the commit after I test some more for you to confirm is OK.

**Comment by mulhearn** [comment]
@rekovic I believe the incorrect EtSums were causing you trouble in HLT sequences, right?  So this fix should be of interest to you too...

**Comment by mulhearn** [comment]
Both fixes are in l1t-integration-14.2, and calo packing/unpacking is unity now.

**Comment by mulhearn** [comment]
@jimbrooke:  EtSum fix is here, please have a look and make sure it looks OK to you:  https://github.com/cms-l1t-offline/cmssw/commit/dae428349e91a640673c71abf97098e60dcd34d2

**Comment by rekovic** [comment]
Packing/Unpacking of Calo are causing serious problems in HLT.
After unpacking Calo we re-run the GT emulator, and most of the 
EtSums l1algos are currently disagreeing between emulated and 
unpacked decisions. 
I will check if solved with these fixes.

**Comment by rekovic** [comment]
It helps but does not get rid of all discr.

**Comment by rekovic** [comment]
git cms-addpkg EventFilter/L1TRawToDigi and re-compiling from clean helped.

Now all the discrepancies in HLT L1T unpakcing and re-emulation are gone.
Submitted PR #13786 to 80X. Need this immediately for MWGR#4.
