### ISSUE TITLE
L1 Private Integration Branch based on CMSSW 802

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#189]
The L1T integration branch has been forward ported to 802:

   https://github.com/cms-l1t-offline/cmssw/tree/l1t-integration-CMSSW_8_0_2

Only mulhearn should merge or push to this branch, however, developers are encouraged to make PRs to this branch when their effort has matured.

The TSG integration branch is simply a lagging version of this branch.  Only changes first integrated, and tested here, will be merged onto dev recipes and given a "l1t-tsg-vX" type tag.

To check out a defined working tag:

```
cmsrel CMSSW_8_0_2
cd CMSSW_8_0_2/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic cms-l1t-offline:l1t-integration-v14.0
git cms-addpkg L1Trigger/L1TCommon
scram b -j 8
```

The change log is here:

   https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev#Development_Integration

to run the officially supported cmsDriver-based version of L1T Re-Emulation:
`cmsDriver.py l1NtupleRECO -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW2015 --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 200 --data --no_exec --no_output --filein=/store/data/Run2015D/DoubleEG/RAW-RECO/ZElectron-PromptReco-v4/000/260/627/00000/12455212-1E85-E511-8913-02163E014472.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`
and then:

```
cmsRun l1NtupleRECO_RAW2DIGI.py
root -q -b -x L1Trigger/L1TCommon/macros/rates.C
root -q -b -x L1Trigger/L1TCommon/macros/kin.C
```

An example re-Emulating from 2016 data:

`cmsDriver.py l1Ntuple -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 200 --data --no_exec --no_output --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs`

You can ignore the error messages from L1Ntuple about missing HCAL and ECAL TPs... its because we are no longer re-emulating these for 2016 (though we will support this soon).

Developer instructions:

Start by checking out a specific tag as above.   If you prefer to simply checkout the HEAD of the development branch, replace the cms-merge-topic line above with `git cms-merge-topic cms-l1t-offline:l1t-integration-CMSSW_8_0_2` but this is not required.

Here is an example work flow that assumes you are working on the "fix-hf1x1" task:

```
> git checkout -b mydevel
> # work work work
> git add <files>
> git commit -m "work work work"
> # repeating as needed...
> git push cms-l1t-offline mydevel:smith-fix-hf1x1-$CMSSW_VERSION 
```

If you wish to collaborate with other, after the initial push, you collaborators can start there own working areas by simply following the recipe above but replacing the cms-merge-topic line with, for example:

```
> git cms-merge-topic cms-l1t-offline:smith-fix-hf1x1-$CMSSW_VERSION 
```

When your code is ready to go back into the integration branch, either:
1) notify mulhearn that your code is ready by posting in this branch and specifying the branch.
2) making a pull request, using github website, of your branch into the l1t-integration branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-integration-CMSSW_8_0_2
Option (2) is a bit fussy, because you have to make sure you select cms-l1t-offline as the repository in the pull down menus.

**Comment by mulhearn** [comment]
The control plots for tag l1t-integration-v7.0-cmssw802 are here:
http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v7.0-cmssw802/
results of an object-level comparison with l1t-tsg-v3 are here:
http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v7.0-cmssw802/diff
There are only minor differences, as expected due to HCAL TP updates.  (Bitwise equivalent results were demonstrated when we rolled back HCAL updates in the release.)  These are a bit hard to interpret for the non-expert at the moment (they are auto-generated from the comparisons.)

**Comment by mulhearn** [comment]
In 802, our MC simulation production sequence works for HF 1x1 TPs.  (In pre6 only the re-emulation sequence works).

**Comment by mulhearn** [comment]
Next step is to forward port the latest tag from pre6, here, which should go more easily.

**Comment by mulhearn** [comment]
All of the instructions on this page have been tested, updated, and now work.  Disclaimer removed!

**Comment by mulhearn** [comment]
The latest and greatest from the pre6 integration branch is now available as tag l1t-integration-v12.0-cmssw802 with control plots here:
http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v12.0-cmssw802/

**Comment by mulhearn** [comment]
@jimbrooke @apana l1t-integration-v13.1-layer1 contains the latest bug-fixes from layer1 folks.  This is based on 802 now, so HCAL TPs are up to date (all minor differences from pre6).  I guess this is likely now the best branch for layer2 development based on layer1 inputs.

**Comment by mulhearn** [comment]
@apana @rekovic l1t-integration-v13.1 is our candidate for l1t-tsg-v4.  Please test!

**Comment by jimbrooke** [comment]
Sigh.  Layer 2 calibration bus left some time ago with v10.  I hope the changes in v13 are not going to affect calibration or seed threshold studies...

**Comment by jimbrooke** [comment]
@gomber What are the changes in v13?  Is v10 buggy ?  We are actively using this code so please keep us in the loop if you fix bugs or make changes.

**Comment by gomber** [comment]
As mentioned in the other mail, we found one small bug in the code related to hcal scale, we were using ecal scale in hcal scale calculation. And I mentioned that to some students of imperial i.e Antoni and Shane. Sorry for not mentioning it to all..

**Comment by SridharaDasu** [comment]
Dear Jim,

Yes, they will be different as the last tag that was introduced
was really buggy.  In the re-write of access I did a cut-and-paste 
and I accidentally replaced "hcal" scale with "ecal" scale.  That
would be most bogus resulting in E instead of ET in some non-linear
scale used for HCAL energies.  I would most certainly not use that.
Bhawna caught that change and fixed it.  Then Nick converted the
usage of the "transcoder".  Whichever bus that left needs to 
make a U-turn.

Regards,
Sridhara

---

Prof. Sridhara Rao Dasu                         Department of Physics
dasu@hep.wisc.edu                             University of Wisconsin
http://www.hep.wisc.edu/~dasu                    4289 Chamberlin Hall
608-262-3678 ( Office )                        1150 University Avenue
408-829-6625 (Wireless)                        Madison, WI 53706, USA

**Comment by apana** [comment]
Hi Mike,

1t-integration-v13.1 looks good to go to me.  It gives identical results to
v12 for all distributions, and my previous test of v12 vs l1t-tsg-v3 showed
the expected changes for muons and taus, and no changes for the other
objects.

-Len

**Comment by rekovic** [comment]
@mulhearn 
1t-integration-v13.1 passes all the L1T unit tests successfully.
1t-integration-v13.1 and 1t-integration-v12.0 cmssw802  are equivalent in L1T rates and L1T object distributions.

Moving to (cmssw_802) from (cmssw_800pre6) introduced small changes,
~ 1% in  Jet triggers and a few percent in L1_DoubleMu_10_3p5.

The comparison of L1T running on 1000 events from Run2015D MuonEG stream is available here
/afs/cern.ch/user/r/rekovic/public/forL1TStage2/l1t-integration/rateComparison_l1t_integraion_v13.1_vs_12.0_cmssw800pre6.log

**Comment by rekovic** [comment]
Moving to (cmssw_802) from (cmssw_800pre6) introduced small changes -> means "drop".

At the moment, I am not sure where this comes from, but we are talking about a handful of paths

<pre>
<       17                             L1_SingleJet68       723    723    723         1          1        0
<       18                           L1_SingleS1Jet92       448    448    448         1          1        0
<       19                            L1_SingleJet128       216    216    216         1          1        0
<       20                          L1_SingleS1Jet176        99     99     99         1          1        0
<       21                          L1_SingleS1Jet200        75     75     75         1          1        0
>       17                             L1_SingleJet68       724    724    724         1          1        0
>       18                           L1_SingleS1Jet92       450    450    450         1          1        0
>       19                            L1_SingleJet128       219    219    219         1          1        0
>       20                          L1_SingleS1Jet176       100    100    100         1          1        0
>       21                          L1_SingleS1Jet200        77     77     77         1          1        0
<       38                         L1_DoubleMu_10_3p5        46     46     46         1          1        0
>       38                         L1_DoubleMu_10_3p5        49     49     49         1          1        0
<      100                  L1_TripleJet_92_76_64_VBF       123    123    123         1          1        0
<      101                  L1_TripleJet_84_68_48_VBF       201    201    201         1          1        0
>      100                  L1_TripleJet_92_76_64_VBF       124    124    124         1          1        0
>      101                  L1_TripleJet_84_68_48_VBF       202    202    202         1          1        0
</pre>

**Comment by rekovic** [comment]
fixed the above https://github.com/cms-l1t-offline/cmssw/issues/189#issuecomment-195937476

**Comment by fwyzard** [comment]
Hi all,
trying to understand reconcile the two set of comments...

The fix in the Layer 1 code does not impact the comparison between `l1-tsg-v3` and `1t-integration-v13.1` because the latter does not use the Layer 1 module by Wisconsin, yet ?

.A

**Comment by rekovic** [comment]
@fwyzard That is correct.

**Comment by apana** [comment]
Hi Andrea,

I'm not sure you're aware, but there is another branch,
1t-integration-v13.1-layer1,
which has the bugfix and has the layer1 emulation turned on. The Stage2
developers are currently using that to update and tune the calo algorithms.

@Vladimir:  I think the small changes in the Jet paths can be attributed to
the HCAL TP updates Mike mentioned at the top of this thread.  Don't know
why double muon changed. I take it all the other muon paths agree?

-Len

**Comment by rekovic** [comment]
@apana Yes. All other muon paths agree except for L1_DoubleMu_10_3p5.

**Comment by fwyzard** [comment]
hi,
sorry, maybe it's completely unrelated, but I just saw #13704 pending for CMSSW 8.0.x about adjusting the LSB for HF 1x1 TPs back to 0.5 GeV .

Will that impact this work?

**Comment by nsmith-** [comment]
@fwyzard Chances are yes, since both layer 1 emulators call function in that class.

**Comment by mulhearn** [comment]
I doubt that will have a noticeable impact.  Once we adapted our event setup for 802, the effect was unnoticeable unless you do a bitwise comparison.

**Comment by mulhearn** [comment]
Added l1t-integration-v14.0 and l1t-integration-v14.0-layer1 which include latest bugfixes from layer1 team (#192).

**Comment by rekovic** [comment]
Rates, and distributions all agree in data and MC bw v14.0 and v13.1.
I confirm that HF jets are there.

**Comment by bortigno** [comment]
@rekovic where can I find the definition of the algorithms you are producing rates with? is it an xml or hardcoded in some analyser? if it is L1Menu_Collisions2015_25nsStage1_v7_uGT_v1.xml then I have a further question: I read that for DoubleMu_10_3p5 the quality requirement is >11. The muon quality adjuster changed between 12.0 and 13.1 2adbc520844fbf42dbee8d9711a958b95f146b6a moving muon high quality from 1 to 12. So how can the DoubleMu_10_3p5 give any rate if it only passes >11? Anyhow the quality changed so maybe this is the source of difference in rate?

**Comment by rekovic** [comment]
@bortigno By the rates here I meant "counts" for each l1 algo.  They are is given as the output of  "L1TSummary" module after running on fixed number of events.

**Comment by thomreis** [comment]
@mulhearn @rekovic the uGMT upgrades and conditions changes are in branch https://github.com/cms-l1t-offline/cmssw/tree/thomreis-uGMT-fixes-CMSSW_8_0_2 ready to be integrated.

**Comment by thomreis** [comment]
@mulhearn you have disabled the packeing of the uGMT RegionalMuonCand with this commit https://github.com/cms-l1t-offline/cmssw/commit/30054b108a51a8e7b3512e4e274e5720681b2d78 
Has this been fixed? Can we uncomment these lines again at some point?

**Comment by thomreis** [comment]
@mulhearn in https://github.com/cms-l1t-offline/cmssw/commit/6433dcb84201ac6a8875359c28584cd3aed01c85 you added instances to the unpacked L1Candidates to use edm::view. For the uGMT emulator we don't have these instances. Should we add them there too? I case yes what needs to be changed so that the consumers code does not break?

**Comment by mulhearn** [comment]
@apana since last night there has been l1t-integration-v14.1 which adds a customization for running bitwise layer1 in parallel... sorry the first version of this comment was not successfully posted...  Here's an example using it:
`cmsDriver.py L1TEST --python_filename=l1t_test.py -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 100 --data --no_exec --no_output --filein=/store/data/Run2015D/MuonEG/RAW/v1/000/256/677/00000/4A874FB5-585D-E511-A3D8-02163E0143B5.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --customise=L1Trigger/Configuration/customiseReEmul.L1TAddBitwiseLayer1Write`

**Comment by thomreis** [comment]
@mulhearn After discussing with Alessandro I have added some changes to https://github.com/cms-l1t-offline/cmssw/tree/thomreis-uGMT-fixes-CMSSW_8_0_2 that should be integrated as well. Essentially, the BX range is removed from the conditions since it will not be in the offline DB.

**Comment by mulhearn** [comment]
l1t-integration-v14.2 is out with bugfixes for calo packing and GT stable params.

**Comment by mulhearn** [comment]
l1t-integration-v15.0-layer1 and l1t-integration-v15.0 are out with latest updates from layer1 team, including the suggested speedup from layer2 team.

**Comment by mulhearn** [comment]
l1t-integration-v16.0 is out with latest updates from GMT.  The diff plots with v15.0 show some differences during re-emulation, that I'd like to discuss with @thomreis:  http://mulhearn.web.cern.ch/mulhearn/plots/l1t-integration-v16.0/diff/

**Comment by thomreis** [comment]
@mulhearn The new automatic BX range determination does not work perfectly yet as it seems. Could you try to set autoBxRange to False in https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-v16.0/L1Trigger/L1TMuon/python/simGmtStage2Digis_cfi.py#L15 and try again?

**Comment by thomreis** [comment]
I have fixed the BX range detection for the uGMT emulator. It now ignores input collections if all the inputs of that collection are masked or disabled. However, since now the smallest BX window of the input collections defines the output range, I expect less muons being found than before when the window was always 5 BX. The changes are in https://github.com/cms-l1t-offline/cmssw/tree/thomreis-uGMT-fixes-CMSSW_8_0_2
In the standard sample of the cmsDriver command the OMTF and EMTF had only BX 0, while BMTF had 5 BX range. In the plots it looks like the you find the same number of BMTF muons and less in the endcaps. This is the opposite of what I was expecting.

**Comment by fwyzard** [comment]
Hi Thomas,
I guess I'm confused... shouldn't the emulator always use only the inputs from BX=0, to produce candidates for BX=0 ?

I mean, it does make sense to emulate the other BX (as long as there is enough information from the track finders), but these candidates should be assigned to the corresponding BX, not to BX=0.

Is this not the case ?

**Comment by thomreis** [comment]
Hi Andrea,
the uGMT does not change BX numbers of the inputs. So what comes in BX -1 stays in BX -1 for example.

The upgrade handles cases where one TF would have a smaller BX range than others (in case that ever happens). In that case the smallest input BX range is the one for the output since it indeed does not make sense to emulate outputs for a BX where some inputs are missing. Previously the output BX range was set to 5 BX in the config file.

**Comment by fwyzard** [comment]
Understood, thanks.

.A

**Comment by jimbrooke** [comment]
"l1t-integration-v15.0 are out with latest updates from layer1" - would it be possible to get a summary of the changes?

**Comment by gomber** [comment]
Here are the changes as mentioned by Sridhara earlier and nothing major.
Restored validator of the emulator using ethernet-caputure events from the spy DAQ.
Also tried to speed up Layer-1. The real speed up was provided by @raggleton - also included in this branch.
Found a minor difference - firmware calculates flag bits using calibrated ETs, and the emulator used uncalibrated. Emulator changed to match the firmware.
@nsmith- fixed HF unpacker caloPhi assignment for highest caloEta bin.

**Comment by rekovic** [comment]
As a reminder, we keep track of integration tags here

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev#Development_Integration

**Comment by rekovic** [comment]
@mulhearn Reverted v35.0 and integrated Tau iso-option-5 LUTS, and tagged l1t-integration-v36.0

v36.0 should be the base for our l1t-tsg-v5.

**Comment by gennai** [comment]
Hi,
stupid question.
Is V36 also including the track timing assignment which was pushed together with the ME1/1a dataformat change in V35p0?

Best,
S.
Il giorno 14 apr 2016, alle ore 18:30, rekovic <notifications@github.com<mailto:notifications@github.com>> ha scritto:

@mulhearnhttps://github.com/mulhearn Reverted v35.0 and integrated Tau iso-option-5 LUTS, and tagged l1t-integration-v36.0

v36.0 should be the base for our l1t-tsg-v5.

**Comment by rekovic** [comment]
@gennai No, v36 does not include track timing assignment.  
The merge leading to v35 was entirely reverted to point to v34, and then tau iso-option-5 LUTs were added.

**Comment by mulhearn** [comment]
Tag l1t-integration-v41.0 is out with the latest fixes from EMTF team from PR #275.

Our quick comparison plots, when quality>=12 is applied, show a dramatic increase in the endcaps, as expected.  Very promising.

<img width="1028" alt="screen shot 2016-04-26 at 6 30 52 pm" src="https://cloud.githubusercontent.com/assets/5119251/14826549/a78cd1dc-0bde-11e6-94b2-5d16b5f90270.png">

**Comment by mulhearn** [comment]
With tag v42.1 we now support unpacking and n-tuplizing 2016 RAW data, as well as re-emulating L1T starting from 2016 RAW data.  This is now the assumed default re-Emulation.  Re-Emulating 2015 data as 2016 trigger is still supported but requires slightly different recipe.

**Comment by mulhearn** [comment]
Recipes above need to be updated...

**Comment by fwyzard** [comment]
> Re-Emulating 2015 data as 2016 trigger is still supported but requires
> slightly different recipe.

I assume it is, but just in case... is the "slightly different recipe"
documented on the twiki ?

.A

**Comment by mulhearn** [comment]
Working on it.

**Comment by mulhearn** [comment]
This integration branch is now closed.  Use #291 instead.
