### ISSUE TITLE
L1TCaloLayer1/BXVector speedup

### ISSUE THREAD

**Issue by raggleton** [cms-l1t-offline/cmssw#193]
When running the emulation chain, the L1TCaloLayer1 module takes a significant amount of time per event. Running with callgrind showed a lot of time spent doing `std::vector::_M_erase` and `_M_insert_aux`. I believe this is during [`BXVector::set()`](https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-v14.0-layer1/L1Trigger/L1TCaloLayer1/plugins/L1TCaloLayer1.cc#L236).

Looking at [ `BXVector::set()`](https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-v14.0-layer1/DataFormats/L1Trigger/interface/BXVector.impl#L227:L228) there is call to `vector::erase()` followed by `vector::insert()`. Both of these cause std::vector to relocate elements, causing significant slowdown.

On the assumption that this is just assigning `object` to a given position in the `data_` vector, I tried replacing those 2 lines with 

```
data_.at(itrs_[indexFromBX(bx)] + i) = object;
```

This massively reduced the run time / event in the Layer1 module (0.765s -> 0.005s). Is there a reason to prefer the erase/insert method? I'm afraid I'm not familiar with the BXVector class or its design.

Thanks,
Robin

**Comment by nsmith-** [comment]
Good point Robin, indeed as written on [C++ Reference](http://www.cplusplus.com/reference/vector/vector/erase/):

> Because vectors use an array as their underlying storage, erasing elements in positions other than the vector end causes the container to relocate all the elements after the segment erased to their new positions. This is generally an inefficient operation compared to the one performed for the same operation by other kinds of sequence containers (such as list or forward_list).

I would vote to remove all use of std::vector::erase() from BXVector, the reallocation of the entire object is incredibly expensive, especially since we have an absolute index hash available to us.

**Comment by mulhearn** [comment]
This is merged in l1t-integration-v15.0-layer1 and onward...
