### ISSUE TITLE
Merge l1t-tsg-v4 into CMSSW

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#199]
Preparing to push l1t-tsg-v4 into CMSSW.

PRs for the data area are:
- https://github.com/cms-data/L1Trigger-L1TCalorimeter/pull/8
- https://github.com/cms-data/L1Trigger-L1TMuon/pull/3
- https://github.com/cms-data/L1Trigger-L1TGlobal/pull/2

The 80X PR is:  cms-sw#13767 (merged)
The 81X PR is:  cms-sw#13768 (merged)

Loosely related DQM updates:
The 80X PR is:  cms-sw#14021 (merged)
The 81X PR is:  cms-sw#13891 (merged)

Still todo:
- Fix reported crashes from IB in 250206.0 (Stopped in recent IBs)

https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-04-12-1100/pyRelValMatrixLogs/run/250206.0_ZMM_13+ZMM_13INPUT+DIGIPRMXUP15_PU25+RECOPRMXUP15_PU25+HARVESTUP15_PU25/step2_ZMM_13+ZMM_13INPUT+DIGIPRMXUP15_PU25+RECOPRMXUP15_PU25+HARVESTUP15_PU25.log
- check bitwise equivalence of 80x with l1t-tsg-v4 as was done for 81x. (DONE)

**Comment by mulhearn** [comment]
@rekovic you are interested in this.

**Comment by Martin-Grunewald** [comment]
@mulhearn 
How do I get the above three cms-data into my developer area? Ie, what is the git command?

**Comment by mulhearn** [comment]
I'll make a separate PR that simply updates your local data area, which we won't merge...

**Comment by mulhearn** [comment]
Or simpler might be to just do:  `git revert 06cccfdb6a680cb76f822714ca4c2117fc503f8f`

**Comment by Martin-Grunewald** [comment]
git revert does the job... thanks!

**Comment by fwyzard** [comment]
here is how you could get the latest .../data files without touching the git history for cmssw (useful if you want to make PR based on your developments later on):

```
git cms-merge-topic 13767
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter.git L1Trigger/L1TCalorimeter/data
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TMuon.git L1Trigger/L1TMuon/data
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TGlobal.git L1Trigger/L1TGlobal/data 
```

**Comment by mulhearn** [comment]
I've been doing some bitwise comparisons.  These are complicated by the fact that the nominal l1t-tsg-v4 tag is in 802, but we are looking in release 804 and 810_pre2.  I found I have bitwise agreement for re-emulation and simulation after merging PR 14021 in 804 if I use the nominal l1t-tsg-v4 recipe plus:
- cherry pick EG packer bug fix:  6364eec7053e349a962606edf762531e82627ebe
- cherry pick Sum packer bug fix:  e7aac534e576e9a7e904706a35e0242df4baf5bb
- use MC tag (as in 804):  80X_mcRun2_asymptotic_v9
- use Menu (as in 804 GT):  L1Menu_Collisions2015_25nsStage1_v7_uGT_v4.xml

So this looks fine.

**Comment by mulhearn** [comment]
Now that all the v4 era PRs are in, completed the last set of bitwise comparisons to make sure we understand everything going on.

Standard of comparison is l1t-tsg-v4 with the adjustments described above.

In CMSSW_8_0_X_2016-04-13-1100 the HLT PR that changes L1 Menu to GT has not been merged yet, so I switch the menu to the one in GT so that I can use the benchmark above.

I get agreement everywhere but in forward jets.

This was assumed to be due to the HCAL PR adjusting the HF 1x1 LUTs, and I confirmed this by reverting their PR:
`git revert -m 1 17ab3e96ef8139dc14098336f20c7f74f4ca5a39`

After this I have perfect bitwise agreement with the l1t-tsg-v4 benchmark.

In the comparison with 81X theres a bit more going on.  In addition to the HF 1x1 changes, an additional PR has turned on emulation of external conditions, so now those algorithm bits are non-zero:

```
<        0                                L1_ZeroBias       100    100    100         1          1        0
<        1                       L1_SingleEG2_BptxAND        99     99     99         1          1        0
---
>        0                                L1_ZeroBias         0      0      0         1          1        0
>        1                       L1_SingleEG2_BptxAND         0      0      0         1          1        0
11c11
<        4                           L1_ETT15_BptxAND        96     96     96         1          1        0
---
>        4                           L1_ETT15_BptxAND         0      0      0         1          1        0
23c23
<       16                            L1_SingleJet128        29     29     29         1          1        0
---
>       16                            L1_SingleJet128        27     27     27         1          1        0
69c69
<       62                  L1_SingleJetC32_NotBptxOR         0      0      0         1          1        0
---
>       62                  L1_SingleJetC32_NotBptxOR       100    100    100         1          1        0
79c79
<       72                  L1_SingleMuOpen_NotBptxOR         0      0      0         1          1        0
---
>       72                  L1_SingleMuOpen_NotBptxOR        59     59     59         1          1        0
95c95
<       88                  L1_SingleJetC20_NotBptxOR         0      0      0         1          1        0
---
>       88                  L1_SingleJetC20_NotBptxOR       100    100    100         1          1        0
```

The single jet trigger difference is the same change seen in 80X before reverting the HF 1x1 PRs.

So all differences understood, and l1t-tsg-v4 has made it cleanly into 80x and 81x.

**Comment by mulhearn** [comment]
I also looked into 250206.0 and could not reproduce the failure.  It has gone away in more recent IBs as well.  David is worried the Endcap muon producer likely has memory corruption problems.  We'll follow this one up in a different thread.

**Comment by mulhearn** [comment]
l1t-tsg-v4 has made it cleanly into 80x and 81x.  This one is closed.
