### ISSUE TITLE
Understanding External Conditions in uGT

### ISSUE THREAD

**Issue by rekovic** [cms-l1t-offline/cmssw#200]
Currently not emulating the External Conditions in uGT.  We unpack them in case they are 
available.  We should commission the External Conditions as the preparation for the beam.
This is meant as a forum for it.

**Comment by rekovic** [comment]
@mulhearn @blwiner @tmatsush @apana @bortigno This interests you.

**Comment by rekovic** [comment]
L1_ZeroBias depends on Bptx External Condition.
When re-emulated L1_ZeroBias running on 2015 DATA, it is always set to 0.  Why?
Indicating that possibly the unpacking of it is broken.  

Here is a quick test, running on 2015 data, that will print out the L1T decisions 

<pre>
#### working with l1t-integration-14.0
cmsDriver.py L1TEST --python_filename=l1t_test.py -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 1000 --data --no_exec --no_output --filein=/store/data/Run2015D/MuonEG/RAW/v1/000/256/677/00000/4A874FB5-585D-E511-A3D8-02163E0143B5.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput
cmsRun l1t_test.py >& l1_test.log
</pre>

**Comment by tmatsush** [comment]
uGT external conditions are unpacked/packed in
https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/EventFilter/L1TRawToDigi/src/implementations_stage2/GTSetup.cc

In order to use external conditions included in 2015 data with the legacy-GT running, the conditions in legacy-GT data need to be mapped to one of the 256bits in GlobalExtBlk of uGT. L1Menu_Collisions2015_25nsStage1_v7_uGT_v4 includes BPTX_plus_AND_minus.v0. The menu is using (arbitrary) mapping and the condition is mapped to  ext_cond_bx_0(8) at the moment. 

cc: @vasile-ghete

**Comment by rekovic** [comment]
Thanks @tmatsush 
@blwiner Are we using ext_cond_bx_0 in the emulation at the moment ?

**Comment by tmatsush** [comment]
@rekovic @blwiner  
ext_cond_bx_0 should be GlobalExtBlk at BX=0.

**Comment by blwiner** [comment]
The emulator uses the external condition mappings as defined in the L1 menu
xml file.  So as long as the GlobalExtBlk is filled following the same
mapping (Takashi pointed out that BPTX is mapped to ext_cond_bx_0(8)) then
the emulator will use it.

-Brian

On Fri, Mar 18, 2016 at 7:07 AM, tmatsush notifications@github.com wrote:

> @rekovic https://github.com/rekovic @blwiner
> https://github.com/blwiner
> 
> ext_cond_bx_0 should be GlobalExtBlk at BX=0.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/200#issuecomment-198309341

## 

---

B. Winer

**Comment by rekovic** [comment]
@blwiner Coming back to this, do we have a working test example for MC that shows working BptxAND ?

**Comment by blwiner** [comment]
@rekovic  a couple of comments:

```
 1) I have tested the external signals by artificially setting bits for
```

external signals and propagating those through the emulation.
     2) These were part of tests that were run through the test stand at
Vienna to compare with the firmware. Those tests passed.
     3) What I think you are asking for is a more permanent solution for
MC.  To me this suggests that we need a producer that sits upstream of the
uGT emulation and creates the external signals for the MC.  But this
prompts some questions: What signals do we want to include?  What
flexibility do we want to have in terms of turning those signals on and
off?  If we just want to turn on certain bits for every MC event that
should be straight forward, but if there is a desire to have a lot of
flexibility things get more challenging.

 -Brian

On Wed, Mar 23, 2016 at 10:45 AM, rekovic notifications@github.com wrote:

> @blwiner https://github.com/blwiner Coming back to this, do we have a
> working test example for MC that shows working BptxAND ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/200#issuecomment-200375696

## 

---

B. Winer

**Comment by rekovic** [comment]
@blwiner  Thanks for the details and the info about  1) and 2).

Regarding 3) and the upstream producer, I think the minimal you
mentioned is to have a certain bit turned on for every MC event.
I imagine the bit is defined by uGT firmware. Wouldn't that be all
we need to emulate simple XXX_BptxAND paths?

Why would we ever want to turn them off?  I am simply asking to
understand.  Would they have any effect unless we have l1algos
that are gated or ORed with it?  And if we do, we should be able
to emulate them in MC. I see from the 'L1TGlobalSummary' that we do
emulate XXX_NotBptxOR paths.

I was thinking if it would be possible to have this up-stream module
be configurable for both MC and DATA so that we can see BptxAND.
For MC it could set the Bptx bit for every event, but for DATA 2015
it would do some mapping Stage-1 to Stage-2 before setting the bit.

The idea is to commission the external condition emulation both
with MC and possibly with 2015 data before beams come.
I could also look into this if you want, but could probably use some
pointers from you guys.

**Comment by blwiner** [comment]
@rekovic  we will look into a simple Producer that fills bits of the
External Conditions.  If we are going to access legacy external conditions
from 2015 data, we are going to need help with that.  I have no idea how to
access that information for the legacy system.  But at least we can get
started on the MC part.

 -Brian

On Wed, Mar 23, 2016 at 11:53 AM, rekovic notifications@github.com wrote:

> @blwiner Thanks for the details and the info about 1) and 2).
> 
> Regarding 3) and the upstream producer, I think the minimal you
> mentioned is to have a certain bit turned on for every MC event.
> I imagine the bit is defined by uGT firmware. Wouldn't that be all
> we need to emulate simple XXX_BptxAND paths?
> 
> Why would we ever want to turn them off? I am simply asking to
> understand. Would they have any effect unless we have l1algos
> that are gated or ORed with it? And if we do, we should be able
> to emulate them in MC. I see from the 'L1TGlobalSummary' that we do
> emulate XXX_NotBptxOR paths.
> 
> I was thinking if it would be possible to have this up-stream module
> be configurable for both MC and DATA so that we can see BptxAND.
> For MC it could set the Bptx bit for every event, but for DATA 2015
> it would do some mapping Stage-1 to Stage-2 before setting the bit.
> 
> The idea is to commission the external condition emulation both
> with MC and possibly with 2015 data before beams come.
> I could also look into this if you want, but could probably use some
> pointers from you guys.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/200#issuecomment-200407116

## 

---

B. Winer

**Comment by fwyzard** [comment]
A comment about a producer for MC

In limit of infinite manpower, one could design a module that gets the information about the bunch structure being simulated (e.g. from the mixing module or some other source), and set the BPTX signals to "true" for the corresponding bx. For example, the 25ns simulation would see BPTX = True for all bunch crossings, while the 50ns simulation would see BPTX = True  only for bx = -2, -, +2, and the simulation without pileup would see BPTX = True only for bx = 0. 

In a more realistic scenario, I think setting BPTX = True either only for bx = 0, or for all bx, would cover the vast majority of the use cases.

**Comment by fwyzard** [comment]
A comment about reading the external conditions from data for the legacy GT.

This is some code I wrote some years ago, following instructions by Manfred:

``` c++
    // read the L1 GT digis from the event
    edm::Handle<L1GlobalTriggerReadoutRecord> handle;
    event.getByToken(token, handle);
    L1GlobalTriggerReadoutRecord const & l1tResults = * handle;

    // select PSB#9 and bunch crossing 0
    const L1GtPsbWord & psb = l1tResults.gtPsbWord(0xbb09, 0);

    // the four 16-bit words psb.bData(1), psb.aData(1), psb.bData(0) and psb.aData(0) yield
    // (in this sequence) the 64 technical trigger bits from most significant to least significant bit
    uint64_t psbTriggerWord = ((uint64_t) psb.bData(1) << 48) |
                              ((uint64_t) psb.aData(1) << 32) |
                              ((uint64_t) psb.bData(0) << 16) |
                              ((uint64_t) psb.aData(0));
```

I guess it can be used or adapted to read the external conditions from the Legacy GT data. Then one would have to extract the right bits, and map them to the external conditions fr the uGT.

**Comment by puigh** [comment]
PR made for module to be tested with MC:
https://github.com/cms-l1t-offline/cmssw/pull/214

With it, one can turn on/off Bptx Plus, Minus, OR, AND, as needed from the configuration file for testing L1 algos with external conditions. Initial testing shows the intended behavior, but it would be great if others could test.

**Comment by puigh** [comment]
PR https://github.com/cms-l1t-offline/cmssw/pull/214 updated to include module for converting legacy external conditions in data to stage 2 uGT GlobalExtBlk.

**Comment by tmatsush** [comment]
As for the BPTX signal mapping for uGT, it turns out that the real situation at P5 is (as opposed to our assumptions);
ch32 := BptxAND, ch33 :=  BptxPlus, ch34 := BptxMinus and ch35 := BptxOR
This mapping will be used for the next update of menus (L1Menu_Collisions2016_dev_vX)
In future, it would be good if the channel numbers of external conditions at uGT inputs be taken from the menu.

**Comment by mulhearn** [comment]
The latest version of the external conditions takes this from the Menu.  This one is closed.

**Comment by fwyzard** [comment]
@mulhearn , do you mean that the mapping is taken by the L1 menu also for the modules that produce
- the external conditions for MC
- the external conditions from 2015 data
  ?

**Comment by blwiner** [comment]
The new code is implemented in both the producer for the MC and the
producer used on the 2015 data.  In both cases it sets/remaps the
appropriate bits for the 2016 L1 Menu.  These bits are determined from the
menu itself.

-Brian

On Fri, Apr 22, 2016 at 3:59 PM, Andrea Bocci notifications@github.com
wrote:

> @mulhearn https://github.com/mulhearn , do you mean that the mapping is
> taken by the L1 menu also for the modules that produce
> - the external conditions for MC
> - the external conditions from 2015 data ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/200#issuecomment-213569832

## 

---

B. Winer

**Comment by fwyzard** [comment]
Thanks !
