### ISSUE TITLE
Request of UTM external library update (80X) 

### ISSUE THREAD

**Issue by tmatsush** [cms-l1t-offline/cmssw#251]
@smuzaffar @mulhearn

Can we update UTM external library in 80X to the tag, r44601-xsd310-patch ,
available on https://gitlab.cern.ch/cms-l1t-utm/utm ?

This is backwards compatible, and we will not be able to emulate
correlation conditions without this update. Also Makefile has been updated
to exit with error code.

**Comment by smuzaffar** [comment]
@iahmad-khan, can you  please take care of it

**Comment by iahmad-khan** [comment]
created 
https://github.com/cms-sw/cmsdist/pull/2254
