### ISSUE TITLE
Revert to option5 for taus iso LUT

### ISSUE THREAD

**Issue by bortigno** [cms-l1t-offline/cmssw#252]
v37.2 has still v21. @davignon

**Comment by fwyzard** [comment]
to give more details: v21 is fine for the startup, but for the MC production we should use v5 by default.

**Comment by davignon** [comment]
Hi Pier and Andrea,

In PR #256, I just asked for Option 5 to be included as default in the caloStage2Params config file for the next l1t-integration next tag.

Cheers,
- Olivier
