### ISSUE TITLE
Layer 2 Unpacker makes towers at ieta 29

### ISSUE THREAD

**Issue by nsmith-** [cms-l1t-offline/cmssw#257]
As I was testing Layer1 data-emulator comparison with my own fix to the layer 2 unpacker (#210) until recently, this went unnoticed.
The fix provided by layer 2 appears to not have fixed the problem however, and as of l1t-tsg-v5, the unpacker creates towers at +/- 29.  It does not make towers at +/-30 and it appears that the towers at 29 should be the ones at 30.

**Comment by fwyzard** [comment]
Hi @nsmith- , as I'm not familiar with this, could you briefly explain what is the effect of this problem ?
Does it affect
- MC simulation ?
- MC re-emulation ?
- unpacking 2016 data ?
- emulation on 2015 or 2016 data ?

.A

**Comment by nsmith-** [comment]
I think Jim should clarify, but I'm pretty sure this affects unpacking 2016 data only

**Comment by jimbrooke** [comment]
I confirm that this can only affect unpacking 2016 data.  The only workflow that uses Layer 2 inputs from unpacker is DQM.

@bundocka and I will look into this.

BTW, you need to @ include me otherwise I will not see issues on github.

**Comment by jimbrooke** [comment]
This is fixed in #278
