### ISSUE TITLE
Porting legacy muon dataformat into upgrade one

### ISSUE THREAD

**Issue by bortigno** [cms-l1t-offline/cmssw#259]
Porting the legacy muon in the MuonBxCollection. The porting will involve only physical quantities - all hardware quantities are set to 0. The final outcome should be able to add a legacy muon collection in the L1Ntuples so we can easily compare performance.

**Comment by bortigno** [comment]
I have done some work on this on my branch https://github.com/bortigno/cmssw/tree/including-legacy-muons-to-stage2
how should I proceed? should I create a branch in the cms-l1t-offline? @rekovic

**Comment by mulhearn** [comment]
Make a PR into the integration branch.

**Comment by bortigno** [comment]
close #270
