### ISSUE TITLE
Using the new O2O 

### ISSUE THREAD

**Issue by eparadas** [cms-l1t-offline/cmssw#262]
Dear all,
for the moment there is a very first version that takes care of the O2O stuff. We (Khristian, Thomas, Giannis and I) kindly ask from all developers to start playing with that, following the instructions below and please in case of any problem, feel free to post a comment.
Let's start!
Under L1TCommon, there are 4 new objects:
- _setting_ -> a class which takes care of each setting parameter (xml tag: param)
- _mask_ -> a class which takes care of each mask information (xml tag: mask, disabled)
- _xmlConfigReader_ -> a class which takes care of the XML file parsing
- _trigSystem_ -> a class which keeps the settings and the masks for the whole system

In order someone to create a trigSystem object properly, needs to do the follow:
1. Define the HW. By calling the method _addProcRole_, one should give as arguments the role and the processor: `void addProcRole(const std::string& role, const std::string& processor)`. This should be called as many times as the processors your system has.
2. Parse the XML files. By calling the method _configureSystem_, one should give as arguments the L1 key and the subsystem name: `void configureSystem(const std::string& l1HltKey, const std::string& subSysName)`. This method will be able to connect to the OMDS and retrieve the XML files. Since this is under development, we ask you to add the XML files manually. To do this, copy all the XML files, under CMSSW_$VERSION/src
   Then, you will need to edit the `L1Trigger/L1TCommon/src/trigSystem.cpp` lines 33 to 35, by adding the name of the top XML file and the key:
   - `_xmlRdr.readDOMFromFile("ugmt_top_config_p5.xml");`
   - `_xmlRdr.buildGlobalDoc("TestKey1");`
   - `_xmlRdr.readContexts("TestKey1", _sysId, *this);`
3. Once the above steps are done, you are ready to call the getters and retrieve the parameters you need. 
   Get/Check methods:
   1. `std::map<std::string, setting> getSettings (const std::string& processor)`
   2. `std::map<std::string, mask> getMasks(const std::string& proccessor)` 
   3. `bool isMasked(const std::string& proccessor, const std::string& id)` 
   4. `bool isProcEnabled(const std::string& proccessor)`
4. Explanation of the above methods:
   1. Returns a map with all the settings of a specific processor. The first element of the map is the id of the setting and the second is a setting object. With the method getValue, of the setting object, one can get the value in the type he prefers. 
      
      **Example**: 
         XML contains: `<param id="caloInputsDisable" type="bool">true</param>`
         Then in your ESProducer you can retrieve the value of the above, by doing:
         `std::map<std::string, l1t::setting> settings = trgSys.getSettings(aProcessor);`
         `disableCaloInputs = settings["disableCaloInputs"].getValue<bool>();`
      
         Some other possible returning methods are:
                                                                                  - `getVector()` which returns a Vector
                                                                                  - `getTableRows()` which returns a Table (xdata::Table in the XML file)
                                                                                  - `getLUT()` which returns a l1t::LUT object
         For these methods please have a look in the `setting.h` in order to call them properly. The getLUT has a few arguments. In order to retrieve a table setting here is an example:
      XML Contains:
      `<param id="regTable" type="table" delimiter="|">`
      `<columns>register_path| register_value</columns>`
                       `<types>string| uint</types>`
                           `<rows>`
                           `<row>payload.run.run_param.open_lut | 0</row>`
                           `</rows>`
                           `</param>`
      Then in your ESProducer you can retrieve the value of the above, by doing:
      `std::vector<l1t::tableRow>  tRow = settings["regTable"].getTableRows();`
      `for(auto it=tRow.begin(); it!=tRow.end(); it++)`
          `{`
            `if (it->getRowValue<std::string>("register_path").find("open_lut") != std::string::npos)`
             `std::cout << "Value is: " << it->getRowValue<bool>("register_value") << std::endl;`
            `}`
   2. Returns a map with all the masked links of a specific processor. The first element of the map is the id of the masked link and the second is a mask object. One can iterate on all the elements of the map and assign the masking to the emulator.
      **Example**: 
         XML contains: `mask id="inputPorts.Rx02"`
         Then in your ESProducer you can retrieve the value of the above, by doing:
         `std::map<std::string, l1t::setting> masks = trgSys.getMasks(aProcessor);`
         `for (auto& it: masks)`
         `std::cout << "Masked port: " << it.second.getId() << std::endl;`
   3. Returns true if the given id corresponds to a masked id. Keep in mind that the id should be as it is in the XML file, i.e. "inputPorts.Rx02".
   4. Returns true if the given processor is not disabled. This will be filled if only the "disable" tag is shown in the XML.

For a better understanding of all the above, you can have a look in the ESProducer of the uGMT `L1Trigger/L1TMuon/plugins/L1TMuonGlobalParamsESProducer.cc`

Cheers,
Vangelis

**Comment by kkotov** [comment]
For the standalone development and tests you can use an example of xml reading/parsing in:
https://github.com/kkotov/l1o2o/blob/master/L1TriggerConfig/Utilities/test/readxml.cpp

Example of integration with the L1T O2O is also available in: 
https://github.com/kkotov/l1o2o/blob/master/L1TriggerConfig/L1TMuonBarrelParamsProducers/src/L1TMuonBarrelParamsOnlineProd.cc#L192-222

The offline subsystem experts should provide something along the lines:
https://github.com/kkotov/l1o2o/blob/master/L1TriggerConfig/L1TMuonBarrelParamsProducers/src/L1TMuonBarrelParamsOnlineProd.cc#L219-220

**Comment by nsmith-** [comment]
Although integer vectors work ok, float vectors seem to not work.
Take this example case:

``` cpp
l1t::setting testSetting("vector:float", "test", "1.23, 1.2222, 1., 1.", "asdf");
auto tmp = testSetting.getVector<float>();
for(auto i : tmp) std::cout << i << std::endl;
```

I get the error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Wrong value format: 1.23, 1.2222, 1., 1.
Aborted (core dumped)
```

**Comment by eparadas** [comment]
Hi,
thanks for testing. Yesterday I noticed also some strange behavior in the grammars so I have redone them. Now I am testing them and I will push the results in an hour or so. I will post a comment here as well.

Thanks,
Vangelis

**Comment by puigh** [comment]
@eparadas We are using our own branch for uGT (l1t-global-CMSSW_8_0_5), but we would like to test our reading xml files for the prescales and masks. Should we get the most recent code from the l1t integration branch (e.g. l1t-integration-CMSSW_8_0_2), or from somewhere else?

**Comment by eparadas** [comment]
Hi all,
we have pushed a new version and you can find it in the branch: 

https://github.com/cms-l1t-offline/cmssw/tree/cms_o2o_devel-CMSSW_8_0_2

This fixes the problem that Nick mentioned earlier. Please let us know if you find something else problematic.
@puigh Please use the one in the branch above because it is the very recent. It shouldn't have problem compiling under 8_0_5

Cheers,
Vangelis

**Comment by eparadas** [comment]
Two new getters were added in the trigSystem class:

```
std::map<std::string, std::string> getProcRole() { return _procRole; };
std::map<std::string, std::vector<std::string> > getRoleProcs() { return _roleProcs; };
```

In that way there is no need for someone to remember all the names of the processors, e.g. in the BMTF there are 12 processors. With the above getters one can iterate on all the processors and retrieve the masks and the settings.

Cheers,
Vangelis

**Comment by fwyzard** [comment]
Unless you have a particular reason, I would advice returning them by `const &` rather than by value.

By the way, the CMSSW convention for data members is to use either a trailing underscore `_`, or a leading `m_` .

A leading underscore followed by a lowercase letter is allowed for a data member by the C++ standard, but it might be confusing (a double underscore is reserved,  leading underscore followed by a uppercase letter is reserved, a leading underscore followed by a lowercase letter is reserved in the global namespace).

**Comment by eparadas** [comment]
@fwyzard Thanks for the suggestions. Already pushed.

Cheers,
Vangelis

**Comment by mulhearn** [comment]
New 807 based 020 dev branch is almost ready.  @puigh I think I know where your crash is coming from.  I guess maybe you saw:

```
cmsRun: /afs/cern.ch/work/m/mulhearn/trigger/o2o/CMSSW_8_0_7/src/L1Trigger/L1TCommon/src/XmlConfigReader.cc:120: void l1t::XmlConfigReader::readDOMFromFile(const string&): Assertion `doc_' failed.
```

**Comment by puigh** [comment]
My crash was different. It was due to one missing piece on my side and required one fix from the experts that was already pushed up yesterday. It's working now in the standalone code, and I'm putting it in the producer. Once you have the new branch, I will migrate my progress there.

**Comment by mulhearn** [comment]
Can you send me the relevant commits in your dev branch?  I'd like to handle this merge myself.

**Comment by eparadas** [comment]
Hi,
we created a branch for the 8_0_7 and you can find it at:
https://github.com/cms-l1t-offline/cmssw/tree/cms_o2o_devel-CMSSW_8_0_7

Also, it contains the latest changes we 've added. These changes are also committed to the branch for the 8_0_2. We kindly ask from all the developers to check out the latest changes.

Cheers,
Vangelis

**Comment by mulhearn** [comment]
Deleted above comment to avoid confusion.  The branch from @eparadas is deprecated.  

This issue is now superseded by #298.

**Comment by mulhearn** [comment]
Closing this issue.
