### ISSUE TITLE
Offline tau broken in L1Ntuples on 2016 data

### ISSUE THREAD

**Issue by jimbrooke** [cms-l1t-offline/cmssw#286]
Running the L1NtupleAOD_cff on 2016 data results in missing product errors from the l1TauRecoTree producer
----- Begin Fatal Exception 02-May-2016 19:24:16 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing run: 271336 lumi: 15 event: 10374326
   [1] Running path 'l1ntupleaod'
   [2] Calling event method for module L1TauRecoTreeProducer/'l1TauRecoTree'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PFTauDiscriminator
Looking for module label: hpsPFTauDiscriminationByTightIsolation
Looking for productInstanceName: 

Commenting out the l1TauRecoTree allows the job to run, with all other reco quantities in the output as expected.

@davignon  might know how to fix this ?  (But note that it would be desirable to have solutions for both 2015 and 2016 data...!)

**Comment by gennai** [comment]
Hi Jim,
do you have a file at hand?
If so could you post the output of the edmDumpEventContent command on that file?

Best,
S.
Il giorno 02 mag 2016, alle ore 19:25, Jim B <notifications@github.com<mailto:notifications@github.com>> ha scritto:

Running the L1NtupleAOD_cff on 2016 data results in missing product errors from the l1TauRecoTree producer
----- Begin Fatal Exception 02-May-2016 19:24:16 CEST-----------------------
An exception of category 'ProductNotFound' occurred while
[0] Processing run: 271336 lumi: 15 event: 10374326
[1] Running path 'l1ntupleaod'
[2] Calling event method for module L1TauRecoTreeProducer/'l1TauRecoTree'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: reco::PFTauDiscriminator
Looking for module label: hpsPFTauDiscriminationByTightIsolation
Looking for productInstanceName:

Commenting out the l1TauRecoTree allows the job to run, with all other reco quantities in the output as expected.

@davignonhttps://github.com/davignon might know how to fix this ? (But note that it would be desirable to have solutions for both 2015 and 2016 data...!)

**Comment by davignon** [comment]
@gennai @jimbrooke 
I'm having a look, thanks for the heads up

**Comment by davignon** [comment]
@gennai @jimbrooke 
I found the difference. In the new 2016 RECO samples:
hpsPFTauDiscriminationByTightIsolation  --> hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits
This affects a certain number of ID/iso/anti-e/anti-mu flags, not only the Tight tau ID one.
I'm going to create a specific config file for recoTaus in 2016. Should I make it the default? (or not just yet?)

Cheers,
- Olivier

**Comment by gennai** [comment]
Hi,
I would use what is the default in 2016 RECO samples, which seems to be :

hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits

just my two cents.

S.
Il giorno 09 mag 2016, alle ore 15:13, davignon <notifications@github.com<mailto:notifications@github.com>> ha scritto:

@gennaihttps://github.com/gennai @jimbrookehttps://github.com/jimbrooke
I found the difference. In the new 2016 RECO samples:
hpsPFTauDiscriminationByTightIsolation --> hpsPFTauDiscriminationByTightCombinedIsolationDBSumPtCorr3Hits
This affects a certain number of ID/iso/anti-e/anti-mu flags, not only the Tight tau ID one.
I'm going to create a specific config file for recoTaus in 2016. Should I make it the default? (or not just yet?)

Cheers,
-   Olivier

**Comment by davignon** [comment]
@gennai 

OK thanks. So then I make another config file for 2015 and keep the default one with the 2016 ID flag names.

**Comment by rmanzoni** [comment]
as far as "do we really use this in the real world" is concerned, I think this is outdated
`hpsPFTauDiscriminationByTightIsolation`
and indeed it's been dropped in recent CMSSW releases.

You can move altogether to `hpsPFTauDiscriminationBy*CombinedIsolationDBSumPtCorr3Hits`

**Comment by davignon** [comment]
@jimbrooke @gennai @rmanzoni 
It will be solved after PR #310 is implemented.

**Comment by aloeliger** [comment]
Closed according to laurent
