### ISSUE TITLE
Request of UTM external library update

### ISSUE THREAD

**Issue by tmatsush** [cms-l1t-offline/cmssw#300]
@smuzaffar @mulhearn @blwiner @puigh 

Can we update UTM external library to the tag, r45210-xsd310-patch,
available on https://gitlab.cern.ch/cms-l1t-utm/utm ?

This is backwards compatible, and this tag is needed to introduce minimum bias triggers for low-PU run.
[ https://github.com/cms-l1t-offline/cmssw/pull/295 ]

**Comment by smuzaffar** [comment]
I have created a PR for 81X. I guess you want it in 80X too ...... right?

**Comment by fwyzard** [comment]
On 6 May 2016 at 09:47, Malik Shahzad Muzaffar notifications@github.com
wrote:

> I have created a PR for 81X. I guess you want it in 80X too ...... right?

Yep.

Thanks,
.Andrea

## 

Strategy is a system of expedients.

Field Marshall Helmuth Carl Bernard Graf von Moltke

**Comment by smuzaffar** [comment]
tonight's 23h00 81X IB will have new UTM.
I will update it in 80X once tests in 81X passed
