### ISSUE TITLE
Problems with HLT Seeds in Actual Running

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#303]
During weekend running, problems were found with HLT L1 seeds, tracked to a problem with indexing in the BX vector.  Since the L1REPACK re-emulation sequences only include BX=0, this was not detected by HLT tests until running on the actual 2016 data, because the index is correct if only BX=0 is included in the collections.

The culprit is a difference in reference point assumed by the GT emulation and the HLT seeds filter respectively.  After some discussion, it was decided that GT emulation should remain as is, and HLT seeds filter should adapt.
- Mike is working on the local testing sequence (DONE).
- Vladimir is working on the fix

**Comment by mulhearn** [comment]
The new test sequence is provided by this commit 011a2499f879eb6abdcb0d5a4d1468a4cbd5bfcb.

To exercise on 2016 data, use this cmsDriver command:
`cmsDriver.py L1TEST --python_filename=l1t_test.py --conditions=80X_dataRun2_v13 -s RAW2DIGI -n 100 --era=Run2_2016 --data --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --no_output --no_exec --customise=L1Trigger/Configuration/customiseHlt.L1TTestHLTSeeds`

**Comment by mulhearn** [comment]
@rekovic here is your sequence for testing.

**Comment by rekovic** [comment]
PR #14414 and #14415 in place for 80x and 81x respectively.

**Comment by fwyzard** [comment]
If I understand correctly the fixes, the problem was in the building of the edm::Refs .
So, if we have different code accessing the candidates directly, it should be fine, as long as it takes the same possibility (that the first element is not necessarily from bx 0) into account, right ?

**Comment by rekovic** [comment]
@fwyzard  That is correct.

**Comment by fwyzard** [comment]
Thanks.

The muon code ([here](https://cmssdt.cern.ch/lxr/source/HLTrigger/Muon/src/HLTMuonL1TFilter.cc#0123)) is doing

``` c++
MuonRef muon(allMuons, distance(allMuons->begin(allMuons->getFirstBX()),it) );
```

I _think_ it looks correct, but could you cross-check it ?

**Comment by rekovic** [comment]
@fwyzard Yes, it is correct. The code ([here](https://cmssdt.cern.ch/lxr/source/HLTrigger/Muon/src/HLTMuonL1TFilter.cc#0123)) will pick up all the muons in bx = 0.

**Comment by mulhearn** [comment]
That should work fine, but note that `allMuons->begin()` is equivalent to `allMuons->begin(allMuons->getFirstBX())`.
