### ISSUE TITLE
Extrapolation of reco muon phi 

### ISSUE THREAD

**Issue by bortigno** [cms-l1t-offline/cmssw#357]
It would be also nice to have the reco muon phi at the same position as
the L1 muon. This should be the second muon station by convention,
although I don't know exactly how this is handled in the OMTF region.

**Comment by akalinow** [comment]
OMTF reports phi state at the DT station 2.

**Comment by abrinke1** [comment]
EMTF reports phi at CSC station 2, or station 3 if there is no station 2
LCT, or station 4 if there are no station 2 or 3 LCTs.

On Fri, Jun 17, 2016 at 11:09 AM, Artur Kalinowski <notifications@github.com

**Comment by thomreis** [comment]
Extrapolated eta and phi variables at 1st and 2nd station are introduced with PR #422.

**Comment by thomreis** [comment]
This is in integration tag 87.1
