### ISSUE TITLE
ntuples success rate 10%

### ISSUE THREAD

**Issue by bortigno** [cms-l1t-offline/cmssw#394]
Tuples in v73 and later are crashing in crab 90% of the time with a 139 error code. Here an example of log:
/afs/cern.ch/user/b/bortigno/public/forVlad/

**Comment by mulhearn** [comment]
Adding a few loosely related things after discussing with Pier:
- Need to merge #392 into dev branch
- Need a working 8_0_10 dev branch, for recent data.
- Need a special tag or recipe with v73.0 plus custom added for l1t-integration-v76.1 that adds `--customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAWsimHcalTP`

**Comment by mulhearn** [comment]
Adding that the switch to using EMTF unpacked inputs is needed urgently now, as online would like to take CSCTF offline:
- The PR is #391
- Just need to check that this makes the changes everywhere needed.

**Comment by mulhearn** [comment]
Also check on status of L1T ntuple code PRs and legacy muon PR.

**Comment by bortigno** [comment]
related to your second point see #395 - I think it would be better to have a 8_0_14 integration branch as we are taking data with that one

**Comment by bortigno** [comment]
running Tuples in 8_0_16 with #395 solution from Andrea I have a 90% success rates on the Express stream (only unpacked). I launched now in the same area a production of ntuples re-emulated to see if porting the code to 8_0_16 could fix the issue.

**Comment by bortigno** [comment]
Results from my test: adding the re-emulation sequence to the jobs create a failing rate of 85% on the very same dataset where unpack-only jobs were 90% successful. Error code is always the same (139).

**Comment by mulhearn** [comment]
This one is fixed with tag v78.0.
