### ISSUE TITLE
[PR tracking] for RCT unpacker and DQM

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#40]
Track the following until merged with CMSSW:
76X PR cms-sw#10882 is merged (since CMSSSW_7_6_0_pre6)
75X PR cms-sw#10881 is merged.
74X PR cms-sw#10880 is tested and signed, but rejected by ORP due to impending obsolescence of 74X.

**Comment by mulhearn** [comment]
@nsmith- you can track progress here...  we'll need to wait for relval rsults in 76X before it will be allowed in 75X/74X.

**Comment by mulhearn** [comment]
Included in ORP request here:  #67

**Comment by mulhearn** [comment]
@nsmith-  David (offline coordinator) has merged this into 75X, but is resistant to put this is 74X.  DQM is already using this in their own patch, and use cases for 74X are dwindling.  Do you have any objection to leaving this out of 74X or do I need to push back on this?

**Comment by nsmith-** [comment]
I think that's ok, as long as the DQM patch sticks around
I assume DQM is moving to 75X for HI running?

btw it's `nsmith-`

**Comment by mulhearn** [comment]
I think nsmith must hate you ;-)

**Comment by mulhearn** [comment]
Just to be certain, I emailed Jingyu as well.

**Comment by mulhearn** [comment]
Jingyu says it is OK, as long as 74X PR is left open.

**Comment by mulhearn** [comment]
Looks like this one is closed.
