### ISSUE TITLE
L1T muons vtx extrapolated coordinates

### ISSUE THREAD

**Issue by rekovic** [cms-l1t-offline/cmssw#476]
uGMT
===
Since tag **l1t-integration-v92.0**, uGMT emulator  provides additional muon eta/phi variables, which are extrapolated to the Vtx.
  - hwEtaAtVtx
  - hwPhiAtVtx
  - etaAtVtx
  - phiAtVtx

Muon packer and unpackers are adjusted appropriately. 
(for details see merged PR https://github.com/cms-l1t-offline/cmssw/pull/456).

uGT
===
We need the uGT emulator adjusted to take advantage of the new coordinates and improve invMass algorithm.  If it remains as is, it will continue to use non-extrapolated muon coordinates. (@apana )

p.s.
PR of current l1t-integration branch to central CMSSW is planned for this week.

**Comment by rekovic** [comment]
Available change in uGT emulator to use uGMT muons vtx-extrapolated coordinates. PR #490.
Merged and tagged as l1t-integration-v92.12.

**Comment by thomreis** [comment]
@rekovic can we close this?

**Comment by thomreis** [comment]
Closing this.
