### ISSUE TITLE
Add GEM in EMTF

### ISSUE THREAD

**Issue by dildick** [cms-l1t-offline/cmssw#499]
I had a quick look at how RPC is integrated in the EMTF. I blindly copy-pasted (with slight modifications) to get GEMPadDigis integrated in the EMTF. Here is what I have so far https://github.com/cms-sw/cmssw/compare/master...dildick:from-CMSSW_9_1_0_pre2-add-GEM-EMTF?expand=1
 
Please let me know what is missing. 

@tahuang1991 @abrinke1 @jiafulow

**Comment by thomreis** [comment]
Hi Sven,
the EMTF emulator should be replaced by a completely rewritten emulator soon. The current version can be found here https://github.com/abrinke1/cmssw/tree/EMTF_March_2017 .
Perhaps you could get in touch with @abrinke1 and @jiafulow for details about this.

**Comment by dildick** [comment]
@abrinke1 @jiafulow please let me know of your plans and timeline. I need (1) start adding GEMPadDigis to the EMTF (2) extend the BMTF/OMTF/EMTF with classes that do pT assignment for displaced muons. See also #491

**Comment by jiafulow** [comment]
Hi Sven,

As Thomas mentioned, we are in the process of putting the new emulator in place. We hope to get it done within the next two weeks, if there is no additional hold up.

Jia Fu
