### ISSUE TITLE
Make EMTFTrack functions const

### ISSUE THREAD

**Issue by dildick** [cms-l1t-offline/cmssw#514]
These functions should be made const IMO

https://github.com/cms-sw/cmssw/blob/09c3fce6626f70fd04223e7dacebf0b485f73f54/DataFormats/L1TMuon/interface/EMTFTrack.h#L43-L44
i.e.
<PRE>
EMTFHitCollection Hits() const { return _Hits; }
std::vector<uint> HitIndices() const { return _HitIndices; }
</PRE>

**Comment by jiafulow** [comment]
Hi Sven,

As Andrew mentioned, we are replacing the EMTF emulator in CMSSW. The data formats are also updated in the process. I just checked that the above functions are const in the new emulator.

https://github.com/abrinke1/cmssw/blob/EMTF_March_2017/DataFormats/L1TMuon/interface/EMTFTrack.h#L61-L62

Meanwhile, if you are working with the old emulator, feel free to change those functions to const. The new emulator should be integrated very soon.

Best,
Jia Fu

**Comment by dildick** [comment]
Ok. See https://github.com/cms-sw/cmssw/pull/18469
