### ISSUE TITLE
Problems with l1t-integration-v95.5 and later

### ISSUE THREAD

**Issue by rekovic** [cms-l1t-offline/cmssw#562]
Hi,

This is a WARNING.
Attn @bundocka, @apana

We observed a problem with tag `l1t-integration-v95.5` crashing at some events. 
Recipe:

<pre>
cmsDriver.py --python_filename=l1t_test_v95.5_MuonInputFile.py -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --conditions=92X_dataRun2_Prompt_v4 -n 30 --data --no_exec --no_output --filein=/store/data/Run2016H/SingleMuon/RAW-RECO/ZMu-PromptReco-v3/000/284/036/00000/14EE7A3D-639F-E611-81EE-02163E013441.root
sed -i "32i process.source.skipEvents = cms.untracked.uint32(1300)" l1t_test_v95.5.py
cmsRun l1t_test_v95.5.py
</pre>

Error message comming from uGT emulation (apparetnly nothing to do with changes introducded in v95.5.

<pre>
Begin processing the 29th record. Run 284036, Event 359759690, LumiSection 206 at 08-Jun-2017 15:58:52.506 CEST
----- Begin Fatal Exception 08-Jun-2017 15:58:52 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 284036 lumi: 206 event: 359759690 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TGlobalProducer/'simGtStage2Digis'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 18446744073709551612) >= this->size() (which is 256)
----- End Fatal Exception -------------------------------------------------
</pre>

Will revert changes introduced in v95.5 and publish a new tag.

**Comment by rekovic** [comment]
This is now fixed with a new tag v95.11

`l1t-integration-v95.11` - Revert tag v95.5 that was causing a crash in uGT emulator.

**Comment by rekovic** [comment]
@fwyzard 
I would imagine that for the HLT development, TSG would want an equivalent in terms of Calo calibrations to what were tags `v95.7` (old HF SF)  and `v95.8` (new HF SF, no longer divided by 0.7). 

The new analogous tags are
 -  `v95.11.7` (was `v95.7`)
 -  `v95.11.8` (was `v95.8`)

**Comment by fwyzard** [comment]
Thanks, I will update the google doc

**Comment by rekovic** [comment]
OK.  Thanks.

**Comment by fwyzard** [comment]
Mhm, yesterday we were told to use
  - l1t-integration-v95.8 (CaloParams_v1_7) to run on old MC with the 0.7 factor in HF
  - l1t-integration-v95.9 (CaloParams_v1_8) to run on new MC and data without the 0.7 factor in HF

I can change 95.8 to 95.11.8 - but what about 95.9 ?

**Comment by rekovic** [comment]
Correct. So the right analogy is 

 -  `v95.11.7` (was `v95.8`)
 -  `v95.11.8` (was `v95.9`)

sorry for the spam.

**Comment by rekovic** [comment]
my attempt to have the same last digits failed :(
