### ISSUE TITLE
[PR Tracking] Initial Commits for 2016 Muon Emulation

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#58]
Only intended for 76X:
- PR cms-sw#11504 includes MicroGMT and needed DataFormats
- EventFilter PR still needed.

TrackFinder code is not yet ready for primetime.

**Comment by thomreis** [comment]
Hi Mike,

looking at the file names for the MicroGMT it seems strange that they all still have L1T as a prefix. Joschka has fixed that already some time ago. Which branch did you use? Or did I miss something?

Cheers,
Thomas

**Comment by jlingema** [comment]
Hi Thomas, Mike,

I only changed the names of the DataFormats. The L1T prefix was added by Mike only to the plugins, so I guess that's yet another naming convention we didn't follow :)

Cheers,
Joschka

**Comment by thomreis** [comment]
I read the minutes again and found it there. Sorry for the false alarm.

**Comment by mulhearn** [comment]
Yeah, the plugins don't work well with namespaces, so we put it in the name.   Same for CondFormat/DataRecords...

**Comment by mulhearn** [comment]
This one is done.
