### ISSUE TITLE
[PR Tracking] Emulator Bug Fixes for Rare Overflows

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#61]
Tracking the following PRs:

76X: https://github.com/cms-sw/cmssw/pull/11676 is merged since CMSSW_7_6_0_pre7
75X: https://github.com/cms-sw/cmssw/pull/11677 (Merged)
74X: https://github.com/cms-sw/cmssw/pull/11678

**Comment by harmonicoscillator** [comment]
The 75X and 74X PRs will depend on your issue #48

**Comment by mulhearn** [comment]
Those are just waiting for relvals before the backports are admitted.  I'll check the status.

**Comment by mulhearn** [comment]
This only made pre7, I doubt the relvals are ready.

**Comment by mulhearn** [comment]
Merged in all but 74X, so closing this issue.
