### ISSUE TITLE
[PR Tracking] Updates for Stage-2 Unpacking and Algorithms

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#62]
Tracking the PR for Stage 2 unpacking:

   76X:  cms-sw#11866 (tests underway)

Tracking the PR for Stage 2 algorithm updates:

  76X:  cms-sw#11867 (tests underway)

Do we need back ports to 74X/75X?  I guess maybe no?

**Comment by mulhearn** [comment]
@blwiner @jimbrooke lets track this issue here.  Jim, is the stage 2 calo unpacker update ready for prime time?

**Comment by jimbrooke** [comment]
Apologies for missing this when it was created.  I'm not sure if there are still changes anticipated for uGT, but the stage 2 calo unpacker is now ready for prime time (although still not included in any standard workflow).  See PR 11853.

**Comment by mulhearn** [comment]
Why is #11853 closed?

**Comment by jimbrooke** [comment]
Because apparently there are conflicts and I couldn’t figure out why…  Didn’t want to leave it open until/unless I knew you were able to take a look.  I will repoen it.

**Comment by jimbrooke** [comment]
Also because it pulls in L1Trigger/L1TNtuples after I managed to add to the branch unintentionally.  Sigh.

On 18 Oct 2015, at 20:41, Jim Brooke <Jim.Brooke@cern.ch<mailto:Jim.Brooke@cern.ch>> wrote:

Because apparently there are conflicts and I couldn’t figure out why…  Didn’t want to leave it open until/unless I knew you were able to take a look.  I will repoen it.

On 18 Oct 2015, at 20:35, mulhearn <notifications@github.com<mailto:notifications@github.com>> wrote:

Why is #11853https://github.com/cms-sw/cmssw/pull/11853 closed?

**Comment by mulhearn** [comment]
OK, I have fixed the PR for the Stage 2 unpacker.  Does this include everything needed for GT unpacking as well?  PR is here:  cms-sw#11866

**Comment by mulhearn** [comment]
OK, both unpacker and alg update PRs are being tracked here.  @jimbrooke, @blwiner can you confirm that this has all your latest and greatest?

**Comment by blwiner** [comment]
Mike,

   This does not appear to have the the latest changes for the uGT
unpackers.  These were put on the l1t-devel branch, which was for unpacker
development.  However, at some point the stage2 calo unpacker development
got moved to a different branch.  The latest changes to the uGT unpacker
did not get moved to that new branch.   What can we do about this?

 -Brian

On Sun, Oct 18, 2015 at 6:23 PM, mulhearn notifications@github.com wrote:

> OK, both unpacker and alg update PRs are being tracked here. @jimbrooke
> https://github.com/jimbrooke, @blwiner https://github.com/blwiner can
> you confirm that this has all your latest and greatest?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/62#issuecomment-149056282
> .

## 

---

B. Winer

**Comment by mulhearn** [comment]
To include uGT changes I also need to add these commits:
  7f641f4ec73a5b1e58eff80081d8ec392fdcad6e
  2e747e3f5101f01f6d6b570c412f9dc4e3249661
  1d7de8d8ed04a219a69ac7b82395449b939442ba
  6fa81db31b02bed7b7232d92e5ada517d62d108f

**Comment by mulhearn** [comment]
@jimbrooke can you update this thread once you define a new development branch and I'll add in these uGT unpacker changes?

**Comment by mulhearn** [comment]
Noting that after discussion with David, these updates will target 80X instead of 76X.  But don't worry, work on 76X, this only effects the PR.

**Comment by jimbrooke** [comment]
The new unpacker dev branch is l1t-s2unpacker-CMSSW_7_6_0_pre7.  I believe I pulled all the latest uGT changes.  @blwinerhttps://github.com/blwiner can you check this ?

**Comment by mulhearn** [comment]
I can check and add as needed...

**Comment by mulhearn** [comment]
@jimbrooke something went totally wrong with that branch.  It seems it is missing almost all of CMSSW... GITTTTT!!!!!!

See:  https://github.com/cms-l1t-offline/cmssw/tree/l1t-s2unpacker-CMSSW_7_6_0_pre7

**Comment by mulhearn** [comment]
Have to drop this for now, but I can help sort out next week.

**Comment by jimbrooke** [comment]
Sigh.  Fixed now.  https://github.com/cms-l1t-offline/cmssw/tree/l1t-s2unpacker-CMSSW_7_6_0_pre7

**Comment by mulhearn** [comment]
This was pushed back to 80X.   Closing this issue.
