### ISSUE TITLE
[TODO]  Add a Stage 2 era for 2016 

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#65]
We need to add a Stage-2 Era to the Era customization for the 2016 L1 trigger configuration.  Mark Grimes (mark-grimes) is the contact person.  He's not in cms-l1t-offline so I can't evidently ping him directly here...

**Comment by mark-grimes** [comment]
The auto-complete won't work but I'm pretty sure you can ping any github user from any repository/organisation.

I've added an entry to this weeks ORP meeting agenda.  Once that's discussed I can put in a pull request.

**Comment by mark-grimes** [comment]
I have a branch ready for the sub-era `stage2L1Trigger` here: https://github.com/cms-sw/cmssw/compare/cms-sw:CMSSW_7_6_X...mark-grimes:addStage2L1TriggerEra.  This is what you would use to apply the customisations in your config files; I see no reason why this won't be approved.

For the user-level era (i.e. what the user selects, which will be composed of `stage2L1Trigger` and whatever other components), there will need to be discussion at the ORP.  I presume you want to keep all of the current ones (`Run2_25ns`, `Run2_50ns` and `Run2_HI`) and add at least one other?  What permutations of the other components do you need?

**Comment by mark-grimes** [comment]
This was discussed in the 20/Oct/2015 release planning meeting, and I've put in cms-sw/cmssw/#12023 for 8_0_X.  The top-level era is named `Run2_2016`, and as mentioned the stage 2 specific part is `stage2L1Trigger`.  So once that PR is merged:

When calling cmsDriver.py use `Run2_2016`, i.e.

``` bash
cmsDriver.py --era Run2_2016 <other commands>
```

When configuring in your python files, use `stage2L1Trigger`, e.g.

``` python
from Configuration.StandardSequences.Eras import eras

triggerThing = cms.ESProducer("SomeTriggerProducer",
   parameter = cms.string("Run1Value")
 )
eras.stage2L1Trigger.toModify( triggerThing, parameter=cms.string("ValueForStage2Trigger") )
```

There are other ways of making the changes, see https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCmsDriverEras.

`Run2_2016` is assumed to be 25 ns; its components are `run2_common`, `run2_25ns_specific` and `stage2L1Trigger`.  If you need the era in other releases let me know.

**Comment by mulhearn** [comment]
This one is done.
