### ISSUE TITLE
[TODO] Prepare Stage-2 PRs

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#66]
@jimbrooke has a few branches that include additional (not wanted for CMSSW) changes.  Helping to extract these for PRs here.

**Comment by mulhearn** [comment]
Needed changes are:  

1) https://github.com/cms-l1t-offline/cmssw/tree/l1t-calol2unpacker-CMSSW_7_6_0_pre2
but without the inadvertent inclusion of L1TNtuples.

2) https://github.com/cms-l1t-offline/cmssw/tree/l1t-stage2eg-CMSSW_7_5_0_pre5
but only the stuff in L1Trigger/L1TCalorimeter.

I'll fix this here and record the procedure for future reference.

**Comment by jimbrooke** [comment]
1) is the wrong branch, it should be l1t-calol2unpacker-CMSSW_7_6_0_pre2

**Comment by mulhearn** [comment]
Yeah, I noticed when I got 8 million conflicts... Its fixed.

**Comment by mulhearn** [comment]
Here's the procedure I used for fixing (1):

```
cmsrel CMSSW_7_6_0_pre2
cd CMSSW_7_6_0_pre2/src/
cmsenv
git cms-init
git history
```

Note for future use, the most recent commit at top of the output, in
this case 37107a0dcf52a03e1034b35fe974b61d5e41d869.  Now merge in
the branch with needed changes + unneeded changes.

```
git cms-merge-topic cms-l1t-offline:l1t-stage2unpacker-CMSSW_7_6_0_pre2
```

Now the trick is to reset the head using soft option to the original
commit.  The soft option means keep all the changes in your local
area, but reset the HEAD to the original commit.  Now all changes
relative to that original commit will be seen as uncommited changes:

```
git reset --soft 37107a0dcf52a03e1034b35fe974b61d5e41d869
git status
   # On branch from-CMSSW_7_6_0_pre2
   # Changes to be committed:
   #   (use "git reset HEAD <file>..." to unstage)
   #
   #    modified:   Configuration/StandardSequences/python/RawToDigi_Data_cff.py
   #    modified:   Configuration/StandardSequences/python/RawToDigi_cff.py
   #    new file:   EventFilter/L1TRawToDigi/data/mp7_central_buffer.txt
   ...
   #    new file:   L1Trigger/L1TNtuples/.gitignore
   #     new file:   L1Trigger/L1TNtuples/BuildFile.xml
   #     new file:   L1Trigger/L1TNtuples/README.md
   #     new file:   L1Trigger/L1TNtuples/interface/L1AnalysisCSCTF.h
```

This includes the changes we want in EventFilter, but also ones we
don't in L1Trigger/L1TNtuples.  Since these don't exist in the HEAD,
simply blow them away:

```
git reset HEAD L1Trigger/L1TNtuples
rm -fr L1Trigger/L1TNtuples
```

(If they did exist in the HEAD, but different then you have it,
something like "git checkout HEAD L1Trigger/L1TNtuple" would have
worked instead)

Now git status shows all is good:

```
git status
(only wanted changes)
```

So now simply steal your co-workers hard-worked commits into one single commit of your own:

```
git commit -m "udpates to stage2 unpacking, collapsed from Jim B et al."
git push cms-l1t-offline from-CMSSW_7_6_0_pre2:pr-stage2unpacker-76x
```

Note the use of a NEW branch.  This will make sure that no one gets
hurt too badly by collapsing these commits (changing history).  They'll
simply see this as a new commit on a new branch that just happens to
change exactly the same thing as a whole bunch of other commits.

**Comment by mulhearn** [comment]
There are conflict in this branch when merging with latest 76X.  I'll fix those separately.

**Comment by mulhearn** [comment]
OK, the PR for stage 2 unpacking is here:  cms-sw#11866

**Comment by mulhearn** [comment]
The PR for stage 2 alg updates is here:  cms-sw#11867

**Comment by mulhearn** [comment]
This one is done!
