### ISSUE TITLE
L1 uGT O2O for 2016 Run

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#71]
For the 80X deadline:
- Brian and Darren to continue developing emulator to use new grammar.
- Takashi to provide updated library with data / logic separated, in preparation for O2O.
- Mike to handle switch to using CondFormats once updated library available

**Comment by mulhearn** [comment]
@blwiner let's track this issue here.

**Comment by mulhearn** [comment]
Requested a meeting next week when Takashi is reportedly at CERN.

**Comment by mulhearn** [comment]
Substantial progress on this one.  We'll use the online tool for generating xml from the online database.  Then we'll use the uGT xml library to interpret that xml as classes.  Then those classes are simply cast as CondFormat classes.

**Comment by mulhearn** [comment]
Takashi Provides a more detailed study:

Hi Mike, Khristian

I just try to summarise the discussion we had today on uGT O2O.
What we agreed is not to duplicate works but use xml file as a single source of information, even for O2O.

The details are the followings;  Reference figure at https://twiki.cern.ch/twiki/pub/CMS/GlobalTriggerUpgradeL1T-uTme/MenuConditions.png
- There is a common c++ library called “utm” to read/write level-1 Menu XML file.
  The library can be used in CMSSW environment as an external library
  Optional python wrapper can be generated with SWIG
- The utm library can create c++ classes depicted inside the right hand box in the figure (call them event setup classes for now.)
  - emulator can use the event setup classes
  - the condformat in CMSSW should be based on the event setup classes
  - the event setup classes should be comprised of just data members and “dumb”accessor methods to be used as condformat in CMSSW
    - this need to be checked.
- There is another applications that can access menu information stored in OMDS
  - xml to OMDS conversion is performed using a python/SQL scripts
    - the python script reads XML file and creates SQL script, then the menu contents are populated in OMDS using the SQL script.
  - OMDS to xml conversion will be performed using XDAQ/TStore and utm libraries. (under development)
- O2O should read xml information and convert them into condformat which then to be stored in offline database
  - can use either OMDS or xml file as data source, to be decided

**Comment by mulhearn** [comment]
Some updates on this one.  There is a commit here:

   https://github.com/cms-l1t-offline/cmssw/commit/08b95b5acd59968791cc57200252d0086e2025d0

that adds new CondFormat classes extracted from UTM library.

**Comment by mulhearn** [comment]
Brian updates the plan:

```
   1)  Get the utm library and make it work with the current release in the global-jan-dev branch.  This will allow us to configure the emulator in the same way we have been doing for a long time  (XML file  ---> Emulator Classes).

  2) Next merge the new CondFormats Classes into the release.

  3) Make a new Producer that performs the following task:
                   XML File ---> CondFormats  (fill the CondFormats)

   4) Write new code (based closely on what we have already) that:
                      CondFormats --->  Emulator Classes
```

**Comment by mulhearn** [comment]
Instructions for cherry-picking my commit:

```
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-addpkg  CondFormats/DataRecord  # if not there already
git cms-addpkg  CondFormats/L1TObjects   # if not there already
git cherry-pick 08b95b5acd59968791cc57200252d0086e2025d0
```

**Comment by mulhearn** [comment]
Most urgently needed from mike are:
- request inclusion of the candidate /afs/cern.ch/user/t/tmatsush/public/utm-r41543-xsd310-patch.tgz after it passes more tests
- update my commit with derived CondFormat classes to sync with above
- provide 1/2 of the ES producer (the (empty) native UTM -> CondFormat part)
- move the global dev branch to the latest pre-release of CMSSW 80x.

**Comment by mulhearn** [comment]
OK, I moved jan dev branch into 80X_pre4, compiled with latest UTM, and included my PR that includes the scripts and new UTM objects.  I then re-ran my script to update the definition to sync with the latest library.  As expected, only change was related to new number of modules feature:

```
--- a/CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h
+++ b/CondFormats/L1TObjects/interface/L1TUtmTriggerMenu.h
@@ -44,7 +44,7 @@ class L1TUtmTriggerMenu
     L1TUtmTriggerMenu()
       : algorithm_map_(), condition_map_(), scale_map_(),
         external_map_(), token_to_condition_(), name_(), version_(), comment_(),
-        datetime_(), uuid_firmware_(), scale_set_name_() { };
+        datetime_(), uuid_firmware_(), scale_set_name_(), n_modules_() { };

     // dtor
     virtual ~L1TUtmTriggerMenu() { };
@@ -104,6 +104,12 @@ class L1TUtmTriggerMenu
      */
     const std::string& getScaleSetName() const { return scale_set_name_; };

+    /** get number of uGT boards for the menu
+     *
+     * @return number of uGT boards
+     */
+    const unsigned int getNmodules() const { return n_modules_; };
+
     /** set menu name
      *
      * @param x [in] name of the menu
@@ -140,6 +146,12 @@ class L1TUtmTriggerMenu
      */
     void setScaleSetName(const std::string& x) { scale_set_name_ = x; };

+    /** set number of uGT boards for the menu
+     *
+     * @param x [in] number of uGT boards
+     */
+    void setNmodules(const unsigned int x) { n_modules_ = x; };
+
   protected:
     std::map<std::string, L1TUtmAlgorithm> algorithm_map_;      /**< map of algorithm <algorithm name, L1TUtmAlgorithm> */
     std::map<std::string, L1TUtmCondition> condition_map_;      /**< map of condition <condition name, L1TUtmCondition> */
@@ -152,6 +164,7 @@ class L1TUtmTriggerMenu
     std::string datetime_;                                  /**< datetime of the menu */
     std::string uuid_firmware_;                             /**< uuid of firmware */
     std::string scale_set_name_;                            /**< scale set name */
+    unsigned int n_modules_;                                /**< number of uGT boards for the menu */
     unsigned int version;
   COND_SERIALIZABLE;
 };
```

**Comment by mulhearn** [comment]
I have not migrated any of the changes to EventFilter/L1TRawToDigi that were in the jan-dev branch into the new working branch.  There were tons of conflicts, and after using integration branch version for all conflicts, the only change remaining was to add a "GT" to the output label.  We can revisit this later, the commit (suitable for cherry-picking) that contains the entire update to EventFilter/L1TRawToDigi is here:
a64469d3033d2ee663b55389ae62a990b11ec56b

**Comment by mulhearn** [comment]
The new development branch for global (which is now fully up-to date with 80x integration branch) is here:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-jan-dev-CMSSW_8_0_0_pre4

**Comment by mulhearn** [comment]
@puigh @blwiner you are good to go.

**Comment by mulhearn** [comment]
I've only tested that it compile, please sniff around for problems.  

Please see if there's anything missing from the unpacker too.  We can recover it from a64469d if necessary.

I still owe you 1/2 of the ESProducer, but you should feel free to try and make one on your own in case I stall out.  A good example is this one:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-pass3-80x/L1Trigger/L1TCalorimeter/plugins/L1TCaloConfigESProducer.cc

Just ignore the "Helper" wrapper for the CondFormat.  We do that do minimize oversight from DB folks (all functions go there).  You don't need that and can edit directly the CondFormat objects.

**Comment by mulhearn** [comment]
Another quick test would be to run sizeof() over the native utm and corresponding L1TUTM classes, since our plan is to simply cast one as the other, they had better have the same size...

**Comment by mulhearn** [comment]
Oh, it seems I didn't change the #ifndef protection to have a new name for the new classes, which obviously causes problems...  fixing.

**Comment by mulhearn** [comment]
OK, apart from that seems to have dropped right in like we hoped...  I was actually able to write what I hope is most of the ESProducer, thanks to Takashi's demo.  The ESProducer currently parses the demo utm.xml file to make a fake TriggerMenu and puts that into the event setup.  Here's a dump of the Event Setup showing it made it there:

```
L1TUtmTriggerMenuRcd
 start: run: 1 lumi: 0 event: 0 time: 0
 end:   run: 4294967295 lumi: 4294967295 event: 18446744073709551615 time: 18446744073709551615
  L1TUtmTriggerMenu '' provider:L1TUtmTriggerMenuESProducer 'TriggerMenu'
```

I'd like to see that we can retrieve it and read it as in the demo before declaring success, but definitely looking good at this point...

**Comment by mulhearn** [comment]
Looks good.  Here's the output after writing to EventSetup, reading from EventSetup, and dumping to screen:

```
algo name = L1_2MU20_OS
algo exp. = comb{MU20,MU20}[CHGCOR_OS]
algo exp. in cond. = DoubleMU_6984407570981092203
  cond type = 1
    cut name = CHGCOR_OS
    cut target = 10
    cut type = 10
    cut min. value  index = 0 4294967295
    cut max. value  index = 0 4294967295
    cut data = os
...
```

diff'ing with the original test program output shows its identical.

**Comment by mulhearn** [comment]
The new plugins are here:

```
L1Trigger/L1TGlobal/plugins/L1TUtmTriggerMenuDumper.cc
L1Trigger/L1TGlobal/plugins/L1TUtmTriggerMenuESProducer.cc
```

**Comment by mulhearn** [comment]
Takashi writes:

```
if you are happy with the utm-r41543-xsd310-patch.tgz, the tarball can be passed to David.

I think we can attach the tarball to https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1Trigger but if there are better alternative,
that is fine with me.

The instruction of utm library usage is available at;
  https://twiki.cern.ch/twiki/bin/viewauth/CMS/GlobalTriggerUpgradeL1T-uTme
```

**Comment by tmatsush** [comment]
The gzip'ed tarball (utm-r41543-xsd310-patch.tgz) has been attached to the following twiki page;
  https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TGlobal

**Comment by mulhearn** [comment]
Request to David sent.  We'll at least discuss this tomorrow as part of a general discussion of L1T schedule for 80x.

One more test I'd like to do ASAP is to actually write/read-back to/from an sql-lite file.  This will really thoroughly test the serialization directly.  I have never seen something work in sql-lite but not the production DB.

**Comment by tmatsush** [comment]
gitlab repository for utm is now available as requested by David.
  https://gitlab.cern.ch/cms-l1t-utm/utm
the current tag is r41757-xsd310-patch. There is no change in the header files under tmEventSetup since  utm-r41543-xsd310-patch version.

**Comment by tmatsush** [comment]
https://github.com/cms-sw/cmsdist/pull/2111

**Comment by mulhearn** [comment]
Takashi and I worked out the last remaining kinks in our grand plan for L1TGlobal+UTM last night.  This one is closed.

**Comment by tmatsush** [comment]
2016/03/02 22:46、Takashi MATSUSHITA <takashi.matsushita@cern.ch> 

Hi Khristian

I think I can prepare the interface like;

const esTriggerMenu* getTriggerMenu(std::istringstream);

Is this what you want ?
Are you going to use UTM comes with CMSSW ?

Cheers,
Takashi



2016/03/02 20:50、Khristian Kotov <khristian.kotov@cern.ch> :

Hi Takashi,

I see your ESProducer uses UTM library to convert an XML file in the L1 Menu CondFormats
object. Would it be also possible to provide function that creates the object from an XML that
is represented by an std::string? Otherwise, our L1T O2O job would have to write a file once
the menu is fetched from the DB.

Thanks,
 Khristian.
