### ISSUE TITLE
[TODO] Update Stage-1 Tau Lookup Tables

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#72]
New Tau lookup tables were recently brought online.  These will already be in the data tags from O2O, but the MC GTs need to be updated.

Khristian has made a new MC tag  L1TCaloParams_collisions_v3_mc which contains the new payload, taken from TSC_20151020_003550_collisions_BASE. [INCORRECT:  v3 made via config files]

GT currently has L1TCaloParams_collisions_v1_mc, which agrees via has with what is currently online.
Would be nice to confirm that this contains the TauCalibV1 as provided by Isobel, but in any case, collisions_v1_mc is clearly what we want for 76X MC production, since it is online.

**Comment by mulhearn** [comment]
@kkotov, can you handle the GT request?  We need to make this ASAP.  I'm worried it won't make 760... it usually takes a long time to get a new GT.

**Comment by mulhearn** [comment]
@kkotov, also did you confirm that only difference between this payload and previous is the tau lookup table?

**Comment by kkotov** [comment]
@mulhearn, yes I double-checked: tau calib LUT is the only difference between v3 and v4 of the CaloParams. The GT request is posted: https://hypernews.cern.ch/HyperNews/CMS/get/calibrations/2071.html

**Comment by mulhearn** [comment]
sweet!
