### ISSUE TITLE
Phase2 Aging of Muon Detectors and L1T Trigger

### ISSUE THREAD

**Issue by rekovic** [cms-l1t-offline/cmssw#754]
L1T software tools that turn on the aging of the Muon detectors, as
presented in the meetings back in summer of 2018 [1], are available
since the tag  l1t-phase2-v2.16.17.  It is designed for the L1T Muon
group to be easy to use, i.e. with cmsDriver.py command when running
on DIGI's.

One invokes a favorite customisation (can do more then one) to the
cmsDriver.py command depending on which detector you want aged (DT,
CSC, RPC, GEM) 

```
--customise=L1Trigger/Configuration/customiseUtils.appendDTChamberAgingAtL1Trigger
--customise=L1Trigger/Configuration/customiseUtils.appendCSCChamberAgingAtL1Trigger
--customise=L1Trigger/Configuration/customiseUtils.appendRPCChamberAgingAtL1Trigger
---customise=L1Trigger/Configuration/customiseUtils.appendGEMChamberAgingAtL1Trigger
```
and the GlobalTag `100X_upgrade2023_realistic_Candidate_2018_07_26_10_13_24`

These customization does the following
 - envoke in the sequence the detector aging modules, which produce new detector digis with individual hits turned off according to probability map provided in the payload `MuonSystemAging_Phase2-3000fbm1_v1_mc` from the database, contained in the the above GlobalTag.
- chages the inputs of simTriggerPrimitiveDigis to use aged detector digis.
- runs L1T algos with new TriggerPrimitives

This means that all that the analyst has to do is
(1) Run the standard L1T workflow on GEN-SIM-DIGI-RAW sample using
the standard recipe (i.e. without the above customization).
(2) Run the recipe with the above customization and GlobalTag.
(3) Compare the results of (1) and (2).

[1] https://indico.cern.ch/event/752447/contributions/3117091/attachments/1705212/2747480/L1T_SW_Phase2_Weekly_20180827.pdf

**Comment by rekovic** [comment]
The first results of checking effect of the DT aging on Phase2 L1T trigger were showed recently in the presentation [1], showing extreme drop in efficiency (from 99% down to 40%) which is very unreasonable.  

We need to debug the reason for this performance.


[1]
https://indico.cern.ch/event/806863/contributions/3358543/subcontributions/277346/attachments/1814744/2965531/DTAging.pdf

**Comment by battibass** [comment]
@rekovic : 
during today's DT DPG meeting two set of slides were presented ([1](https://indico.cern.ch/event/814473/#sc-4-5-studies-of-legacy-trigg) and [2](https://indico.cern.ch/event/814473/#sc-4-6-studies-of-new-cht-trig)) reporting on the local trigger performance with ageing scenarios as the one used for the Muon TDR. The first set of slides is related to the legacy trigger, the second to the MM/CHT algorithm. Results are consistent among each other and show a drop in efficiency that is much smaller w.r.t. what observed in the presentation you quote.

Also, in the first set of slides, there is one (slide 8) that reports on the expected uGMT performance in case of ageing. Though some use of the RPC is made in the TwinMux along the L1T emulation chain, this should, to my understanding, only relate to the BX correction for existing DT primitives and not to the generation of RPC-only stubs. For such study, the `rerun_test.py` cmsDriver command from [this TWIKI](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TPhase2Instructions#Recipe_AN1) is used for the emulation, of course including DT ageing cutomization. Also the uGMT results point to the fact that efficiency, in case of ageing, should not be dramatically low.

**Comment by rekovic** [comment]
@battibass
Many thanks for the study and the confirmation that the muon aging recipe with instructions 10_1_7 yields the expected and reasonable effect, both with PU0 and PU200 

@bachtis et al, 
We need to double-check the results shown in [1] which contradict the findings above.  Was you study done with 10_1_7 recipe ?

**Comment by battibass** [comment]
Hello, as I am doing some cleanup of old GitHub issues where I am involved, I profit to ask whether this one still needs to remain open.

**Comment by folguera** [comment]
I think this can be closed
