### ISSUE TITLE
Check if TauCalib(v2) should be O2Oed and put into an 80X MC tag.

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#76]
We need to sort out what will happen with Tau Calibration v2.  Is this what we plan to start up with in 2016?  If so, it should be O2O'ed and put into an 80X MC tag.

**Comment by mulhearn** [comment]
E-mailed Isobel/Len/Mario to see what the plan is.

**Comment by isobelojalvo** [comment]
They are meant to be used online at the beginning of 2016. They have not yet been used online.

However, they are currently present in the online DB and are accessible from the online system using this key: L1tauV2Calib.

Khristian has created a baseline version of the L1TCaloParams_collisions_v3_mc tag with the v2 tau LUT.

**Comment by kkotov** [comment]
As we discovered earlier this week, the v3 should not be intent for any future GTs. So the v4, based on v3 was rejected. Given Mike agrees, I'll overwrite the tau calib LUT in v1 (the one we are going to use) and call a new payload v5.

**Comment by mulhearn** [comment]
@kkotov:  No!!! One of us is misunderstanding something.  We need to talk.

**Comment by mulhearn** [comment]
So, all sorted.  We do not yet have an L1 key for all of Stage-1 as intended for running in early 2016.  Isobel suggest we follow this up here:  https://twiki.cern.ch/twiki/bin/view/CMS/L1TCaloCalibration and harass relevant experts.  We won't produce payloads until we have an L1 tag.  Our days of hacking CaloParams together from config files are _over_ (for stage-1...)

**Comment by mulhearn** [comment]
This is a dated issue.  Closing.
