### ISSUE TITLE
[Super Issue] Needed for HI Run

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#82]
This collects all of the known remaining issues for HI running.  Therefore, these are focused on a 75X patch release for online, but it should also go into 80X (and, eventually, to avoid confusion, into a 76X patch)
- #79 
- #68
- #61 (not urgent but already in 76X since pre7)

Note that #68 already includes PRs, but additional related work on the O2O is progressing, but is not needed for the 75X online patch release.  UPDATE:  additional PR will be needed to switch HI emulator to use the dedicated HI record L1TCaloParamsStage1HIRcd.  I guess the emulator will have to switch to which record to request based on the FW version in L1TCaloConfig...

Just collecting the PRs for 75X (most urgent action item) they are:
- cms-sw#12130 (Merged)
- cms-sw#12183 (Merged)
- cms-sw#11677 (Merged)

**Comment by mulhearn** [comment]
@richard-cms is this everything?

**Comment by harmonicoscillator** [comment]
@mulhearn Those reference all the PRs that are currently made, but we're still missing working O2O for HI.

**Comment by mulhearn** [comment]
OK, that's somewhat independent of the release, since we can just patch our O2O locally to get us by.

**Comment by mulhearn** [comment]
But adding to list.

**Comment by mulhearn** [comment]
@richard-cms looks like the O2O will produce a new record for HI (L1TCaloParamsStage1HIRcd).  We'll need to update our code to use this record instead of L1TCaloParamsRcd when the firmware version is an HI version.

**Comment by mulhearn** [comment]
All Prs are merged into 75X, so closing this issue.
