### ISSUE TITLE
Needed for Nov 15ish Deadline for 2016 Emulation

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#91]
We have promised to deliver a working 2016 Emulation by around Nov 15, so that L1 output user code can be modified early in 80X release cycle, and TSG/HLT can perform needed studies. 

Rough sketch for now:
- Standard Sequence Updates including removal of L1Extra (Jim) #94 
- Stage-2 Unpacker Updates (Jim) 
- Menu Building using new L1TNtuple (Chris)
- Global Trigger Updates (Darren, Brian, Mike) issue #95 
- Muon Emulator: issue #93 

Needed soon after deadline:
- Muon Unpackers

**Comment by mulhearn** [comment]
@jimbrooke is the stage-2 unpacker update ready for a PR?

**Comment by jimbrooke** [comment]
There is one feature left to implement and then it is.  (Which is to set output object physical quantities - currently only hardware indices are set).

On 13 Nov 2015, at 15:49, mulhearn <notifications@github.com<mailto:notifications@github.com>> wrote:

@jimbrookehttps://github.com/jimbrooke is the stage-2 unpacker update ready for a PR?

**Comment by mulhearn** [comment]
As we now have a working recipe, considering this one closed.
