### ISSUE TITLE
Discussion on implementation of MuonShowers dataformat

### ISSUE THREAD

**Issue by dinyar** [cms-l1t-offline/cmssw#913]
Hi @rekovic, @dildick,

As discussed yesterday I'm opening a ticket here to discuss further. In https://github.com/cms-sw/cmssw/pull/33446 I mentioned that I don't think that it's a good idea to have "decoding logic" in the data format as it will break compatibility with old data if we decide to change the format. The now merged DF stores the raw bitword and provides member functions that interpret this bitword. Sven correctly pointed out that the data format versioning helps, however this isn't the full story.

What the data format versioning protects us from is if we open digis that were written with an old version of CMSSW. In that case CMSSW will correctly use the old class definition to interpret the bits in the correct way (to my understanding).

What I think we're not protected from is unpacking old RAW data. On the level of the data format I don't think CMSSW has any way to know when this data was taken as it isn't passed e.g. the firmware version. The way this is solved in the L1T is by storing the meaning of the bits in the data format (e.g. `isTwoLooseInTime_`) and to do the decoding of the bitwords in the unpacker itself. The unpacker has access to the firmware version taking the data and therefore can interpret the bits more flexibly.

Cheers,
Dinyar

**Comment by dildick** [comment]
Hi Dinyar, I think I'm following your recommendations though. In the data format I no longer have a function that interprets the bits. Instead I have 4 booleans, with associated getters and setters. This is the version in cms-sw. The version in cms-l1t-offline is superseded.

Some excerpts from the RegionalMuonShower

```
    void setOneNominalInTime(const bool bit) { isOneNominalInTime_ = bit; }
    void setOneNominalOutOfTime(const bool bit) { isOneNominalOutOfTime_ = bit; }
    void setTwoLooseOutOfTime(const bool bit) { isTwoLooseOutOfTime_ = bit; }
    void setTwoLooseInTime(const bool bit) { isTwoLooseInTime_ = bit; }
```
```
    bool isOneNominalInTime() const { return isOneNominalInTime_; }
    bool isOneNominalOutOfTime() const { return isOneNominalOutOfTime_; }
    bool isTwoLooseInTime() const { return isTwoLooseInTime_; }
    bool isTwoLooseOutOfTime() const { return isTwoLooseOutOfTime_; }
```
```
    bool isOneNominalInTime_;
    bool isOneNominalOutOfTime_;
    bool isTwoLooseInTime_;
    bool isTwoLooseOutOfTime_;
```

So if for instance we prefer to trigger on three loose showers, we could change `isTwoLooseInTime_` to `isThreeLooseInTime_` and the CMS version control would recognize the change.

**Comment by dildick** [comment]
See also https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1TMuon/interface/RegionalMuonShower.h#L25-L54 and https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1Trigger/interface/MuonShower.h#L37-L57

**Comment by dinyar** [comment]
Hi Sven,

Ah, you're absolutely right. I must have indeed gotten mixed up with a previous version. Apologies for the noise. Closing.

Cheers,
Dinyar

**Comment by dildick** [comment]
No problem. Thanks for double-checking.
