### ISSUE TITLE
First Pass of the Muon Emulator 

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#93]
Track main issues for the first pass Muon Emulation, available on this topic branch:

   l1t-muon-dev-CMSSW_8_0_0_pre1

Recent emulator meeting minutes with more details here:

   https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerSW/537.html
   https://hypernews.cern.ch/HyperNews/CMS/get/L1TriggerSW/529/2.html

In particular, the short term TODO list:
- Mike to propose reworking of MuonTriggerPrimitive into L1TMuon package instead of a DataFormat (DONE:  Now in to-be deprecated area of L1TMuon)
- Mike will merge commits from PR for official CMSSW into development branch. (DONE) 
- Mike to make name changes proposed in last meeting (DONE)
- Mike to fix the top-level directory names. (DONE)
- All to continue work on version 1 Emulator, with correct I/O dataformats, algorithm encapsulated for easy versioning (Priority 1).
- All to continue to work on CondFormats migration (Priority 2)
- All to work on Unpackers/Packers (Priority 3)
- Mike to finish a few minor renames (DONE)
- Mike to check software at I/O block diagram level (DONE)
- Mike to purge obsolete Data/Formats (DONE)
- Mike to produce configs / full system tests (DONE)
- Mike to check if SealModule files are needed (Moved to individual plugins src files)

And the system block diagram for simDigi production is now:

```
L1TMuonProducer
  produces:  1tMuonBXVector + "simGmtDigis" + "" "L1TMuonEmulation"
  consumes RegionalMuonCandBxCollection
  consumes GMTInputCaloSumBxCollection 

BMTrackFinder (renamed  L1TMuonBarrelTrackProducer)
  produces l1t::RegionalMuonCandBxCollection
  consumes legacy RPC digis (not yet in code)
  consumes legacy L1 DT digis
  consumes *TBD* TwinMux producer output digis (in version 1)

OMTFProducer (renamed  L1TMuonOverlapTrackProducer)
  produces RegionalMuonCandBxCollection
  consumes legacy RPC digis
  consumes legacy L1 DT digis
  consumes legacy L1 CSC digis
  consumes *TBD* TwinMux producer output digis (in version 1)
  consumes *TBD* CCPF ProducerOutput    (in future version)
  *currently* consumes TriggerPrimitiveCollection, to be removed.

L1TMuonUpgradedTrackFinder (renamed L1TMuonEndCapTrackProducer)
  produces RegionalMuonCandBxCollection
  consumes legacy RPC digis
  consumes legacy L1 CSC digis
  consumes *TBD* CCPF ProducerOutput    (in future version)
  *currently* consumes TriggerPrimitiveCollection, to be removed.

L1TMuonTwinMuxProducer (does not exist yet, needed for version 1)
  produces **TBD***
  consumes legacy L1 DT digis (presumed)
  consumes legacy RPC digis (presumed)

L1TMuonFwdSuperPrimProducer (For CCPF, does not exist yet, needed for a future version)
  produces **TBD***
  consumes legacy L1 CSC digis (presumed)
  consumes legacy RPC digis (presumed)
```

Noting some remaining major problems:
- L1TMuonEndCap:
  - still seems to rely on deprecated L1TriggerPrimitive ? 

Noting some remaining problems here:
- L1TMuonEndCap:
  - move root files from include directory to L1TMuon/data, or delete if not needed (DONE)
  - move lut files from src directory to L1TMuon/data (DONE)
  - there are .o files in github... we need to discuss build of this package. (DONE)
  - there is a CVS file... we need to discuss bookkeeping of fw versions. (Removed, and it is OK)
  - L1TMuonOverlap
  - move L1TMuonOverlap/data to L1TMuon/data/omtf_XXX (you pick appropriate XXX)
- L1TMuon and L1TMuonBarrel both look ready to go.

**Comment by mulhearn** [comment]
Noting build warning:

```
Warning in <TInterpreter::ReadRootmapFile>: class  edm::Wrapper<vector<csc::L1Track> > found in libDataFormatsL1CSCTrackFinder.so  is already in libDataFormatsL1TMuon.so 
```

It seems this is due to unneeded things in:

```
/DataFormats/L1TMuon/src/classes.h
```

I'll clean this up after removing the deprecated data objects.

(This is now fixed)

**Comment by mulhearn** [comment]
Further items for discussion:
- role of L1TMicroGMTCaloInputProducer and GMTInputCaloSumBxCollection
- is there an unpacker planned for GMTInputCaloSumBxCollection?

Answer:   It is emulating actual hardware which will eventually be read out, so a dedicated data format is called for.

**Comment by mulhearn** [comment]
Review of DataFormats:
- BMTrackCand.h (Delete)
- BMTrackContainer.h (Delete)
- GMTInputCaloSum.h (Keep)
- GMTInternalMuon.h (Move to L1TMuon/src, used internally for calculation)
- MuonCandidateTrack.h (Try Deleting See What Complains)
- MuonInternalTrack.h (Move local L1TMuonEndCap)
- MuonTrackSeed.h (Try Deleting See What Complains)
- MuonTriggerPrimitive.h (Deprecate... but still work needed from EndCap.) 
- RegionalMuonCand.h (Keep)

Mike to look into Fwd classes whether worthwhile to remove.  Update:  Indeed, this seems to be a good case for forward declarations due to the templates.   However, we can probably consolidate all these Fwd headers into one L1TMuon/include/Fwd.h class.

**Comment by mulhearn** [comment]
OK, so DataFormats are cleaned up.

**Comment by mulhearn** [comment]
Now some last minor name changes (DONE) and start integrating!

**Comment by mulhearn** [comment]
Noting for later, we are missing these guys:
  T_EventSetup_CaloConfig.cc
for the new CondFormats...  will be needed at some point before putting in DB.
Also:
  CondCore/L1TPlugins/src/plugin.cc

**Comment by mulhearn** [comment]
PR for L1TMuon/data is here:
https://github.com/cms-data/L1Trigger-L1TMuon/pull/1

**Comment by mulhearn** [comment]
Woo hoo!  I just ran the entire Muon emulation chain, including input from Stage2Layer1 Calo.  I see everyone producing the correct digis:

```
    10 occurrences of key L1MuDTChambPhContainer + "simTwinMuxDigis" + "" "L1TMuonEmulation"
    10 occurrences of key l1tCaloTowerBXVector + "caloStage2Layer1Digis" + "" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "imdMuonsBMTF" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "imdMuonsEMTFNeg" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "imdMuonsEMTFPos" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "imdMuonsOMTFNeg" "L1TMuonEmulation"
    10 occurrences of key l1tMuonBXVector + "simGmtDigis" + "imdMuonsOMTFPos" "L1TMuonEmulation"
    10 occurrences of key l1tMuonCaloSumBXVector + "simGmtCaloSumDigis" + "TriggerTower2x2s" "L1TMuonEmulation"
    10 occurrences of key l1tMuonCaloSumBXVector + "simGmtCaloSumDigis" + "TriggerTowerSums" "L1TMuonEmulation"
    10 occurrences of key l1tRegionalMuonCandBXVector + "simBmtfDigis" + "BM" "L1TMuonEmulation"
    10 occurrences of key l1tRegionalMuonCandBXVector + "simBmtfDigis" + "BMTF" "L1TMuonEmulation"
    10 occurrences of key l1tRegionalMuonCandBXVector + "simEmtfDigis" + "EMTF" "L1TMuonEmulation"
    10 occurrences of key l1tRegionalMuonCandBXVector + "simOmtfDigis" + "OMTF" "L1TMuonEmulation"
```

**Comment by mulhearn** [comment]
And the output of the GMT seems reasonable (single Muon particle gun):

INFO:  found muons!
bx:  0  et:  139  eta:  0.793875  phi:  -2.90171
INFO:  found muons!
bx:  0  et:  139.5  eta:  -0.10875  phi:  0.959904
INFO:  found muons!
bx:  0  et:  139.5  eta:  0.50025  phi:  1.82164
INFO:  found muons!
bx:  0  et:  125.5  eta:  -0.06525  phi:  -2.32358
INFO:  found muons!
bx:  0  et:  53.5  eta:  -0.967875  phi:  1.16716
bx:  0  et:  39.5  eta:  -0.89175  phi:  1.16716
INFO:  found muons!
bx:  0  et:  139.5  eta:  -0.348  phi:  2.44339
INFO:  found muons!
bx:  0  et:  139.5  eta:  -0.641625  phi:  -1.81091
INFO:  found muons!
bx:  0  et:  12.5  eta:  -0.554625  phi:  2.66155
INFO:  found muons!
bx:  0  et:  42  eta:  0.380625  phi:  1.3635
INFO:  found muons!
bx:  0  et:  139.5  eta:  -0.511125  phi:  2.65064

**Comment by mulhearn** [comment]
I am beginning the integration of this branch:
https://github.com/cms-l1t-offline/cmssw/tree/l1t-muon-dev-CMSSW_8_0_0_pre1
At this time, the last commit is 36eec540ca465fbc83eac5b6b34acfb8b06b770c.
I am recording this so people can continue to develop on this branch, and I will integrate the changes later.

**Comment by thomreis** [comment]
Hi Mike,
Is this intended that the Calo2Layer2 label takes a Calo2Layer1 product as input?
https://github.com/cms-l1t-offline/cmssw/commit/edf37b325c437579ce52e51e4bb34bc075600a6a#diff-c960dc028aaf5b29d3c71677ac79582dR6 in L1Trigger/L1TMuon/python/simMuonDigis_cfi.py ?

**Comment by mulhearn** [comment]
I'll double check.  Based on what I saw, Muon system uses output of Stage2Layer1.

**Comment by mulhearn** [comment]
(Sometimes it can be ambiguous when systems save inputs and outputs)

**Comment by mulhearn** [comment]
Noticing we'll probably need to cleanup namespace... there's some very generic terms in global namespace in some of the library.  Seem guaranteed to cause trouble.

**Comment by jimbrooke** [comment]
Regarding input from calo trigger - both Stage2Layer1 and Stage2Layer2 emulator modules produce the same L1CaloTower data format.  This is intentional code re-use.  Of course, the "correct" source depends on a hardware solution that does not exist right now.  Suggest to use Layer1 output for now.  But take care how this is presented to end-users...

**Comment by thomreis** [comment]
I have tried to run the muon emulator chain of the l1t-muon-CMSSW_8_0_0_pre1 branch using the runMuon.py config file.
This finishes without problems and produces all the data objects I expect. 

However, the EMTF RegionalMuonCandBxCollection that I get does not contain any muons. 
I have processed 50 events from Giannis' file to test and there are only muons from OMTF and BMTF.

The input collection for the EMTF producer is not empty as far as I can tell.

**Comment by mrcarver** [comment]
Hi Thomas,

Not to ask a stupid question, but have you made sure that the input file has gen muons with eta > 1.2? If the file was from Giannis and for the barrel this may not be the case.

I will also try to run with another file to see if I can produce a positive result from the EMTF.

Thanks,
Matt

**Comment by gflouris** [comment]
Hi guys,

Matt is right, all of my root files contain muons with eta<1. You can use the ParticleGunGenerator_Muon.py file which is located in the same directory as the root file to generate a sample with different eta.

Giannis

**Comment by thomreis** [comment]
OK, then I will try with a different file. So when I saw inputs from CSC they must have been in the overlap region.

Perhaps we should use a different test file by default.

**Comment by mrcarver** [comment]
Also for future reference I've been able to run the EMTF on Run2015D data with a few modification to config file and can send an email with the details if anyone is interested.

**Comment by thomreis** [comment]
I would be interested in this yes.

**Comment by mulhearn** [comment]
Yes, that was bare bones test of throughput.  (Improvements welcome, even simply a starting file that has muons out to higher eta)

**Comment by mulhearn** [comment]
The first pass muon emulator is in the integration branch, this one is closed.
