### ISSUE TITLE
Standard Sequences Update

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#94]
Jim is largely handling this, I'm just keeping track of a few things here.  Topic branch is here:

https://github.com/cms-l1t-offline/cmssw/blob/l1t-sequences-80X

**Comment by mulhearn** [comment]
Assuming we want to deprecate this:

   https://github.com/cms-sw/cmssw/blob/CMSSW_8_0_X/Configuration/DataProcessing/python/RecoTLR.py#L77

We should probably blow away any obsolete customizations and see who complains.

**Comment by jimbrooke** [comment]
One thing to note - the change in standard sequences probably requires a review of EventContent from L1 trigger.  This is partially started in the topic branch.

**Comment by mulhearn** [comment]
Yes, good.   I'd like to have a simple module that simply text outputs a summary of how many non-zero objects of each type of L1T object is in each event.  You can debug a whole lot this way (or at least see what part of chain is broken) at a glance.

**Comment by mulhearn** [comment]
The topic branch:
  https://github.com/cms-l1t-offline/cmssw/blob/l1t-sequences-80X
is based on nightly "CMSSW_8_0_X_2015-11-10-2300".
Mike will rebase this to a pre release.

**Comment by mulhearn** [comment]
This one is finished.
