### ISSUE TITLE
Remaining issues for 2016 Global Trigger Emulation

### ISSUE THREAD

**Issue by mulhearn** [cms-l1t-offline/cmssw#95]
The new UTM library has been integrated with CMSSW since integration build 

```
CMSSW_8_0_X_2016-01-29-2300
```

An integration branch, only for critical updates, has been created at:
   https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-CMSSW_8_0_X_2016-01-29-2300
It compiles and runs in the L1T standard sequences, and is ready for integration with CMSSW.

A development branch, for ongoing work, has been created at:
   https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-CMSSW_8_0_0_pre5
This release predates the inclusion of UTM in CMSSW, so the library will still need to manually configured.

The remaining topics on this thread:
- Mike needs to recast slightly the L1TGlobalUtils as a CMS-wide interface.
- O2O plan for masks and prescales

**Comment by puigh** [comment]
The prescales and masks are already implemented in the l1t-global-dev-CMSSW_7_6_0 branch. They are currently read in via a .csv file. @blwiner has implemented code to get trigger names and bits in the same branch.

**Comment by mulhearn** [comment]
Indeed, I believe this is all done except my part, just dumped the minutes from last Friday without updating the status yet...

**Comment by mulhearn** [comment]
I've checked there is a Run container in the event data, so our plan to push this to the event data and provide a simple interpreter should work fine...

**Comment by mulhearn** [comment]
Mike needs to read up and understand latest updates to GtProducerObjectMapRecord... but seems like ready for HLT to test.

**Comment by mulhearn** [comment]
@blwiner @puigh dramatic progress on this thread.  Please note the summary by following the link to the original github issue.  Please switch to using the new development branch (https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-CMSSW_8_0_0_pre5), which still requires manual installation of utm, for your ongoing work (this is a slight change from what we discussed, but will make future integration smoother).

**Comment by blwiner** [comment]
Mike,

  Does this new branch have all the changes that were pushed yesterday to
the global-jan-dev_pre4 branch?

 -Brian

On Sat, Jan 30, 2016 at 2:17 PM, mulhearn notifications@github.com wrote:

> @blwiner https://github.com/blwiner @puigh https://github.com/puigh
> dramatic progress on this thread. Please note the summary by following the
> link to the original github issue. Please switch to using the new
> development branch (
> https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-CMSSW_8_0_0_pre5),
> which still requires manual installation of utm, for your ongoing work
> (this is a slight change from what we discussed, but will make future
> integration smoother).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/issues/95#issuecomment-177280350
> .

## 

---

B. Winer

**Comment by mulhearn** [comment]
Fully up to date.  Note for the future you can check this by looking at the two branches in github and comparing the commit history... one of the many reasons I abandoned the experimental policy of quashing commits.

**Comment by mulhearn** [comment]
@blwiner @puigh I added this commit db8953de8f599c7031b0ac6856ed843b4c079699 to L1TGlobal in your development branch
https://github.com/cms-l1t-offline/cmssw/tree/l1t-global-CMSSW_8_0_0_pre5
which extends the legacy Object Map to include the object type, and fills it in the emulator, as needed for the L1T/HLT interface.  Can you have a closer look and make sure that everything is sound?

**Comment by mulhearn** [comment]
Looking again, in addition to the warning, I should probably push -1 as the object type if no match is found... so at least the other operands are not out of sync.

**Comment by mulhearn** [comment]
UTM version of L1TGlobal has been in release for some time.  This one is closed.
