### ISSUE TITLE
Removing TkPrimaryVertex from L1T P2 Code

### ISSUE THREAD

**Issue by BenjaminRS** [cms-l1t-offline/cmssw#998]
There remains an older version of the vertexing in the current code: [TkPrimaryVertex](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TCorrelator/interface/TkPrimaryVertex.h). @cecilecaillol points out that TkPrimaryVertex is still used in:

L1Trigger/L1TTrackMatch/plugins/[L1TkEmParticleProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc)
L1Trigger/L1TTrackMatch/plugins/[L1TkFastVertexProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc)
L1Trigger/L1TTrackMatch/test/[L1TrackObjectNtupleMaker.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc)
L1Trigger/Phase2L1ParticleFlow/plugins/[L1TPFProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/Phase2L1ParticleFlow/plugins/L1TPFProducer.cc)
L1Trigger/Phase2L1Taus/plugins/[HPSPFTauProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/Phase2L1Taus/plugins/HPSPFTauProducer.cc)
L1Trigger/Phase2L1Taus/src/[L1HPSPFTauBuilder.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/Phase2L1Taus/src/L1HPSPFTauBuilder.cc)

Can we now go ahead and remove this older vertex reconstruction from the code base?

**Comment by BenjaminRS** [comment]
From my side:

- I will look at changing the [L1TrackObjectNtupleMaker.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc) to read the newer format: it was just an oversight that this used the older vertex as an iterator.

- I saw that the issue with this older vertexing was brought up by [Andrea P a year ago](https://github.com/cms-sw/cmssw/pull/33794#discussion_r635869462), where he suggested to clean up the code with obsolete classes

- The [L1TkFastVertexProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkFastVertexProducer.cc) and [L1TkEmParticleProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc) was introduced by Vladimir in [PR#30363](https://github.com/cms-sw/cmssw/pull/30363)

**Comment by BenjaminRS** [comment]
Hi again, I have looked at [L1TrackObjectNtupleMaker.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc) and found that the code doesn't actually use [TkPrimaryVertex](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TCorrelator/interface/TkPrimaryVertex.h). It still names collections e.g. L1TkPrimaryVertexHandle, and this can be changed any time to make it clear it is not actually the TkPrimaryVertex collection which is being used.

So from the GTT side we are happy to drop the TkPrimaryVertex collection.

**Comment by BenjaminRS** [comment]
@cerminar Can you confirm that the [L1TkEmParticleProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc) is not used please?

**Comment by cerminar** [comment]
Hello @BenjaminRS 
[L1TkEmParticleProducer.cc](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/L1Trigger/L1TTrackMatch/plugins/L1TkEmParticleProducer.cc) is the producer of the simulated TkEM objects used during the L1-TDR studies. It can be phased out since we now have the corresponding emulator in place. 

I was actually planning to remove it together with the TkElectron producer (at least from the sequence) but I was asked to wait since HLT was in the process to switch to the emulated inputs. I assume this is now done?

**Comment by cbotta** [comment]
As you can see in the MenuToools Twiki prepared by @jheikkil, used by HLT people: 
- starting from 11_1_7, we have performed full validation with emulators and we used the VertexFinder emulation: https://twiki.cern.ch/twiki/bin/viewauth/CMS/PhaseIIL1TriggerMenuTools#Object_producers_emulators, so I think we can remove the tkPrimaryVertex from this point onwards (and the idea is to remove it in the porting to current master)
- before, i.e. CMSSW_11_1_3, i.e. the Menu used for the HLT-TDR, simulation was used, and in particular the L1TkPrimaryVertex, as documented here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/PhaseIIL1TriggerMenuTools#Objects_producers_simulation
----> I think that now @trtomei has moved to running the new Menu with emulators, so it is fine to proceed. @trtomei  can you please confirm?

**Comment by gpetruc** [comment]
Hi,

For what matters `/L1Trigger/Phase2L1ParticleFlow/plugins/L1TPFProducer.cc`, it's only used in the old emulator (i.e. `l1pfCandidates` and not `l1ctLayer1`). In the 12_3_X branch would in fact like to remove the old emulator entirely, if the menu team can confirm that they don't need them anywhere downstream.

**Comment by BenjaminRS** [comment]
I think we can close this one - the TkPrimaryVertex collection was removed in [PR#1026](https://github.com/cms-l1t-offline/cmssw/pull/1026)
